packages/blockchain-wallet-v4/src/types/Wallet.spec.js
This fixes two failing tests that broke in the move from addAddress -> importLegacyAddress
I'm not sure whether thats the proper way to test Tasks, currently I resolve them and do the `expect` calls in the closure. 
Furthermore, it looks like encryption isn't happening in the second test case. In particular, `wallet.double_encryption` is `false`, which short circuits any encryption in `applyCipher`. I don't understand enough about this API yet to know how to fix it though.
=> chore(Tests): Fix failing tests for Wallet.addAddress -> importLegacyAddress

package.json, packages/blockchain-wallet-v4-frontend/webpack.config.js
Improve Webpack performance, result on my machine (depends on the # of cores)
Command "`npm run build:prod`"
Results:
3m18.341s
3m21.134s
3m16.703s
2m34.049s
2m28.473s
2m23.440s
~= 25% faster
2m49.154s
3m1.668s
2m55.644s
~= 12% faster
1m53.143s
1m50.950s
1m50.899s
__~= 44% faster__
- The thread-loader improvement should also impact positively the dev build.
- I did not benchmark the "cache" property on uglify, the impact can be __HUGE__,
however it depends on how many files were changed since the last compilation.
- https://github.com/webpack-contrib/thread-loader
- https://github.com/webpack-contrib/uglifyjs-webpack-plugin
=> Improve Webpack config to minimise build time

packages/blockchain-wallet-v4/src/redux/data/coinify/sagas.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
This should fix the issue of options being `undefined` when it gets passed to the partner services.
Because of the sagas refactor, SFOX and Coinify each have a `refresh` and `get` saga. I don't want to go through now and sort that out, but when the Coinify implementation gets merged that'll be cleaned up.
Let me know if you're still seeing issues.
=> make sure options is not undefined

Dockerfile
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Sockets): add new vars to dockerfile

Dockerfile
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Sockets): check correct ws args

README.md, packages/blockchain-wallet-v4-frontend/webpack.config.js, server.js
- Add all coin WebSocket URIs to default configuration for Express server.
- Log all coin WebSocket configurations when Webpack and Express server starts.
- Updates code coverage badge url to point to development branch
Bug Fix, CI/CD
N/A
=> Missing pieces for new WebSocket URIs

packages/blockchain-wallet-v4-frontend/src/scenes/Recover/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Recover/SecondStep/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Reminder/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Reset2FA/FirstStep/template.js, packages/blockchain-wallet-v4-frontend/src/store/index.js, packages/blockchain-wallet-v4-frontend/src/store/index.spec.js
- Fixes issue where socket saga registration was failing in development branch due to merge issue
- Ensure passwords match on wallet recovery page
- Better stying for wallet recover form
- Better stying for other help form footers
Bug Fix
Login page => other  => recover wallet => enter mnemonic phrase => enter mismatching passwords => error
=> Recover wallet passwords must match

packages/blockchain-info-components/package.json, packages/blockchain-info-components/src/Dropdowns/SimpleDropdown/index.js, packages/blockchain-info-components/src/Form/SelectInput/SelectInput.spec.js, packages/blockchain-info-components/src/Form/SelectInput/__snapshots__/SelectInput.spec.js.snap, packages/blockchain-info-components/src/Tooltip/Tooltip.spec.js, packages/blockchain-wallet-v4-frontend/src/components/Form/NumberBox/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Form/NumberBox/index.spec.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PasswordBox/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Form/PasswordBox/index.spec.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.spec.js, packages/blockchain-wallet-v4-frontend/src/components/Form/RadioButton/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Form/RadioButton/index.spec.js, packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBox/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBox/index.spec.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Confirmations/index.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/index.spec.js, packages/blockchain-wallet-v4-frontend/src/layouts/Addresses/index.js
There were about 15 annoying warnings that were being logged when running the unit tests.  I cleaned up test code and added proper mocks to fix all of them.
Cleanup
Run unit tests and observe no more red warning messages
=> Clean up React warnings from test runs

packages/blockchain-wallet-v4/src/redux/kvStore/shapeShift/sagas.js
Android could not correctly parse an empty ss metadata entry. This changes the initial entry for USAState to null instead of empty string
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(KV): create ss entry with USAState null for android parsing

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/IPWhitelist/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/IPWhitelist/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/PasswordHint/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/PasswordHint/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/PasswordStretching/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/PasswordStretching/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/SecondPasswordWallet/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/SecondPasswordWallet/Settings/template.js
onSubmit is required and prevents from crashing when we hit enter on the form
- Bug Fix
=> add onSubmit to password stretching form

packages/blockchain-wallet-v4/src/exchange/convertFiatToBitcoin.spec.js, packages/blockchain-wallet-v4/src/exchange/currency/index.js, packages/blockchain-wallet-v4/src/exchange/displayFiatToBitcoin.spec.js
use Number.toFixed instead of BigRational.toDecimal, because toDecimal always rounds it down
819
- Bug Fix
=> fiat conversion

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/QuoteInput.js
Refactor SFOX quoteInput to no longer use `getDerivedStateFromProps`
Reason here: https://github.com/facebook/react/issues/12898
- Bug Fix
Sfox account --> fetch some quotes
=> Quote Input Improvement

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js
Stores the current guid in cache for users to be able to easily re-login with.  Also ensure the login form state is not cleared until well into the login saga so user see notice an empty form during login routine.
Feature, Bug Fix
Login with existing wallet and login => see the guid is stored.
Create new wallet and logout => see the guid is stored.
=> feat(remember guid during login and account creation)

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js
1041
- Bug Fix
Create wallet with 2fa, logout, enter password incorrectly, enter 2fa. See that your pw is incorrect, correct password, get new 2fa code, login.
=> fix(Login): when 2fa is required after incorrect pw

README.md
Added npm version dependency to README:
`npm ci` requires npm>=6
- Bug Fix
- [+] Code compiles successfully (verified via `yarn start`)
- [+] No lint issues exist (verified via `yarn lint`)
- [+] New and existing unit tests pass (verified via `yarn test`)
- [+] `README.md` and other documentation is updated as needed
=> Fix - added minimal npm version to README

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBitcoin/FirstStep/template.success.js
Display private key doesn't match on the bottom, and also force validate by calling touch. right now if you enter a valid bitcoin private key  that doesn't match the watch only public key, the error isn't displayed unless you click on the text box, that causes some other problems.
isCashAddr is necessary after all, you were right. but it has to run after ```bip21.decode(data, 'bitcoincash')```
- Bug Fix
- CI/CD
=> Qr error message

packages/blockchain-wallet-v4-frontend/src/data/modules/coinify/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js
Wait for second password prompt to succeed before placing sell trade.
- Bug Fix
=> fix(trigger coinify loading after second password prompt)

packages/blockchain-wallet-v4/src/redux/walletSync/middleware.js
Receive index is undefined for archive wallets. So in case of notifications being on sync failed.
- Bug Fix
1. Add an archived wallet
2. Turn on any of notifications
3. Add another wallet
4. Sign out
5. Sign in
6. All wallets should remain in place
=> fix - fixed address derivation for archived wallets

packages/blockchain-wallet-v4-frontend/src/data/components/manageAddresses/reducers.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/reducers.js
Remote.Failure can not be used without being called, like Remote.NotAsked or Remote.Loading
That's the [library](https://github.com/fantasyland/daggy) limitation
Fixes send form crashing after send btc form initialization error
- Bug Fix
1. Force a crash on send btc form saga with a throw
2. Open buy/sell
3. Page should not break
=> fix - fixed Remote.Failure used without being called

packages/blockchain-wallet-v4-frontend/src/modals/RequestBch/index.js, packages/blockchain-wallet-v4-frontend/src/modals/RequestBitcoin/FirstStep/index.js
Refetching data in BTC/BCH request forms if one is missing.
- Bug Fix
1. Grab a state from 1108 issue
2. Load it while logged in or twice
3. Open request dialog - get an error ( loading state while logged out yields no error message)
4. Click on refresh
5. Should show a request window
=> fix - refresh fixed missing BTC/BCH data in request modal

packages/blockchain-wallet-v4-frontend/src/data/components/refresh/sagas.js, packages/blockchain-wallet-v4/src/network/api/wallet/index.js
Home page activity stream is not refreshed without transaction refetch
- Bug Fix
1. Make a transaction that won't show up in the activity stream, btc state from 1108 is valid
2. Click refresh while on the main page
3. See activity stream refreshed
=> fix - refetching all transactions for activity stream while on the home page

package-lock.json, packages/blockchain-wallet-v4/package.json, packages/blockchain-wallet-v4/src/coinSelection/coin.js, packages/blockchain-wallet-v4/src/coinSelection/coin.spec.js, packages/blockchain-wallet-v4/src/signer/bch.js, packages/blockchain-wallet-v4/src/signer/btc.js
Inputs and outputs are now sorted according to [bip69 spec](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki)
- Upgrades
=> upgrade - added input & output bip69 sorting for btc/bch

packages/blockchain-wallet-v4-frontend/src/components/BuySell/Failure.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Confirm/index.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Payment/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Upload/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/Buy/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderHistory/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/Sell/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/index.js
Adds a template for Failure state to buy/sell components
- Feature
Throw an error in an important saga like fetching profile or trades, see a failure template
=> BuySell failure templates

packages/blockchain-wallet-v4/src/utils/bitcoin.js
fixed 804. i'm a little concerned because it seems like this was intentionally omitted originally.
- Feature
=> add support for mini key format

packages/blockchain-wallet-v4/src/redux/kvStore/btc/selectors.js, packages/blockchain-wallet-v4/src/redux/walletSync/middleware.js
Added unused labeled addresses to active addresses sync.
- Upgrades
1. Turn off notifications
2. Add labeled address to account
3. Receive funds through request to get account's receive index past the labeled address index.
Look for receive index in `dataPath.bitcoin.addresses[account's xpub].account_index`.
Look for labeled addresses receive index in `walletPath.wallet.hd_wallets[0].account[find your account].address_labels[find your label].index`
4. Turn on notifications
5. Send funds to labeled address
6. Receive notification
=> upgrade - added unused labeled addresses to notificaions sync;

.gitignore, README.md, config/ssl/ssl.md, packages/blockchain-wallet-v4-frontend/webpack.config.js
Upcoming features will require application to be served over HTTPS. This PR allows the Webpack dev server to auto-start with HTTPS enabled if `.pem` files are found in the `config/ssl` folder.  If the files are not found, the server will fallback to HTTP
Feature
Follow readme instructions to enable SSL
=> Feature(localhost SSL support)

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/IPWhitelist/Settings/index.js
Fixes: When a new wallet is created, the user isn't able to clear the ip whitelist because redux doesn't like the fact that it doesn't have an initial data value. 
- Bug Fix
New wallet > Advanced Security settings > add ip to whitelist > remove ip from whitelist
=> fixed redux form issue with ipwhitelist

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js
If you held up an invalid btc qr code it wouldn't throw error. Now it does.
#799
- Bug Fix
=> fix(Btc Send): made invalid btc QR code throw error

package.json
- eslint does not support json files. It causes errors during pre-commit hook
Resolves #839 
Removed eslint on json files in `lint-staged` as it causes parsing errors.
- Bug Fix
Stage a json file and trigger pre-commit hook
=> fix(linter): Remove eslint for *.json files

packages/blockchain-wallet-v4-frontend/src/assets/locales/defaultMessages.json, packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxUSState/index.js
Fixed the placeholder text for state dropdowns to say 'select state' instead of 'select country': 1096, 1188
- Bug Fix
=> fix(State select dropdown): placeholder text

packages/blockchain-wallet-v4/data/index.js, packages/blockchain-wallet-v4/data/wallet.v3-with-legacy.json, packages/blockchain-wallet-v4/src/redux/kvStore/bch/selectors.js, packages/blockchain-wallet-v4/src/redux/kvStore/bch/selectors.spec.js, packages/blockchain-wallet-v4/src/redux/wallet/selectors.js, packages/blockchain-wallet-v4/src/redux/wallet/walletSelectors.spec.js
Fixes 0-balance issue for imported addresses with a BCH balance. The problem was with the selection of the address context: an unnecessary call to `keysIn` resulted in the address context consisting of the address array indices (rather than the actual addresses).
- Bug Fix
1. Imported an address with a BCH balance
2. See that the wallet-level BCH balance remains at 0
=> Include BCH imported addresses in total balance

packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/index.js
I missed this when I went through the `.data` cleanup. We shouldn't use getOrFail here, because the trade is not always required. For a new account, for example, this was breaking the Coinify experience. QA would have been blocked by this.
- Bug Fix
=> do not use getOrFail

packages/blockchain-wallet-v4/src/network/api/kvStore/index.js
1296
Because a `network` was not passed to KV.magic() a function was returned instead and set as the kv's magicHash. The next time a user tried to interact with this entry an error would be thrown because magicHash was not a buffer but a function.
- Bug Fix
=> fix(Metadata): pass network to magic from md api

packages/blockchain-wallet-v4/src/network/api/sfox/index.js
Hotfix for issue where users were uploading docs and sfox received them as 0 byte files
- Bug Fix
=> fix(SFOX): use body for doc upload PUT

packages/blockchain-wallet-v4/src/redux/kvStore/shapeShift/selectors.js
fixes 1308
- Bug Fix
Use account with trades from v3 and v4.
Trades should be sorted with no dependency on wallet version
=> fix(shapeShift): sorting trades latest first

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ImportedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ImportedAddresses/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/template.success.js
Related to https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/998
- Feature
1) on prod, import a vulnerable address (1AzoywD7PezZoVV2YeRcrrfBb6KEhYYW9Z, for ex)
2) go to settings --> wallets
3) the page should still be usable
=> Retain functionality with remote data failure

packages/blockchain-info-components/src/Form/PasswordInput.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PasswordBox/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js
- Lastpass was remembering last used SMS codes and Yubikey entries. Not any longer.
- Feature
- Bug Fix
Login to accounts that have 2FA enabled and lastpass wont be on those fields
=> feat(disable lastpass on 2fa login fields)

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/Announcements/Service/selectors.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/rootReducer.js, packages/blockchain-wallet-v4-frontend/src/index.dev.js, packages/blockchain-wallet-v4-frontend/src/index.prod.js, packages/blockchain-wallet-v4-frontend/src/scenes/app.js, packages/blockchain-wallet-v4-frontend/src/store/index.js, packages/blockchain-wallet-v4-frontend/src/store/index.spec.js, yarn.lock
- Fix to ensure service announcements show even when there is cache miss for announcement states (e.g. incognito browsing)
- Easiest fix was to update to v5 of `redux-persist` that adds the `PersistGate` component that will not render the UI until the cache is completely loaded. Without this there would be screen flickering of the banner if it was previously dismissed
- Followed the v4 to v5 migration guide [here](https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md#experimental-v4-to-v5-state-migration)
- Bug Fix
- Upgrades
- Ensure your wallet GUID is still being auto-loaded from cache upon signon
=> Feat(Service announcements fix & redux-persist v5 migration)

packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/middleware/streamingXlm.js
- Removes falsey values from accountId list before starting XLM stream
- Ensures future writes to Lockbox kvstore always have a public key
- Bug Fix
- CI/CD
- Wallets with Lockbox and kvStore XLM fetch errors should now load
=> Fix(XLM KvStore fetch)

packages/blockchain-wallet-v4-frontend/src/data/components/bchTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/bsvTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/btcTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bch/ImportedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bch/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Transactions/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Transactions/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ArchivedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ImportedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Menu/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/Empty/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Menu/template.js
- Use a single redux form (`walletTxSearch`) for all sub-menu search boxes (transaction list pages & settings/address pages)
- Small refactor for send BSV sagas to avoid setting unneeded variables
- Tech Debt
- BSV send works
- Transaction list and wallet list searches work
=> Fix(BSV tech debt)

packages/blockchain-wallet-v4-frontend/src/data/components/bchTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/bchTransactions/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/bsvTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/btcTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/btcTransactions/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/ethTransactions/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/form/model.js, packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/bch/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/btc/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/model.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bch/ImportedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bch/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ArchivedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ImportedAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Menu/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Menu/template.js
The form name for the transactions search/filter component was not consistent across the app.
- Bug Fix
- see BTC and BCH web sockets now properly work when updating tx feed
- tx feed form should work
=> fix(Forms): use model so form names dont get out of sync

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Bsv/SendBsv/FirstStep/template.success.js
- Add logic to update BSV send redux form after QR code capture
- Bug Fix
- Scan a BSV or BCH QR code address from BSV send modal
=> fix(BSV): QR code scanning for BSV send

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/modules/rates/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/rates/sagas.spec.js
For BSV we only allow exchangeFrom not exchangeTo, this adds logic to the getAvailablePairs selector and wallet-options, one day we may also want to disable exchangeFrom for w/e reason so added that too
- Upgrades
=> Add exchangeTo and exchangeFrom checks for swap

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/index.js
1. Fixed 'Failed to fetch latest tx' error when switching to eth
2. Fixed swap button becoming enabled when changing amount
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): prevented latest eth tx check error from popping up every time

packages/blockchain-info-components/src/Footer/index.js, packages/blockchain-info-components/src/Navigation/index.js
Navigation/Footer: Update links for markets relaunch,
Data - Markets (links to "/markets") => Data - Prices (links to "/prices")
Products - Principal Strategies (links to "bps.blockchain.com") => Products - Markets (links to "/markets")
- Feature
Open verify header/footer links work
=> feat(header/footer): links rename 

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/PairDeviceStep/template.js, packages/blockchain-wallet-v4-frontend/src/services/LockboxService/apps.js
- latest BTC app requires the user to allow the export of public keys on the actual device.  Since we do this during device setup, we need copy to inform the user that this may be required.
- Increased BTC app transport during the xpub derivation process to account for user needed to allow the export on device.
- decreased the default app uninstall/install timeout to 20 seconds 
- Feature
Device must have BTC app version of 1.3.2
=> Feat(Add BTC 1.3 app support to Lockbox onboard)

packages/blockchain-wallet-v4/src/signer/bch.js
Assigning @salomegeo because I miss you
2140
- Bug Fix
1. swap from lockbox bch
=> fix(BCH): Use script instead of coin.script to construct outputs

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/RecordBackupPhrase/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/RecordBackupPhrase/SecondStep/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/RecordBackupPhrase/ThirdStep/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/template.js
new data-e2e tags for backup funds functionality
- Feature
=> new data-e2e tags for backup funds functionality

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Mobile/MobileLogin/index.js, packages/blockchain-wallet-v4-frontend/src/modals/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js
- Fixes issue where camera would stay on after user logs in via QR code.
Im not entirely sure why this was happening, but it seems that having the `MobileLogin` modal added to the login template as well as added via the `Modals` wrapper in the `WalletLayout` caused the QR code library we are using to never unmount properly thus it would cause camera to stay on and loop inside an error hook.  
I removed the `MobileLogin` modal from being added in the `Modal` components wrapper to avoid the above scenario. 
- Bug Fix
=> Fix(Camera staying on after QR code login)

packages/blockchain-wallet-v4-frontend/src/services/LockboxService/apps.js
- `hash` is not used by Ledger yet.  Sending an empty one can apparently break things at times. Remove hash.
- Bug Fix
=> Fix(Lockbox remove hash from install/uninstall WS urls)

packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Confirmations/index.js
- Fix issue for BTC/BCH showing tx confirmed when there are 0 confirmations. A missing `txBlockHeight` property inherently means 0 confirmations
- Bug Fix
=> Fix(BTC, BCH 0 confirmation logic)

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Error/validationMessages.js
WEB4-2207 removed extra character from swap error message
- Bug Fix
=> fix: remove extra character before swap max error

packages/blockchain-wallet-v4/src/network/api/xlm/index.js, packages/blockchain-wallet-v4/src/redux/payment/xlm/sagas.js
changed setTimeout to fetchTimebounds, which uses the server to get the time, not local time. Should hopefully resolve tx_too_late errors
- Bug Fix
=> fix: used fetchTimebounds instead of setTimeout for xlm txs

packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
- Updates copy and styles the alert red to warn users about not adding a memo when sending XLM to a known exchange address
- Feature
=> Feat(Update XLM memo to exchange style and copy)

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js, packages/blockchain-wallet-v4-frontend/src/services/MigrationService/index.js, packages/blockchain-wallet-v4/src/redux/walletOptions/__mocks__/wallet-options-v4.js, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.js, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.spec.js
@plondon:
> I think for this code what happened was we were preparing for .info .com move, and if v4 was
deployed before the migration we were going to need this redirect.  But we deployed v4 after, so
this code was preliminary and is no longer necessary.
**After this PR lands in production we should inform the backend team that we no longer consume the `enableDomainMigrationRedirects` option.**
Refactor
No test.
=> refactor(migration): Remove unused domain migration code.

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmailToken/index.js
Just adding the param to the deep link directly doesn't seem to work, this creates a longer link but one that should be able to pass on the `context` param.
@bchrisarriola does this seem more like what you need?
- Feature
=> fix(LinkContext): create full deep link with required parameters

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmailToken/index.js
The last PR for this feature wasn't correct, some params are required on the URL itself, while some are embedded inside of the `link` param. Here is what I have for the distinction now:
URL Params:
* `link` (this holds the deep link)
* `isi`
* `ibi`
* `apn`
Deep Link Params (embedded inside `link`):
* `deep_link_path`
* `context`
@bchrisarriola could you verify this all seems correct?
=> fix(LinkContext): Correctly separate link params and deep link params

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmailToken/index.js
Before, the deep link was getting double-URI encoded, because I didn't realize that `URLSearchParams` actually does the encoding for you. This removes the first layer of URI-encoding.
=> fix(LinkContext): Remove double-uri encoding

packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/template.shareLink.js
- Simply changed the qr code in `template.shareLink.js` to render a bip21 encoded message containing address, amount, and label.
1. Fill out a btc request form and click `create sharable link`.
2. Scan the QR code with the mobile app to check that address and amount have been auto-filled.
=>  Fix: BTC Request QR Code Bip21

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js
1. Moved `actions.middleware.webSocket.xlm.startStreams()` to execute before `coreSagas.kvStore.xlm.fetchMetadataXlm` in order to avoid race condition with setting `onMessage` and `onError` attributes of the `HorizonStreamingService`.
2. Added test for `startStreams()`.
1. Open up two wallet sessions in different tabs. 
2. Send xlm from once account to the other.
3. Check to make sure alert popup fires, and balance updates without refreshing.
=> Fix XLM Socket

packages/blockchain-wallet-v4-frontend/src/components/Balances/TopMenu.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WalletBalance/Balance/template.success.js
Fixes issue 113. This undoes https://github.com/blockchain/blockchain-wallet-v4-frontend/commit/0dc7d92d66f1e01349f367d981538f2f59c7068e#diff-1e74d3892617b0624c51881e58bc2c26. 
@jjBlockchain was there a reason LinkContainer was removed? I don't see any issues when adding back it.
=> add linkcontainer back to balance dropdown

package.json, packages/blockchain-wallet-v4-frontend/webpack.config.ci.js, packages/blockchain-wallet-v4-frontend/webpack.config.dev.js, packages/blockchain-wallet-v4-frontend/webpack.debug.js, yarn.lock
Reverts blockchain/blockchain-wallet-v4-frontend#1950
Found issue relating to `build:{env}` commands.  These commands used to exit after build but with this PR the dev server starts and the process never exits.  This is blocking us from running `yarn release` as this command first does a `build:prod`
=> Revert "Debt/terser compile"

packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/CoinSelect/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinIntroduction/template.js
Checkout and dropdown also had PAX instead of USDD + button hover color for empty tx feed. 
=> fix(sb-usdd): coin dropdown and checkout details display name

packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/template.success.js
We removed text label option from text area
- login to wallet 
- click on request
- click on last item in modal `Create Shareable Request Link`
- make sure that description text area do not have wording (optional)
=> chore: removed optional text from text area

packages/blockchain-wallet-v4-frontend/src/scenes/Register/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.tsx
Add flag in the query to allow .com to link directly into the wallet signup homepage with the form opened
=> feat(signup): allow .com to link to wallet form opened

package.json, yarn.lock
We did all on proper way in the first place, `lint-staged` make sure that only staged files are passed around and `jest` `findRelatedTests` make sure that it search for relevant tests, I upgraded version of `lint-staged` and it speed up whole process for 8seconds, we had 46seconds running time before and now it's 38seconds, not that drastically speed but looks like only one doable. 
In any case we do it on right way and jest do not execute all tests, I added one additional parameter `bail` it will stop running if any of relevant tests fail
=> feat: speed up of tests in pre commit hook

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
Next thing to be release id to have ability to send to trading wallets
=> Feat/Send to Trading: reverted back ability to send to non custodial(trading)

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/template.success.tsx
Log in to app and go to USD fiat, click on deposit button and then click on international tab
account number should be visible
=> feat(deposit): show account number no matter of transfer type

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx
https://blockchain.atlassian.net/browse/FWLT-849
Uses coinTicker for swap error messages and in checkout form, so currency will say USD-D instead of PAX.
=> fix(swap): coinTicker in swap error messages

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/index.tsx
Fixes https://blockchain.atlassian.net/browse/FWLT-863.
Originally needed this form clear to make sure there were no duplicate error messages, but this cleared the stored amount value needed to create the swap transaction. This logic has been added to the template.
=> fix(swap): amount form error

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx
For btc/bch outgoing swaps, we display the network fee as the sat/b value rather than what the network fee actually is. BTC/BCH payment has a network fee under payment.selection.fee, while other coins have a static fee in just payment.fee. 
This should be released to production ASAP but https://github.com/blockchain/blockchain-wallet-v4-frontend/commit/f470e9538dbba591a03769716da99f89327b483d should be cherry picked out of development before release since it breaks swap.
=> fix(swap): btc fee amount displayed in preview swap screen

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/index.tsx
https://blockchain.atlassian.net/browse/FWLT-854
Swap:
Rather than show both '0' and 'Free' tag  or network fee if wallet is custodial, only show free tag.
=> fix(swap): remove 0 if no fee, only show fee tag

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx
Undos this [commit](https://github.com/blockchain/blockchain-wallet-v4-frontend/commit/3bb150a0ab7007b63a1182b3fc92c8bfb792bfc6), backend doesn't return fee in ETH. Need to add more conversion, didn't want this to break with next release.
=> fix(swap): fee

packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts
ensure coin entry exists in wallet options before render attempt
=> fix(menu): safe render

packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
Only notify backend of pending deposit if send is from non-custodial to custodial.  This is causing users to see fake pending transactions in their feed when they sent to non-custodial.
=> Hotfix(BTC):  Fix non-custodial to non-custodial send / transaction list

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.utils.ts
Backend service expects BCH addresses to be in cashAddr format
=> fix(interest): bch withdrawals must be in cashAddr format

packages/blockchain-wallet-v4/src/redux/data/fiat/sagas.ts
Fixing edge case where user had less than the page size of transactions and entered, exited and then reentered a fiat transaction list, and we never refetched their transactions properly and thus nothing would show.
See above
=> fix(fiat): ensure we always refetch transactions when reset is true

packages/blockchain-wallet-v4/src/exchange/index.ts
WDGLD displays should use 8 decimal places rather than 2. Adjusted max/min digits and am opening against SDD branch so it can be tested via automation. 
=> fix(wdgld): show 8 decimals rather than 2

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx
Maximum sell amount validation in the checkout form was not accounting for network fees. This checks if a payment is created (will only happen from non-custodial accounts) and uses that effective balance as a max rather than account's full balance.
=> fix(sell): use payment to calculate max avail

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/selectors.ts
Added `paymentR` to get limits for sell with fees, but this broke buy because payment never loads. Changed it to 'getOrElse undefined' which allows everything to load, there just is a slight delay in getting limits when on the sell checkout screen, i.e. the UI updates in real time once the right limits load.
=> fix(buy): payment getOrElse undefined so it doesn't load forever

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.sdd.success.tsx
If a user quits out of the process when attempting to verify the 3ds, the payment will go into pending state in BO, and will show that the payment was successful in the wallet. After that the user is unable to start a new payment until the pending one fails/expires.
Expected Behavior:
The payment should display a correct status or let the user cancel it manually.
=> feat(sdd-flow): implemented new open payment screen

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx
Fixes check to block user from creating a Swap order if there is not enough ETH in their wallet for an ERC20 send. 
=> fix(swap-eth): change to check if not sufficient eth

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
If bank linke update endpoint fails the app should show the user a default error screen instead of throw
Link a bank and make the api endpoint to `/update` return a 500 error. User will be shown a default try again error screen. To replicate this I put `throw new Error('any text')` on line 541 of `data/components/simplebuy/sagas.ts`
=> fix(bank linking): show user default error screen when bank link fails

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4/src/network/api/custodial/index.ts, packages/blockchain-wallet-v4/src/network/api/simpleBuy/index.ts, packages/blockchain-wallet-v4/src/network/api/simpleBuy/types.ts
- Fix to ensure non-gold users are shown payment methods for Buy/Sell instead of the currency unsupported screen
- Removes duplicate entries of same APIs.  The two removed where not used in the codebase
=> fix(payment methods): use new payment method eligibity endpoint

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
This PR prevents caching of swap initial value, after success swap we now do clear previously entered amount
=> feat(swap): prevent caching of old swap amount after success swap

packages/blockchain-info-components/src/Colors/DarkMode.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx
- Show correct bank account information on transaction list instead of "Bank Account"
- By default select last bank account used for Buy
- Fix Dark mode grey900 text
=> fix(ACH): Payment methods defaults and order history

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx
Fixes issue with swap where an XLM payment is created by clicking 'Swap Min', but the XLM balance < min. This causes formChange saga to stop and not resolve, breaking most of the app.
Also added styling to card settings, to truncate card label so rows don't shift. 
=> fix(swap): resolve saga if xlm payment error and card settings styling

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/AddCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/services/ImagesService/index.ts
When a user first signs up and proceeds to go through the simple buy flow, we get the payment methods eligibility from the api _before_ the user has entered any address/kyc info. So it shows them as ineligible unless they hard refresh and log in again. This change makes the payments method fetch each time the CC form is loaded so we always have the latest eligibility. 
1. Sign up for a new wallet (DO NOT HARD REFRESH)
2. Go through simple buy flow
3. CC form should no longer show the `Card type not supported` input error when you put in a CC#
=> fix(simple buy): fixes error on first-time user credit card form validation

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts
This filters the default card payment method by 'ACTIVE' state. Currently if you remove a CC and it was the last used card, it will still be set as the default payment method.
- add a card or use an existing one
- make a simple buy with it
- remove that card
- open simple buy form
=> fix(simple buy): filter out non-active cards from sb default payment

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts
Fixes issue where ERC20 fees weren't include in the ETH transaction history csv. The !tx.erc20 check isn't needed, since erc20 transactions are not included in the rawTxList returned from eth transaction endpoint.  
=> fix(export-history): include erc20 feed in eth transaction history

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx
There's a click event on all cards in general settings that just opens the simple buy flyout. This should not be there.
Add CC to an account or use existing CC account, go to General settings, click on the save CC (not the remove button) and it should now do nothing.
=> fix(credit cards): remove click event from cards in general settings

packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.ts, packages/blockchain-wallet-v4/src/network/api/custodial/index.ts
Due to recent changes on API side we have to pass along fiatCurrency in check call
To test this log in to wallet and go ove simple buy flow, make sure that there is no errors show once when user do select crypto currency
=> feat(simplebuy): fixed check withdrawal lock to pass over fiat currency

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/model.tsx
Fixed 985, where swap/buy/sell transactions displayed PAX in the feed rather than usd-d. 
=> fix(tx-feed): pax to usd digital display

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx
Disable swap if user's wallet balance < swap minimum. Was originally comparing wallet balance in minor units to minimum swap (major units), so the check was always returning false. This change fixes the check to use the correctly converted wallet balance. 
=> fix(swap): disable swap if avail balance is less than min swap

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx
Matches design for linked cards displayed in Settings. We originally had exp date and limits in the card, but I've removed to match design, which just has 'Card Ending in {cardNumber}' as the detail.
=> fix(settings): update card style to match designs

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts
If you have fiat funds, and buy crypto with 100% of your fiat wallet, the next time you try to buy crypto, it defaults to previous fiat wallet, but says I don't have enough funds, but you can't change the payment method because there's a form error.
Add fiat funds to your account, buy crypto with 100% of those funds. Try to buy more crypto again.
=> fix(simple buy): fixes issue where funds default payment method has no available funds

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/model.tsx
Fixes FWLT-1030, uses abbreviated wallet name in tx feed for swaps, to match what we display in wallet selection for swap.  
=> fix(tx-feed): use coinTicker instead of displayName for swaps in tx feed

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx
Currently users that are not eligible for ACH can still see the "add a bank" button in general settings. They should not be able to.
Create a new user with a NYC address so that they're not eligible, and go to `/settings/general` you should not see an "add a bank" button anymore.
=> fix(bank accounts): check for bank_transfer payment method before displaying add bank button on settings page

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
Original Issue: If /trades returned an error for sell, the flow would return to Checkout Screen but form would stay in loading state and error message would never show.
Caused by a start submit for the simpleBuyCheckout form on line 391 that was never stopped. Removed the 'return' from line 397 so that saga would go onto 401 and stop the submit.
=> fix(sell): sell for should also stop submit

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
This PR fix a multiple calls to /nabu-gateway/sdd/verified in case that user is already verified we do not need to again call BE anymore since user can't lost verification
- create a fresh wallet
- go over SDD
- after you enter dob/address make sure that in network tab we do not call more calls to /nabu-gateway/sdd/verified after BE return that user is verified
=> fix(sdd): once when we know that user is verified we set this flag in state

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
with this PR we show min buy for SDD users once when user start entering smaller amount than it's limited.
Login to wallet with SDD wallet, tier3 go to simple buy flow chose BTC and enter small amount like $1 button with min should be visible
=> feat(sdd): show minimum buy when user type lower amount

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
We do prevent calling BE endpoint if user is not ye created
Create a new wallet and then validate email and click on crypto and once when enter amount page is rendered we do call API endpoint /sdd/verified
=> feat(sdd): prevent verif call if user is not yet created

packages/blockchain-wallet-v4-frontend/src/components/Send/ExchangePromo/index.tsx
Fixes issue with send blowing up when first opening the modal, similar to the fix in segwit branch.
I'm not sure why LinkContainer was causing the issue, but it seems like using a different component visually looks the same and as far as I can tell, functions the same as well.
=> fix(send): :switch linkcontiner to connect container in exchange promo

.prettierrc
This is just a rule to make `vscode` and other text editors to comply with `prettier`. It seems that they've created a new rule for `jsx`, and now you have to explicitly add `jsxSingleQuote` as `true`, in order to get single quotes on `tsx` or `jsx`.
=> Fixing `.prettierrc` config

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.tsx
1. Shows original footer (login via mobile and need help?) on the login page if mobile auth feature is off
2. Adds back in the wallet ID reminder copy currently in production.
=> fix(mobile-auth): add old login via mobile if feature flag is off

packages/blockchain-wallet-v4/src/signer/btc.js
Set redeemScript to null in tx.sign for native P2WPKH send. Fixes issue where pushtx wasn't being called for native segwit sends. 
=> fix(send): redeemScript to null on tx.sign for segwit send

packages/blockchain-wallet-v4-frontend/src/data/components/utils/sagas.ts
Fixes 1070, issue where creating a swap order wasn't working correctly.
Not sure why `const defaultDerivation = yield select(selectors.core.common.btc.getAccountDefaultDerivation(address, appState))` wasn't working, but that returned undefined. If I removed the `yield select`, the value was correctly resolved. 
=> fix(swap): selectReceiveAddress function fix

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
This PR close simple buy modal once when user clicks on show interest.
Go ove tier 2 wallet, buy some crypto, on last page interest banner will be visible, click on earn now, close interest modal, make sure that Simple Buy modal is not visible anymore
=> feat(interest): close previous modal, once when starting interest modal

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx
What was happening is that one div was overlapping the other, because of the defined height. As the background of the overlapping div was transparent, we were able to see through it, but not click on the link. I had the option to change the `z-index`, but I preferred to just remove the height (unnecessary and probably just copied and pasted), to make it work.
=> fix(withdraw): removing height so the link can be clickable

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/validation.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/selectors.ts
Adds standard min/max validations to the amount input and disallows "non-amounty™️" kinds of input values. 
Go to US dollars wallet, click deposit, try and enter sub $1 and more than $30,000 and also try entering letters and other non-numerical characters.
=> fix(ach deposits): add form min/max/format validation

packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/btc/utils.ts
1. BCH sends to external addresses were generating a bech32 change address. This was fixed by importing the `fromAccount` util function from bch/utils rather than btc/utils, which correctly assumes default derivation as legacy.
2. BCH transfers from wallet to wallet were assuming the 'to' wallet should use bech32 as derivation. Added checks to `toOutputAccount` function which passes 'legacy' argument if coin is bch. 
=> fix(bch-send): use legacy derivations for from and to bch send

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/index.tsx
This PR load proper fiat currency for deposit/withdrawal click
- login with wallet which have USD account, try to use deposit/withdrawal they should work as before, the only difference is that we now load fiat currency it from store it's not hardcoded anymore
=> feat(ach): load fiatCurrency based on page where user did clicked

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx
Withdrawal enter amount screen needs to be disabled if there is no wire account and no ach accout.
try to withdraw with only a ach account and no wire accounts on your user account, you should still see the "Next" button as enabled.
=> fix(ach withdrawals): form should check for existence of both beneficiary and ach bank

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/model.tsx
Increase height of wallet balance dropdown to accommodate all coins. 
=> fix(balance-dropdown): increase height to show all coins

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
This fixes the issue where wallet creating would hang after submitting the form. We were trying to show the upgrade modal, now it will only show if it's not the user's first login. 
=> fix(register): dont show upgrade prompt at wallet creation

packages/blockchain-wallet-v4-frontend/src/modals/Btc/AddBtcWallet/template.js
This PR solve issue with non working click on X button
Go to settings, then select 'Wallets & Addresses' and then click on button 'New Wallet', modal will appear click on X button and make sure that it's closing modal.
=> fix(new-wallet): fixed close button behaviour

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Authorize/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/SelectBank/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/BankDetails/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/LinkedPaymentAccounts/Accounts/Bank/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/LinkedPaymentAccounts/Accounts/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Methods/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/model.tsx
Fixes issues @milan-bc had in original open banking PR and fixes an issue with deposit button defaulting to USD add bank modal instead of using the user's fiat currency to determine yodlee or yapily.
=> fix(open banking): several small fixes to imports and formatted messages, as well as open the proper add bank modal using the users fiatCurrency

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
Fixes this error when selecting custodial USDT/PAX from interest dropdown on the transfer screen.
=> fix(erc20-interest): fix contract address error for custodial transfers

package.json, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
Currently users are experiencing an issue on the initial deposit attempt to interest account. This is happening because we were not waiting for call to Nabu for deposit address to finish before we attempted to build the deposit transaction.
=> Hotfix(Interest): wait for deposit address before building tx

packages/blockchain-wallet-v4/src/coinSelection/coinSelection.spec.js, packages/blockchain-wallet-v4/src/coinSelection/index.js
Follow-up for #3011
Fixes edge case when `transactionBytes` multiplied by `feePerByte` contains fractional value, which is not accepted by `bitcoinjs`
```
$ npm run test:core -g "Coin*"
```
=> fix(segwit): Fix edge case with fractional vbytes

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
Checks if lastPendingOrder came from YAPILY. If yes, show the Open Banking Connect modal when viewing pending order details. 
=> fix(open-banking): show correct flyout for pending orders

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/model.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx
Yapily logic was causing Yodlee simple buy confirmations to hang. Just needed to do a specific check for Yapily partner before running the auth url polling method.
Log into an ACH capable account and do a simple buy, it should complete successfully as it does on production.
=> fix(simple buy): fix issue where order confirmwasnt showing on yodlee orders due to yapily

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYodlee/Add/index.tsx
This PR solves the issue with back button click
Login to wallet
Navigate to SB
Select any crypto and any sum
Select payment methods
Press 'Link a Bank'
Attempt to press 'Back' arrow, nothing happens
=> feat(open banking): link bank modal back button click now works

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx
When doing a simple buy with open banking we need to have a loading screen between the order confirmation/authorization step and the QRCode step due to Yapily api taking a long time. 
Login into an open banking enabled account and do a simple buy order. After clicking the Authorize button you should see a loading screen for around 1 minute :( and then you should be dropped into the qr code screen.
=> fix(open banking): add a loading step between approve and the qrcode screen and change order confirm button to next for yapily orders

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/Authorize/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
Handle order failed screen
Using an open banking enabled account, do a simple buy but when you go to the modelo bank website to auth the debit from the account, click cancel. When you come back to the wallet after the api updates it should take you to an order rejected screen.
=> feat(open banking): show failed order screen when user declines access on their bank site

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx
This PR resolve inconsistency with default limits if method is not selected
Try to buy some DOT
Before we had default limit set to $5
=> feat(ob): improved default minimum

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts
There is a pagination bug on backend ingestion service that can result in transactions being missed. By raising the page sizes for both transaction list and reports, the odds of this bug occurring is drastically reduced.
=> Fix(ETH): Transaction fetching

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OpenBankingConnect/index.tsx
This PR improve loading of order details
create OB order close it after bank is linked, you will see banner that there is pending order, click on it and then QR screen will be stuck to infinite load since there are no order attribute details
=> feat(ob): prevent infinite loading of QR code since order attributes are missing after repen of SB flow

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/BankDetails/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/RemoveBank/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/model.tsx
This PR resolve issue with possible render of null
Use wallet with EU based and for example connect Commerz bank then try to remove it you should not see null in name
=> feat(ob): prevent rendeering of null for account number and bank name

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/CryptoItem/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/utils/helpers.js
Simple buy icon should look like this: ![image](https://user-images.githubusercontent.com/57680122/116621776-9039e080-a8f8-11eb-8e0c-7f9653268e18.png)
I also added a `hexToRbg()` util function that can be helpful for future devs
Open Simple buy for any coin, look in top right corner of modal.
=> fix(simple buy): coin icon doesnt match designs

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/selectors.ts
Fixes issue where ETH fees were being displayed as 0 in interest.
I know it's a btc check, but i'm replacing the erc20 coin check with this one, so it's a net zero. 
=> fix(interest): eth fee

packages/blockchain-wallet-v4/src/redux/payment/btc/utils.ts
// When moving from one chain to another i.e legacy to segwit we must send to the receive chain so that backend services will search for funds on the change chain. Without funds received to a receive chain, the backend will not lookup change.
=> fix(btc): add transfer address for new chains

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxEthAddresses/selectors.ts, packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxXlmAddresses/selectors.ts
Interest accounts were missing from dropdowns for XLM and ERC20's.  Fixed that issue and also named a few variables better.
=> fix(accounts): show interest accounts in tx list account dropdown

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
Mobile authorization fix:
Clears channelPhonePubkey from cache so user sees QR code when visiting login page.  
=> fix(mobile-auth): clear phoneKey on logout

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedWireBanks/index.tsx
Fixed issue with passing along proper currency instead of remote object
Go to preferences change wallet currency, go back to general settings
=> feat(settings): fixed issue with switching wallet currency

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/model.tsx
This PR implements new checkout screen for ACH and open banking
Try Buy flow and buy some crypto, checkout screen should looks like
=> feat(brokerage): implemented new buy checkout screen for ACH/OB flows

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/BankPicker/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/selectors.ts
Need to check for USD bank_transfers payment methods and not filter them out when checking the open banking invites list.
=> fix(withdrawals): check for usd when filtering out payment methods for the openbanking invite list

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/index.tsx
Fiat deposit -> add bank screen wasn't showing up because of the fiatcurrency prop. Set a getOrElse default to USD to solve the issue for USD, EUR, and GBP.
=> fix(deposits): default to USD when adding a new bank from deposit

packages/blockchain-wallet-v4/src/network/api/kvStore/index.js, packages/blockchain-wallet-v4/src/types/KVStoreEntry.js, packages/blockchain-wallet-v4/src/types/KVStoreEntry.spec.ts, yarn.lock
Metadata fetch fails because of an incorrectly derived private key used for decrypting the payload.
=> fix(metadata): check the correct and incorrect encryption key

packages/blockchain-info-components/src/Colors/DarkMode.ts
Error messages in darkMode are nearly unreadable.   Lightened color to increase contrast against dark background.
Replaced .error color in DarkMode to increase contrast against dark background.  Existing color definition was nearly unreadable.
=> Replace .error color with readable color

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/OpenBankingConnect/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OpenBankingConnect/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx
The "Link via mobile" and "Link via desktop" text is no longer hardcoded in the reusable component. For the PIS flow it now shows as "Confirm via mobile" "Confirm via desktop"
=> fix(open banking): makes action text for qrcode screen a child so it can be changed more easily

packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.tsx
changes layout for standard laptops from looking like:
To:
=> fix(layout): set layout chart breakpoint to 1023px width to accomodate regular laptops

packages/blockchain-wallet-v4-frontend/src/components/Form/CoinBalanceDropdown/selectors.ts
AAVE and YFI custodial accounts weren't showing up when trying to use them with interest. Since they're erc20 coins we can simply add the `getXlmAddressData()` to the interest dropdown selectors
Get AAVE and YFI and ETH and add it to your interest
=> fix(interest): enable interest deposits for aave and yfi

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/BankPicker/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx
This adds an extra level of checking for an edge case where users can select a USD bank account to withdraw EUR or GBP to. When a user is withdrawing they should only be able to select a bank that goes with the fiat wallet they're withdrawing from. This change filters the list of banks by that fiatCurrency. 
=> fix(withdrawals): filters bank accounts and beneficiaries based on the users fiatCurrency when using the withdrawal flyout

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
- Transition from amount screen to the checkout screen - The back button changes size, it should stay the same size. 
Fiat Wallet Checkout
- Kill the purchase line item.
- Kill the fee line item. 
Bank Checkouts
- Kill the purchase line item. 
- Kill the fee line item. 
=> fix(simple buy): design changes to confirm screen

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
Hide button after success withdrawal
Go to interest page and transfer/withdrawal more than $500K
=> feat(edd interest): do not show button after withdrawal success

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
Interest deposit form throws an error if user
1) has a private key account with 0 balance selected as their deposit account
2) and then enters an amount into the field
Fix: If selected account has 0 balance, skip payment.build(). This will prevent form from breaking. 
=> fix(interest): skip payment dot build if account has 0 balance

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankStatus/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx
There are two similar but unrelated issues. 
1. When clicking "Add a bank" from the general settings, the modal has an infinite loading screen.
2. When you link a bank through settings/simple buy/deposit the loading spinner spins infinitely and never transitions to the "Successfully linked bank" screen
Try to link a bank from general settings, and also link a bank from simple buy and it should get all the way to the success screen.
=> fix(brokerage): fixes infinite spinner in general settings add bank button click and infinite spinner when successfully linking a bank

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankStatus/template.error.general.tsx
Close modal X button wasn't working on bank linking error modal because it wasn't calling the close modal function properly
=> fix(open banking): close modal x button wasnt working

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/IntroCard/index.tsx
Interest account should not show up info box for EDD after it's passed from BO
Create one wallet with interest, mark it as EDD needed, and then open interest page, after that box should be visible; go to BO mark EDD of interest as passed and check wallet again
=> feat(edd): show required info box only if user eddNeeded is true, in case of passed do not show it

packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterPassword/index.tsx
Fixes logic to show 2fa field label in both authType case 4 and 5 (google auth and sms)
=> fix(2fa): show field label for google auth 2fa

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/SecondStep/index.js
Fixes issue where we show an error if valid recovery phrase isn't associated with a known wallet ID. We should still allow user to proceed with recovery into a new wallet. 
=> fix(recovery): allow recovery for valid phrase without metadata

packages/blockchain-wallet-v4-frontend/src/components/Form/CoinAccountListOption/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/index.tsx
This tiny PR solve CSS issue
Login with wallet which contains swap account with huge amount of money make sure that circle looks as expected
=> feat(swap): fixed issue with circle size when text is too wide

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
If you are on the summary page of swap and return to the `swapAmount` form, we will rerun initAmountForm with a  provisionalPayment with value = `0`. This fixes that problem. This problem is live in prod as well.
=> fix(swap): amount form

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/model.tsx
There is `undefined undefined` under "Credit Card" for silver tier users using simple buy. This ticket removes this.
- Get a silver tier account
- Open simple buy, enter an amount, click Next
- Credit Card should not have any text under it.
=> Fix/fwlt 1509/cc undefined text

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx
Issue with min buy showing up as $685.00 instead of $6.85 because the value isn't being converted from base amount to standard amount.
=> fix(simple buy): convert all min amounts from standard to base before displaying in the UI

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts
Fix for erc20 balance selector. Fixes bug where erc20 non-custodial balances was not included in total balance. 
=> fix(erc20-selector): change symbol to tokenSymbol

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
Handles edge case for kyc reset upon mnemonic recovery where a user is Tier 2, with kycState = NONE + resubmission reason. We should allow them to resubmit their docs again.
=> fix(kyc-reset): edge case when user is tier 2 but kycstate is none

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
Kyc reset hotfix, accounts for users that are still tier two but still have a resubmission tag.
=> fix(kyc): hotfix for kyc reset

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
After mnemonic recovery and kyc reset, user has to re-verify their information. If there was a country mismatch on the address step, /address would return an error and app would blow up. We are passing `_error` a string now as it expects, and error message now displays correctly on form. 
=> fix(address-resubmit): display error if country mismatch

packages/blockchain-wallet-v4-frontend/src/components/Flyout/FrequencyScreen.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Header.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/index.tsx
When clicking the ok button after a Buy, there's some logic to check if the recurring buy flow should pop up or not. This needed to check for an existing sb quote in order to show up or not.
=> fix(recurring buy): check for quote before opening first time RB flyout, and other small bug fixes

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Box/SavedRecurringBuy.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuy/GettingStarted.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuy/GettingStarted.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuyDetails.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/index.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/GetStarted/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Notifications/AnimatedCarousel/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Notifications/AnimatedGraph/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Notifications/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx
=> fix(recurring buy): fixes several small design issues related to recurring buy

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinChart/template.tsx
The charts were doing some math to set the width of the chart, but some of the first renders were rendering a negative number which is not allowed for svg element. I just used `Math.abs()` to make sure it's always a positive number.
=> fix(charts): svg width param cannot be negative

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/index.tsx
When clicking the 'Ok' button on the buy order confirmation screen you should be taken to the first time recurring buy flow only if it's the accounts first purchase on the app and if they didn't already select a recurring buy option on the enter amount screen.
=> fix(recurring buy): only show the first time buyer flow if its truly the users first purchase

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/CloudRecovery/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryOptions/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryPhrase/FirstStep/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/StepOne/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/StepTwo/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/index.tsx
Uses magic link data from state for email header, rather than cache which can be unreliable sometimes. 
=> fix(email-header): get email from magic link not cache

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actionTypes.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
Logging in, opening up simple buy with only a default payment method,  selecting a recurring buy period (ex. Weekly) then submitting the form would correctly submit the recurring buy, but on the checkout confirm page, the UI would say it's only a One Time purchase.
=> fix(recurring buy): fixes issue where recurring buy period was getting reset to ONE_TIME in the UI

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
Fixes issue where we're logging a JSON error to the console for missing `message.msg` -> only exists after using secure channel login for mobile app login.
=> fix(json-error): only parse message if it contains a msg

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/actions.column.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/selectors.ts
https://blockchain.atlassian.net/browse/FWN-969
Only select token will have buy and sell depending on `CustodialWalletBalance` is in `window.coins.ETH.coinfig.products`
It works using account provided by Phil: 
bbdca2df-XXXX
=> fix(prices-buy-sell): only show buy and sell on select tokens

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PreviewSell/index.tsx
Buy/Sell Crypto → Sell → go all the way to checkout screen and make sure it says `Sell Now` or `Buy Now`
####Screenshots
=> fix(sb): correct button copy

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
This PR fix issue with download transaction history
You need a wallet with interest rewards(transactions), go to rewards page and check transaction list, try to download it you should be able to see generated link
=> fix(interest): fixed issue with download transaction history since we did pass array as object which is not ok

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/EnterAmount.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/validation.tsx, packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx
This PR fix the issue with missing deposit error message
Any account deposit flow try to enter greater than maximum error message should be visible
=> feat(seamless limits): improved error message when amount is over max for deposit flow

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/UpgradeToGold.tsx, packages/blockchain-wallet-v4-frontend/src/components/Form/FiatConverter/Converter/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
Fixed copy and added error message on proper location
login with silver+, go to send flow try to send BTC from C->NC and enter more than $2K, should be able to see error like
=> feat(seamless limits): improved old send flow error message and banner copy

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/types.ts
Stops polling for magic link data after login is successful. Previously, we'd only stop polling once magic link data was returned from the endpoint, but if a user triggers an email but logs in with guid, we still poll and user would see an expiration message which is confusing. 
=> fix(login): stop magic link data polling after logging in

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx
Use selected trading currency instead of wallet currency during buy/sell flow
=> feat(trading limits): use proper currency on enter amount screen

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/TransactionList/index.tsx
If a user cancels a buy within the 3ds flow. hide the failed order to prevent confusion
try to buy crypto with a card -> cancel within the 3ds flow -> check that the order is not listed in the transaction list
=> fix(FWN-758): remove failed 3ds orders

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/SellState/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/SellState/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/selectors.ts
move the getaccount flyout logic away from the initial load and into the sell side
=> refactor(flyout): move account logic into a sell flyout

packages/blockchain-wallet-v4-frontend/src/scenes/Signup/SignupLanding/index.tsx
* add institutional sign up link to bottom of exchange sign up card on sign up flow.
* navigate to /signup (look below the exchange sign up card)
* click create wallet
* should show wallet sign up form and exchange sign up card with institutional sign up below exchange sign up card
=> feat(institutional-signup): add insitutional link

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/template.unsupported.tsx
Show unsupported modal in case that user is not eligible for adding a payment method
=> feat(add payment): show unsupported method in case that user is not aligible to add payment method

packages/blockchain-wallet-v4/src/redux/wallet/sagas.ts
In addition to the fix implemented in #3966, we would like to also apply replenishDerivations fix whenever derivations array size is not 2.
This resolved an bug where there is only one derivation in the derivations array.
=> fix(derivations): apply replenishDerivations fix whenever derivations array size is not 2.

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/selectors.ts
Prevent fresh new users to see add new card screen in case that they are still not eligible
- Create a new wallet
- go over to settings > general
- click on add card
- should not be able to add new card since new user is not eligible yet for that action
=> feat(buyer hand hold): only in case that user is eligible to do payment method allow them to add new card

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PreviewSell/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/ThreeDSHandlerCheckoutDotCom/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx, packages/blockchain-wallet-v4-frontend/src/providers/ModalEnhancer/index.tsx
Removed Cancel Button From:
- Cash Wallet Buys, Sells and Swaps
- Card Buys
- Open Banking Buys
- ACH Buys
=> Feat/fwn 690/tb remove buysell cancel button

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts, packages/blockchain-wallet-v4-frontend/src/layouts/Public/components/Footer/index.tsx
1) Fixes issue where `finally` of the triggerWalletMagicLink function would never run, because `yield call(pollForSessionFromAuthPayload, api, sessionToken)` doesn't resolve until device is verified or after 50 attempts. This would cause login form to remain in loading state when it shouldn't. 
2) 'Need Help' link in Exchange login form could sometimes cause the app to blow up because form values could be undefined. 
=> fix(institutional-portal): need help link and stop form submit

packages/blockchain-wallet-v4/src/network/api/nfts/types.ts, packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts
Converting to full string since BigNumber forces scientific notation, but opensea doesn't want
(ex. auto converts to 1e27 when we actually want '1000000000000000000000000000')
basePrice: BigNumber | string
extra: BigNumber | string
=> fix(nfts): allow for big eth amounts

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelOffer/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/fees.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/ShowAsset/ActiveOffers/cta.tsx, packages/blockchain-wallet-v4-frontend/src/store/index.js, packages/blockchain-wallet-v4/src/network/api/nfts/index.ts, packages/blockchain-wallet-v4/src/network/api/nfts/types.ts, packages/blockchain-wallet-v4/src/redux/payment/nfts/index.ts, packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts
Allow offers to be made in any of asset's payment_token_contracts
Breaks:
~1. need to figure out why offers reverse maker/taker relayer fees, look at opensea-js @jmichel-bc, this was the issue that we fixed before then reverted because of _accepting_ offers, now there is an issue w/ _making_ offers.~
~2. frontend can no longer find orders on offers_made from user address~
=> feat(offers): move away from hardcoded weth

packages/blockchain-wallet-v4-frontend/src/data/auth/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/slice.ts, packages/blockchain-wallet-v4-frontend/src/data/cache/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/cache/slice.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterEmail/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterPassword/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterEmailOrGuid/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPassword/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx
1. Saves exchange login data in cache, so user doesn't have to go through device verification every time
2. Moves the tab clicking functions into the main login index file
=> feat(exchange-login): cache exchange data

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/OrderSummary.stories.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/index.tsx
The OrderSummary component was rendering a duplicated currency sign
because the parent component was already adding the currency sign to
the label
* create a recurring buy in staging
* in the order summary should display the currency sign duplicated
=> fix(OrderSummary): remove extra currency sign in recurrent buy

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/BankList/template.success.tsx
This removes the min Withdrawal from the bank account
item in the beneficiaries list page
* Go to Deposit page
* Open the list of beneficiaries
* Then verify that any bank option will not show the "Min Withdrawal" chip
=> fix(BankList): remove min Withdrawal on bank account

packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx
The coin selection page was using only the account name to check
if it is the select account, but that is a problem when multiple
accounts have the same name. This improves the selection check by
doing a deep comparison on the account to check for the selected
account
https://user-images.githubusercontent.com/99212903/154145161-05daa4c5-65fb-4f1a-870a-2a4e4115144f.mov
=> fix(Swap/CoinSelection): display the correct selected account

.storybook/main.js, packages/blockchain-wallet-v4-frontend/src/components/Flex/Flex.spec.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flex/Flex.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flex/Flex.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flex/index.ts, packages/blockchain-wallet-v4-frontend/src/components/Flex/types.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/CoinPage.stories.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/CoinPage.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/CoinHeader/CoinHeader.stories.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/CoinHeader/CoinHeader.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/CoinHeader/index.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/CoinHeader/types.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/PageScaffold/PageScaffold.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/PageScaffold/index.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/PageScaffold/styles.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/PageScaffold/types.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/index.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/index.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/types.ts
This PR adds the coin page component and the inner layout of the page
with the page header displaying the coin name, code, logo and description
=> add coin page scaffold

packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/HoldingsCard/HoldingsCard.spec.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/HoldingsCard/HoldingsCard.stories.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/HoldingsCard/HoldingsCard.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/HoldingsCard/index.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/HoldingsCard/types.ts
This adds the visual component for
coin view to use
Story at: http://localhost:6006/?path=/story/pages-coinpage-holdingscard--bitcoin
=> feat(CoinView): add holdings card

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/TransactionsLeft.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/TransactionsLeft.tsx
=> feat(silver revamp): transactions left banner

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/selectors.ts
This PR creates the ability to use the tag `INTERNAL_TESTER` from the user to allow it to see features or not.
In this case, I need it to enable `Apple Pay` only for certain users on prod (because it's the only place where it can be tested ATM)
=> feat(applepay): adding internal tester as check for apple pay

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/template.js
Prevent the address from being clipped
Open the send modal and checked that a BCH/btc address isnt clipped
=> feat(FWN-1134): make modals bigger to prevent address from being cutoff

.storybook/preview.tsx, .storybook/utils/addIconsToWindow.ts, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/OrderSummary.tsx
This changes the footer height how the icons are positioned in the
the order summary, so all elements are aligned
Before:
After:
=> fix(Brokerage): position icons and button correct in order summary

packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/ChartBalancePanel/ChartBalancePanel.stories.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/ChartBalancePanel/ChartBalancePanel.test.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/ChartBalancePanel/ChartBalancePanel.tsx, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/ChartBalancePanel/index.ts, packages/blockchain-wallet-v4-frontend/src/pages/CoinPage/components/ChartBalancePanel/types.ts
Adds the chart balance panel to the coin view
list of components
=> feat(CoinView): add chart balance panel

.github/workflows/deploy-storybook.yml
Commented non-working command for deploy-storybook to prevent build failure
=> fix: remove nonworking command from deploy storybook

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts
Should prevent issue where `authorize-verify-device` payload is null.
If user is trying to log into the exchange, bypass the session ID check after polling returns account data. 
FWN-1335
=> fix(session-id): bypasses session id check if exchange and polling

packages/blockchain-wallet-v4-frontend/webpackBuilder.js
- reduces app bundle size (~300b gzipped) by excluding non-english wordlist json files
=> refactor(builds): remove non-english bip39 files from bundle

legacy-pages/import-wallet.html, legacy-pages/js/import/wallet-import.js
Added the new captcha script and keys to the html and then use the client to get the validation in order to submit the wallet recovery.
One should be able to navigate into [the wallet recovery legacy page](https://login.blockchain.com/wallet/import-wallet) add the proper `json` file and set the new password.
=> FWN-1261 add captcha support for legacy wallet import

packages/blockchain-wallet-v4-frontend/src/modals/Settings/RecoveryPhrase/ShowRecoveryWords/template.tsx
Adding `className='notranslate'` attribute to the parent wrappers to avoid google translate services to translate the wallet's "magic words" (or "seed words"). Better description inside [the ticket](https://blockchain.atlassian.net/browse/FWN-1375).
=> FWN-1375 - fix: adding 'notranslate' class to avoid seed words being translated

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/EnterAmount.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
Change CTA buttons: Buy Now/ Withdraw Now
=> fix(FWN-1331): remove next buttons and replace with appropriate cta

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/EnterAmount.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/validation.tsx, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/model.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx
Adding behavior to the warning buttons in the Buy, Sell, Swap, Deposit and Withdraw flows. If the user sees the minimum/maximum warning on the CTA button, they should be able to click on it and the amount will be populated in the amount field.
=> feat(wallet): adding behavior to checkout warning buttons

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
Explicitly caches exchange email when user opens 'verify your device' email link.
=> fix(cache): set exchange email on device verification

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
* Open Buy flyout
* select some value in the payment method currency
* Click preview
* the fee should be formatted with the payment method currency format
* go back
* change payment method to coin
* click preview
* The fee format should not have changed
=> fix(BuySell): format order fee using the input currency

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/template.tsx
The Buy button in the Price Chart component of the home page should go directly to the amount screen instead of the crypto selection screen in the modal.
=> feat(price chart): improvements on buy button in price chart component

.well-known/assetlinks.json
The signatures were wrong.  Needed to get them from the actual signing keystores we use.
=> EXAND-731 update links to have proper sha signatures

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx
The Buy button in the Transaction screen should go directly to the amount screen instead of the crypto selection screen in the modal.
=> feat(transactions): buy button improvement

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
Put 'resubmission' banner ahead of 'complete your profile.' This is because if a user recover their account, they will have both a resubmission flag in `/users` and have a kyc state of none. If 'Complete Your Profile' is before 'Resubmission', they will see the incorrect banner and could be confusing. 
=> fix(resubmit): re-order switch case to prioritize resubmission banner

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/OrderSummary.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/index.tsx
This removes an empty box that shows up above the OK button in the Order Summary flyout
Fixes: https://blockchain.atlassian.net/browse/FWN-1225
=> fix(OrderSummary): remove ghost element above OK button

.well-known/apple-app-site-association
Exclude /exchange/alpha* paths for prod
Also cleaned up what looked to be a bad merge.
=> EXIOS-1064 update association files to include alpha paths

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
1. Enter the wallet.
2. Navigate to Rewards.
3. Search for DESO or PAX coins and hit “Earn Rewards”.
4. Click “Add DESO”.
5. Change the type of the unit (to DESO) under “Enter transfer amount”.
=> fix: switching coin per displaySymbol to show pax and deso properly

.well-known/assetlinks.json
We had to rotate our signing keys.  This enables deeplinks for the new keys.
=> EXAND-731 update asset links due to new signing keys

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/selectors.ts
We're currently doing a check for `canDepositFiat === true` when displaying the list of crypto wallets a user can select to receive to. Fiat eligibility shouldn't have an affect receiving crypto wallets so i'm removing it.
=> fix(receive crypto): removes check for canDepositFiat when listing crypto accounts to receive

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/Trade.tsx, yarn.lock
Upgrade @blokchain-com/icons@0.0.4
Before:
After:
=> chore(@blockchain-com/icons): upgrade icons to v0.0.4

packages/blockchain-info-components/src/Form/CheckBoxInput.js
Using permanently the `alwaysWhite` color for the checkbox tick to avoid color change.
=> fix: fixing checkbox tick color for using with dark mode theme

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Header.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/Header.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/SubHeader.stories.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/SubHeader.tsx, packages/blockchain-wallet-v4-frontend/src/components/Flyout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Transfer/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/CoinSelect/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx
from 
to this which is more inline with the "New Swap" layout on the previous step.
I also removed the `StickyHeaderWrapper` component that was being used in several places and converted swap coin selection and send/receive coin selection screens to use the `/components/Flyout/Layout` components (Container, Header, SubHeader, Content) and added an optional `sticky` param to the header and sub header components if they're needed.
=> fix(swap): fix padding issue with coin selection header

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/template.tsx
Fixes issue where there's no email address after metadata recovery, and user can't proceed to wallet after mnemonic recovery. 
https://www.loom.com/share/becd850128e640e1b80a27ad77ea6ba6
=> fix(recovery): skip email verification if metadata recovery

packages/blockchain-wallet-v4-frontend/src/hooks/index.ts, packages/blockchain-wallet-v4-frontend/src/hooks/useBankAccountsQuery/index.ts, packages/blockchain-wallet-v4-frontend/src/hooks/useBankAccountsQuery/useBankAccountsQuery.stories.mdx, packages/blockchain-wallet-v4-frontend/src/hooks/useBankAccountsQuery/useBankAccountsQuery.ts, packages/blockchain-wallet-v4-frontend/src/hooks/useBankAccountsQuery/useBankAccountsQuery.types.ts
This adds the useBankAccountsQuery hooks to retrieve the use bank accounts from redux in hook form.
This will be used in the coin view activity feed
=> chore(useBankAccountsQuery): add hook to load/retrieve user bank accounts

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PreviewSell/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/model.tsx
This PR solve issue with new error code for sanctions
- Need account with sanctions
- need to have more that 10K crypto, try to sell error should be visible
=> feat(sanctions): cover error 165 with proper error messaging

packages/blockchain-wallet-v4-frontend/src/hooks/useCoinConfig/useCoinConfig.spec.ts, packages/blockchain-wallet-v4-frontend/src/hooks/useCoinConfig/useCoinConfig.ts, packages/blockchain-wallet-v4-frontend/src/hooks/useCoinConfig/useCoinConfig.types.ts, packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useHoldingsCard/useHoldingsCard.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/TransactionListItem/TransactionListItem.tsx
This refactor allow the consumer of this hook to wait for the coin's
configuration to be loaded before consuming the window.coins.
This is required because the window.coins are loaded asynchronously, and
this hook could emit an error when the coin is not loaded yet
=> refactor(useCoinConfig): this refactor adds an async state to the hook

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
This prevents the buy sell flow from failing when the delete
order call fails with a 409 status. 409 status is a conflict
error from the api
=> fix(BuySell): prevent order fails when deleting pending order

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
Getting incorrect field value name from form, was causing 'unknown guid' error in authorization. 
=> fix(exchange-guid): use correct value name for form submission

packages/blockchain-info-components/src/Form/TextAreaInput.js, packages/blockchain-wallet-v4-frontend/src/components/Form/TextArea/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryPhrase/FirstStep/index.tsx
- Use input (TextBox) for mnemonic recovery form
- Ensure autocomplete='off' prop gets passed correctly to textarea component
=> fix(textarea): pass autocomplete prop to base textarea component

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/model.ts, packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/ExtraFields.stories.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/kyc/index.ts, packages/blockchain-wallet-v4/src/network/api/kyc/types.ts
=> feat(kyc extra): pass over context to save KYC extra fields call

packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterEmailOrGuid/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryPhrase/SecondStep/template.tsx
* move error message to bottom of input to avoid overlap
=> fix(login-error-overlap): move error to bottom

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/OrderSummary.tsx, packages/blockchain-wallet-v4-frontend/src/data/analytics/types/walletRewardsClientEvents.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/index.tsx, yarn.lock
- Remove the rewards legacy banner
- Add "Earn Rewards" flow to "Buy" flow if user/token is eligible.
=> SRW-91 - modify 1-click interest in buy flow

packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx
1. send correct state format to `/address/initial` when signing up via exchange mobile
2. Remove normalization of state value. Value would become undefined after state was chosen, triggering this error
=> fix(signup): state field value and exchange signup fix

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Errors/Oops.tsx
Checks if the errorMessage is actually a string, this
is needed because errors can be objects and React is
throwing errors when trying to render an object in the view
=> fix(Flyout): only display error if is string

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/ArriveInThreeDaysEasyBankTransferCard/ArriveInThreeDaysEasyBankTransferCard.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/InstantlyEasyBankTransferCard/InstantlyEasyBankTransferCard.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/Methods.styles.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/OneDayBankTransferCard/OneDayBankTransferCard.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/PaymentCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/SameDayBankTransferCard/SameDayBankTransferCard.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/WireTransferCard/WireTransferCard.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/index.tsx
Remove duplicated Wire Transfer item in the payment methods and update style to match other items
Before:
After:
=> fix(PaymentMethods): update styles to match rest of option

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
On the opening of deposit & withdraw modals, we were waiting for 2 types of events:
setAllContextQuestionsAnswered or closeModal
This was intended to know if the user completed or dismissed the kyc questions, the problem is that we were hearing for ALL close modal events, even the ones that were not related to KYC.
To fix this, we now only close the deposit or withdraw modal if the closeModal modalName is KYC_MODAL or undefined
=> fix(LTMONB-28): prevent deposit and withdraw modal closing from irrelevant closeModal events

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/errors.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.test.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.types.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.test.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.types.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/index.ts, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/index.ts, packages/blockchain-wallet-v4-frontend/src/store/index.js
Add an interception to axios to intercept and log all nabu errors to segment
- Run app locally and open the [segment debugger](https://app.segment.com/blockchain/sources/web_staging/debugger) for staging
- Now for every nabu error you should see the error in segment a few seconds later
=> feat(NabuError): log all nabu errors to segment

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/selectors.ts
The Wire Transfer Page is dependent on the order remote, but when the user clicks in the Wire Transfer option, at that moment there is no order so the Wire Tranfer flyout would be loading forever.
This removes the dependency on the remote to render the page, that way the page can load the account and userData and then load the order separately
https://user-images.githubusercontent.com/99212903/180319241-4e9600a9-0c75-405d-ac04-44b5431f871d.mov
=> fix(WireTranfer): remove the order dependency on wire ttranfer flyout

packages/blockchain-wallet-v4-frontend/src/scenes/plugin/common/TransactionStatus/index.tsx
Example of usage: 
`  <TransactionStatus
closePopup={closePopup}
history={history}
messageId='plugin.send.transaction_cancelled.title'
title='Transaction cancelled'
>
<IconClose height='70%' width='70%' color='black' />
</TransactionStatus>
`
=> feat(plugin): common transaction status wrapper added

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/utils/isApplePayAvailable/isApplePayAvailable.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
Updates the order of the banners so apple and google pay
is first, and catch error when trying to check for apple pay
availability on safari
=> fix(AppleAndGooglePay): this changes the banner order

packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/Payment/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/Bank/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/Card/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx
Fix some UI styles in the card/bank items
=> fix(Card/Bank): trim bank/card name when reach full width

packages/blockchain-wallet-v4-frontend/src/components/NabuErrorDeepLinkHandler/NabuErrorDeepLinkHandler.tsx
Sets the card remote in redux to NotAsked when the user clicks in try another card
=> fix(NabuErrorActions): clear card remote on click "try another card" action

packages/blockchain-wallet-v4-frontend/src/components/GenericNabuError/GenericNabuError.tsx, packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.types.ts
read correct status icon URL
Before
After
=> fix(NabuError): handle when status icon is not present

packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/useWalletsCard.tsx
The wallets card was not correctly setting the loading state, this changes the loading state to look at all dependencies
=> fix(CoinView): map loading state correctly in wallets card

packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.tsx
Removes text at the bottom of this modal:
Looks like this now
=> fix(stx-airdrop): remove old availability copy

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/hooks/useBlockedPayments/useBlockedPayments.tsx
Use the nabu ux title when rendering the buy button
=> feat(PaymentMethod): use nabu ux title as the buy flow button content

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/CheckoutConfirm.styles.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/hooks/index.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/hooks/useRecurringBuySection/index.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/hooks/useRecurringBuySection/useRecurringBuySection.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/hooks/useRecurringBuySection/useRecurringBuySection.types.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts
- Removed the recurring buy option on create order
- Creates the recurring buy after the order payment is successful
- Add toggle to include recurring buy on checkout page
https://user-images.githubusercontent.com/99212903/185391419-0c638c70-e48f-4910-aa8b-dca7ea0c6de0.mov
=> feat(Buy): add recurring buy option in checkout page

packages/blockchain-wallet-v4-frontend/src/services/browser/index.tsx
Handles literal edge case (haha!) where Android user is trying to verify their login. Motorola Edge device came out last year, bowser assumes string 'edge' in user agent means it's a Microsoft Edge browser. There's no version attached to it though, so version is undefined and `browser.satisfies` returns false for all checks. 
=> fix(browser-detection): bypass motorola edge issue

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
Add a notice to the rewards flyout
=> feat(rewards-notice): add notice to bottom of rewards flyout

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/types.ts, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts
Addresses issue reported by Peter - we only call `/users` to create or get a nabu user if it's the users first login. This is an issue for older wallets (created pre-nabu) since login throws an error like this. 
Main fix is we pass `firstLogin` boolean from loginRoutineSaga into nabu profile signIn function. If it's false but nabu credentials are empty, we call the createUser saga. 
=> fix(create-user): create user if credentials empty in metadata

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts
`getCurrentTier` selector expects user data, allows for it to be undefined for wallets without nabu accounts. 
=> fix(get-tier): allow for undefined user

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/slice.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/Staking/AccountSummary/AccountSummary.BalanceDropdown.template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Staking/AccountSummary/AccountSummary.Detail.template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Staking/AccountSummary/AccountSummary.model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Staking/AccountSummary/AccountSummary.selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Staking/AccountSummary/AccountSummary.template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Staking/AccountSummary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Staking/Warning/Warning.template.tsx
* add a balancedropdown to staking manage screen
* change Staked {token} to {token} balance
* If user has pending transactions between 1 & 4, pending transactions will automatically open
* Show user how many pending transactions they currently have
* rework fee detail row
* update copy on staking warning modal
* fix pending transfer value
* fix minimum amount error value in staking deposit modal
=> Feat/stak 88/manage screen

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/utils.test.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/utils.ts
Replaces existing default sort by just market cap with the following sort order:
1. Trading Assets
2. Descending by Market Cap
3. Ascending Alphabetically
=> feat(Prices): change default sorting on Prices page

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/utils.test.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/utils.ts
Application of padding relative to the height of the chart was causing issue with scale for assets with lower price. Thus, the padding values should be relative to the values domain.
| Before  | After |
| ------------- | ------------- |
| <img width="818" alt="Screenshot 2022-10-25 at 14 20 22" src="https://user-images.githubusercontent.com/114945181/197784288-621dbb2e-6adc-4c3b-8a70-f1627ecd4f39.png"> | <img width="818" alt="Screenshot 2022-10-25 at 14 20 26" src="https://user-images.githubusercontent.com/114945181/197784339-2d6c2da6-cf70-45ec-973e-c5a75e577bf1.png">  |
| <img width="818" alt="Screenshot 2022-10-25 at 14 20 31" src="https://user-images.githubusercontent.com/114945181/197784436-64390f81-3055-412c-b897-a072e2e92ae9.png">  | <img width="818" alt="Screenshot 2022-10-25 at 14 …
=> fix(Home): fix the way how linear domain is padded

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/UpgradeToGold/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/UpgradeToGold/template.tsx
This PR just cleans up our component to prevent entire props spread and use constellation 
=> feat(upgrade to gold): cleanup and added usage of constellation

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
Order processing became asynchronous in Feynman, thus, we need to poll for order completion. Making this change for funds orders only for now as requirements for other payment types are not clear right now.
Select funds payment method and place an order. You should see success screen instead of pending.
=> fix(buy): poll confirmed buy fund order

packages/blockchain-wallet-v4-frontend/src/providers/ErrorBoundaryProvider/index.test.tsx, packages/blockchain-wallet-v4-frontend/src/providers/ErrorBoundaryProvider/index.tsx
Currently we are not tracking errors that are coming from our components and crash the whole React tree. We already have an error boundary that displays an error modal, so we shall track caught errors there too.
=> feat(ErrorBoundary): track caught errors

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/index.tsx
If the Enter Amount screen is accessed directly (e.g. by clicking Buy Bitcoin on home page), orders have to be fetched for default method to be available and Enter Amount screen to load.
Click buy on home or coin page.
=> fix(EnterAmount): fetch orders for default method to be available

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas/createBuyQuoteLoopAndWaitForFirstResult.test.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas/createBuyQuoteLoopAndWaitForFirstResult.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/validation.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/Frequency/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/SellEnterAmount/Checkout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/index.tsx
By removing crypto amount and switch between fiat/crypto (consistent with Android/iOS apps) on Buy screen, we finally can remove creation of fake Buy quotes which cause inconsistencies with numbers we are showing to the users.
| Before  | After |
| ------------- | ------------- |
| <img width="476" alt="Screenshot 2022-12-12 at 16 39 02" src="https://user-images.githubusercontent.com/114945181/207106672-8b093e51-25cd-4391-afc3-49f0feb45f7c.png">  | <img width="476" alt="Screenshot 2022-12-13 at 12 52 30" src="https://user-images.githubusercontent.com/114945181/207323193-bd6b197e-e7ff-4118-b03f-bdbffb6c8575.png">  |
=> feat(EnterAmount): remove crypto amount

packages/blockchain-wallet-v4-frontend/src/scenes/ActiveRewardsLearn/Header/index.tsx, packages/blockchain-wallet-v4/src/network/api/earn/types.ts
=> fix(active-rewards-learn-eligible): fix eligible check

packages/blockchain-wallet-v4-frontend/src/services/postCodeValidator/postCodeRegex.ts
Issue reported by CS, Canadian postal codes are not being validated correctly. Updated regex and spot checked a few random zips. 
=> fix(postcode): correct regex for candian postcodes

packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/SelectToken.selectors.ts, packages/blockchain-wallet-v4/src/network/api/dex/index.ts, packages/blockchain-wallet-v4/src/network/api/dex/types.ts
Atm we have a larger list from DEX backend than we are able to get balances for on FE. Temporary solution is to remove these tokens from the list. Later that problem will be solved. More context here: https://blockc.slack.com/archives/C03C60CF89L/p1672318734848579
=> fix(dex-tokens): filter DEX coins list

packages/blockchain-wallet-v4-frontend/src/components/Brokerage/AvailabilityRows/hooks/useValue.ts, packages/blockchain-wallet-v4-frontend/src/components/Brokerage/AvailabilityRows/types.ts, packages/blockchain-wallet-v4-frontend/src/components/NetworkWarning/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/ConfirmButton.test.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/ConfirmButton.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/models/quoteSummaryViewModel.test.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/models/quoteSummaryViewModel.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/BuySell/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/buySell/types.ts, typings/window.d.ts
In order to get rid of order creation on checkout step, we need to make sure that none information from order response is used on the checkout step. This PR replaces usage of order information with quote.
To simplify the component, all calculation and formatting logic was extracted from a component to a view model.
Go to Buy flow, and proceed to Checkout confirmation step. Given the same quote, all the displayed values should be the same as before.
=> feat(Buy): remove usage of order information from checkout screen

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/accountRecovery.ts, packages/blockchain-wallet-v4-frontend/src/data/analytics/types/login.ts, packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/Wallet/SkipTwoFAVerificationRecovery/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/NeedHelpLink/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/TwoFAConfirmation/index.tsx
- Adds missing 2FA events for account recovery
- Changes 'Login Helped Clicked' -> 'Forgot Password Clicked'
=> feat(account-recovery): add events for 2fa confirmation

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas/createBuyOrder.ts
Gpay orders are failing when beneficiary id is passed as payment method id to the request. Thus, we shall avoid doing that even though from client perspective it would make sense to pass it since it is also passed to quote (before order creation) and confirmation (after order creation).
Buy flow using mobile payment options to be tested.
=> fix(mobile-payments): avoid passing payment method id to order creation request

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
Fixes bug where we were sending `state:null` if non-US user entered a Region in the address form for KYC.  
=> fix(address-form): send region as string instead of null

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxXlmAddresses/selectors.ts
Fixes issue that causes xlm PKW to show 0 balance for send
=> fix(xlm): typo for send wallet balance

packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts
Fixes bug where account recovery doesn't work because there's no signup country from form values
=> fix(account-reset): skip country from formValues if account reset

packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts
We've decided to not send the 'Wallet Signed Up' event for account recovery. This will solve the issue of wallet signups increasing while email verifications remained the same + `none` country value for some signup events. 
=> fix(recovery): dont track recovery as signup

packages/blockchain-wallet-v4/src/coinSelection/coin.js, packages/blockchain-wallet-v4/src/coinSelection/coinSelection.spec.js, packages/blockchain-wallet-v4/src/coinSelection/index.js
Demote utxos with 0 confirmation in btc send coin selection
=> fix(coin-selection): demote 0 confirmation utxos

packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterEmailOrGuid/index.tsx
Error now shown on the top right
=> fix(login): change position of error message

packages/blockchain-wallet-v4-frontend/src/components/Form/FormItem/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/template.success.tsx
There was an issue during some KYC cases where the dropdowns will have some options that didn't register the mouse as they were "behind" other inputs in terms of z-index
Additionally, fixed some react-key related errors. Although the entire file should be refactored moving the "renderXXXcomponent" to separate files
=> fix(kyc): dropdown fields now don't overlap with inputs

packages/blockchain-wallet-v4-frontend/src/data/cache/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/swap/slice.ts, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Page/index.js, packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/ActiveRewardsBanner/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/AppleAndGooglePayBanner.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/BuyCrypto/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CoinRename/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/ContinueToGold/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/FinishKyc/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/NewCurrency/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/RecurringBuys/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/RewardsBanner/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/ServicePriceUnavailable/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/StakingBanner/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/constants.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/template.tsx
The `fetchProductEligibilityForUser` is being done when the user logs in, so it can be safely called without re-fetching it when loading the modal
=> Do not refetch user eligibility when opening the buy modal nor when adding a bank

packages/blockchain-wallet-v4-frontend/src/scenes/Signup/BuyGoal/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/template.error.exchangeMobile.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/LoginLink/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Signup/types.ts, packages/blockchain-wallet-v4/src/redux/data/coins/selectors.ts
There is more work to do, but this is an initial nudge into a cleaner slate
- Remove `ramda`
- Use `redux` hooks
- Pass down only necessary props to child components
- Fix return on `NotAsked` cata
- Remove unused `appEnv` and `miscActions` variables
- Pick only required elements for props
- Use `redux` hooks to get required state and dispatch, removing the need of props
- Made this a component, as it was being built and exported in the `index.tsx` file
- Refactor accordingly to new `LoginLink` component
- Moved `LoginLink` to own file
- Removed exports that were not used
- Removed `unified` and `analyticsActions` as they are now imported directly where they are used in `LoginLink`
- Removed `domains`, `signupMetadata`, `alertActions` as they were not used 
- Removed unused type
- Added …
=> chore(signup): code refactor
