blockchain/blockchain-wallet-v4-frontend

packages/blockchain-wallet-v4-frontend/src/data/auth/actionTypes.js, packages/blockchain-wallet-v4-frontend/src/data/auth/actions.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js, packages/blockchain-wallet-v4-frontend/src/middleware/autoDisconnection.js, packages/blockchain-wallet-v4-frontend/src/modals/AutoDisconnection/index.js, packages/blockchain-wallet-v4-frontend/src/store/configureStore.dev.js, packages/blockchain-wallet-v4-frontend/src/store/configureStore.prod.js
@Lyncee59 per out discussion deleted sagas and fixed autoDisconnect middleware. added resetting autodisconnect timer when we reset the field.
=> Fix auto logout

package.json
This resolves the issues with Storybook that were caused by the recent Webpack 4 upgrade.
=> Upgrade storybook to 4.0-alpha which supports Webpack 4

packages/blockchain-wallet-v4-frontend/src/components/Tray/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/Faq/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/WhatsNew/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Faq/FaqContent/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Faq/FaqGroup/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Faq/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Faq/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/app.js
- Use our own CSS3 transitions instead of a library
- Fixes a few mobile display bugs
- Better setup for dynamic content within the tray itself
=> Side Tray Refactor Part 1

.eslintrc, packages/blockchain-info-components/.eslintrc, packages/blockchain-wallet-v4-frontend/.eslintrc, packages/blockchain-wallet-v4/.eslintrc
- Ensures lint errors aren't thrown when async/await code is written
- Removes unused `.eslintrc` files
=> Add ECMAScript 8 parsing support to ESLint

packages/blockchain-wallet-v4-frontend/src/components/Faq/FaqContent/index.js, packages/blockchain-wallet-v4-frontend/src/components/Faq/FaqGroup/index.js
=> reformatting faq

packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js, packages/blockchain-wallet-v4/src/redux/data/coinify/sagaRegister.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagaRegister.js
=> fix - broken build

packages/blockchain-wallet-v4-frontend/src/components/WhatsNew/__snapshots__/template.spec.js.snap
=> Fix development branch

package.json
=> chore(Release): bump to v4.0.0-alpha2

packages/blockchain-wallet-v4/src/redux/settings/sagas.js
=> fix update-ip-lock-on call

packages/blockchain-wallet-v4-frontend/src/data/components/priceChart/sagas.js
=> fix price chart time

packages/blockchain-wallet-v4-frontend/src/components/ExchangeTimeline/Step3/index.js, packages/blockchain-wallet-v4-frontend/src/components/ExchangeTimeline/index.js, packages/blockchain-wallet-v4-frontend/src/components/ExchangeTimeline/services.js, packages/blockchain-wallet-v4-frontend/src/modals/ExchangeDetails/template.success.js
=> Exchange history bugs

package.json
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> chore(Release): v4.0.0-alpha3

package.json
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> chore(Release): v4.0.0-alpha4

packages/blockchain-wallet-v4-frontend/src/components/Faq/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/index.js
Reset faq form on handleTrayRightToggle
- Feature
Open the FAQ tray. Type something in the search bar. Close it by clicking outside or clicking the close button. Reopen the tray and see the search field is clear and the results are not filtered
=> Reset faq search on handleTrayRightToggle

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/components/Security/SecurityContainer.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/template.js
- Fix issue after a user has completed the 3 initial security center steps, and then attempts to tab over to Advanced Security at the header.  
- Cleans up some CSS and small layout issues
Bug Fix
Complete 3 security steps and then go to advanced page tab
=> Fix advanced security settings loading

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js
- Fixes issue where Yubikey codes were being uppercased when they should not have been resulting in login failures.
- Makes the Yubikey input a password box on login page
Bug Fix
Create account with 2FA Yubikey and attempt to login
=> Fix Yubikey 2FA issue

packages/blockchain-info-components/.storybook/webpack.config.js
Fixes storybook
- Chore: storybook needed a file-loader to handle assets like ttf and svg
Run storybook
=> Fix storybook

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bch/Content/Empty/BitcoinCashWelcome/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bitcoin/Content/Empty/BitcoinWelcome/index.js
Fixes issue where new wallets were unable to go to the Tx pages
Bug Fix
Create new wallet and go to transactions pages for BTC and BCH.
=> Fix new wallet welcome messages

package.json
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> chore(Release): v4.0.0-alpha6

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/index.js
fetch buy/sell metadata to determine account
- Bug Fix
=> fix(BuySell): fetch buy/sell metadata for canTrade

packages/blockchain-wallet-v4-frontend/src/modals/SendBch/SecondStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBch/SecondStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/services/PaymentHelper/index.js
display a warning when sending bch to btc address
=> display a warning when sending bch to btc address

packages/blockchain-wallet-v4/src/utils/ethereum.js
use checksum address for etherem
=> use checksum address for etherem

packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js
=> do not close the send screen when selecting the currency that was already selected

packages/blockchain-wallet-v4-frontend/src/modals/ShowEthPrivateKey/index.js
=> fix(Eth): show correct legacy priv key/addr

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Upload/camera.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Upload/template.js
698
- Bug Fix
Doc upload on safari and FF
=> react-webcam for better browser compat

packages/blockchain-info-components/src/Form/PasswordInput.js, packages/blockchain-info-components/src/Form/TextInput.js, packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/Form/PasswordBox/index.js, packages/blockchain-wallet-v4-frontend/src/components/QRReader/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Upload/camera.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Upload/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.js, packages/blockchain-wallet-v4-frontend/webpack.config.js, server.js
=> Browser Detection

package.json
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Add babel-plugin-add-module-exports

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/SanitizedFormattedHTMLMessage/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> feat(Translations): add sanitized formatted html

packages/blockchain-wallet-v4-frontend/src/middleware/autoDisconnection.js
=> add socket related actions to auto disconnect blacklist

config/wallet-options-v4.json, packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.js
207
- Bug Fix
Send eth with low fee
=> Unconfirmed eth tx

packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberVerify/index.js
=> Misc fixes

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4/package.json, packages/blockchain-wallet-v4/src/network/api/sfox/index.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
Pass trade length to modules
817
- Bug Fix
=> Sfox Trade History

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/index.js, packages/blockchain-wallet-v4-frontend/src/services/ExchangeService/index.js, packages/blockchain-wallet-v4/src/redux/data/coinify/sagas.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
=> fix(use ramda and map to remove token value of undefined errors)

packages/blockchain-info-components/src/Form/SelectInput/index.js
On click outside or on click on an element of a selectinput, clear the search so that other inputs can still be selected.
482
- Bug Fix
=> fix(selectinput search)

packages/blockchain-wallet-v4-frontend/src/components/BuySell/OrderHistoryTable/TradeItem/index.js
689
- Bug Fix
Go to SFOX trade history, see the time is in the right format
=> fix(sfox trade times formatting)

packages/blockchain-info-components/src/Form/CheckBoxInput.js, packages/blockchain-info-components/src/Form/RadioButtonInput.js
=> fix(Checkbox): accessibility, add check

packages/blockchain-info-components/src/Modals/__snapshots__/ModalHeader.spec.js.snap, packages/blockchain-info-components/src/Text/Text.js, packages/blockchain-info-components/src/Text/__snapshots__/Text.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/BuySell/OrderHistoryTable/TradeItem/index.js
Use number for text opacity fine tuning and remove warnings
- Bug Fix
=> fix(text opacity issue)

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberChange/index.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberChange/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberChange/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Info/PairingCode/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Info/PairingCode/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Info/WalletId/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Info/WalletId/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/AutoLogout/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/BitcoinLinkHandling/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/LocalCurrency/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/LocalCurrency/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/MobileNumber/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/MobileNumber/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Notifications/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Notifications/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Notifications/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Themes/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Themes/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Themes/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/WalletLanguage/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/WalletLanguage/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/WalletLanguage/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Settings: change phone number flag

packages/blockchain-wallet-v4-frontend/src/modals/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBitcoin/FirstStep/template.success.js
=> disable continue button when form is pristine

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/RecordBackupPhrase/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/index.js
=> handle the case when recovery phrase wasn't generated

packages/blockchain-wallet-v4-frontend/src/modals/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBitcoin/FirstStep/template.success.js
enable entering address after dropdown was clicked but no address was selected
706
- Bug Fix
=> send BTC/BCH to field

packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberChange/template.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Create/VerifyMobile.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/TwoStepVerification/SMS/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/TwoStepVerification/SMS/template.success.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Phone Number Box

packages/blockchain-wallet-v4-frontend/src/components/Form/DateBoxDebounced/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/Sell/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Fix initialize action naming

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/selectors.js
I broke these in a previous PR
- Bug Fix
=> Fix Buy/Sell Tabs

Dockerfile
Our new Node 10 image doesn't have Python installed by default
Bug Fix
Dev build should succeed.
=> fix(docker image via python install)

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js
204, 207
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> wait until previous kvStore update succeeds

package-lock.json, packages/blockchain-wallet-v4/package.json
=> fix(Eth): upgrade util lib

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bch/Content/Pages/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bitcoin/Content/Pages/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Ether/Content/Pages/template.success.js
827
- Bug Fix
Search by tx list description
=> fix(TxList): key by hash instead of index for description field fix

packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/FiatAtTime/ValueWhenReceived/selectors.js
when the value was > 1000, it had commas and was failing. 903
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Fix fiat at time parsing

packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js, packages/blockchain-wallet-v4-frontend/src/data/router/sagaRegister.js, packages/blockchain-wallet-v4-frontend/src/data/router/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/sagas.js
852
On back or forward browser button click, close all modals.
- Feature
=> feat(close all modals on router location change)

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/template.success.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Coinify Signup / Country Prop

packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Create/AcceptTerms.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Create/index.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
Signup was getting caught in a loop because of cWRP
- Bug Fix
=> sfox signup fix

packages/blockchain-wallet-v4/src/redux/wallet/sagaRegister.js, packages/blockchain-wallet-v4/src/redux/wallet/sagas.js
984
- Bug Fix
Create new default wallet, open request.
=> Refetch context when setting default wallet

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Advanced/index.js
=> fix(enable wallet header display on firefox)

packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/session/actionTypes.js, packages/blockchain-wallet-v4-frontend/src/data/session/actions.js, packages/blockchain-wallet-v4-frontend/src/data/session/reducers.js, packages/blockchain-wallet-v4/src/redux/settings/sagas.js
pass true instead of 1 to api call
fixes 665 and more.
- Bug Fix
=> remove session token when remember 2fa is disabled

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/index.js
=> fix(no setState in render)

packages/blockchain-wallet-v4-frontend/src/providers/ModalEnhancer/index.js
=> feat(close modals on esc and click outside)

packages/blockchain-wallet-v4/src/redux/common/bch/selectors.js, packages/blockchain-wallet-v4/src/transactions/ethereum.js
976
@Lyncee59 This is a continuation of the work we did a few weeks ago. There are still a couple areas where we're using `fast-memoize` but they don't seem to be causing issues at this time. 
- Bug Fix
=> After buy/sell, fix crash issue

packages/blockchain-wallet-v4-frontend/src/data/modules/coinify/sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInput.js
=> Coinify - Initialize Checkout

packages/blockchain-info-components/src/Form/NumberInput.js, packages/blockchain-wallet-v4-frontend/src/components/Form/CountdownTimer/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/TextBoxDebounced/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInputTemplate.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderReview.js
840 and a small Coinify change
- Bug Fix
=> Improve countdown timer for SFOX quotes

packages/blockchain-wallet-v4-frontend/src/services/ExchangeService/index.js
954
- Bug Fix
Use v2 wallet to log in.
=> respect invited field in settings

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/selectors.js
=> fix(backup recovery phrase again)

packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/template.success.js
775
- Bug Fix
Create new wallet, see balance chart
=> fix(Balances Chart): grey when empty

packages/blockchain-wallet-v4-frontend/src/data/modules/coinify/sagas.js
=> fix(clear coinify checkout error on checkout form init)

packages/blockchain-wallet-v4-frontend/src/modals/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBitcoin/FirstStep/template.success.js
=> add validate required to select address dropdown

packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.spec.js
=> phone number field

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/template.success.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(BuySell): fixes submit handler

packages/blockchain-wallet-v4-frontend/src/providers/ModalEnhancer/index.js
Fix - modal window: key event had side effect on modal content
- Bug Fix
=> hotfix - reverted modal component 

packages/blockchain-wallet-v4/src/types/Wallet.js
=> Uncompressed key

packages/blockchain-wallet-v4-frontend/src/providers/ModalEnhancer/index.js
Reverts blockchain/blockchain-wallet-v4-frontend#572
=> Revert "hotfix - reverted modal component "

packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/index.spec.js
Reverts blockchain/blockchain-wallet-v4-frontend#567
=> Revert "phone number field"

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/template.success.js
Reverts blockchain/blockchain-wallet-v4-frontend#566
=> Revert "fix(BuySell): fixes submit handler"

packages/blockchain-info-components/src/Banners/Banner.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBch/SecondStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Components/ChangeEmailSteps/index.js
=> fix(Banner): wrap child of caution banner in Text

packages/blockchain-wallet-v4-frontend/src/data/components/signMessage/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/ShowBtcPrivateKey/template.js, packages/blockchain-wallet-v4/src/signer/btc.js, packages/blockchain-wallet-v4/src/utils/bitcoin.js
802
- Bug Fix
Sign msg from 5KbC1dvYq3LtDe2xyFPnMcDswxCkAVzAJ1SioRJ3AfBfxNPh3d2 key and 1Ma2DrB78K7jmAwaomqZNRMCvgQrNjE2QC addr
=> fix(Sign Message): sign msg from uncompressed key

packages/blockchain-wallet-v4-frontend/src/services/CoinifyService/index.js
=> fix(display pending for reviewing trades)

packages/blockchain-wallet-v4-frontend/src/modals/SignMessage/FirstStep/template.js, packages/blockchain-wallet-v4-frontend/src/modals/SignMessage/SecondStep/template.js
534
- Stylistic
Sign import address msg
=> style(Sign Msg): clean up

packages/blockchain-info-components/src/Tooltip/__snapshots__/Tooltip.spec.js.snap, packages/blockchain-info-components/src/Tooltip/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/ActivityList/ListItem/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/ActivityList/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/ActivityList/template.success.js
707, 935
- Bug Fix
Hover account name in tx list
=> fix(Tooltip): tooltip arrow down fix

packages/blockchain-wallet-v4-frontend/src/components/Form/NumberBoxDebounced/index.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Create/AcceptTerms/template.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Create/VerifyEmail/index.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Create/VerifyEmail/template.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/ISignThis/index.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Payment/mediumHelpers.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Payment/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/QuoteInput.js, packages/blockchain-wallet-v4/src/redux/kvStore/buySell/reducers.js
943, 765, 962
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> BuySell Fixes

packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
=> handle quote error

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.js
=> save last tx and timestamp for ethereum when trading eth

packages/blockchain-wallet-v4-frontend/src/data/modules/coinify/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Payment/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/Buy/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/Sell/selectors.js, packages/blockchain-wallet-v4-frontend/src/services/CoinifyService/index.js, packages/blockchain-wallet-v4/src/redux/data/coinify/selectors.js
1009, 913
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Coinify Bugs

packages/blockchain-wallet-v4-frontend/src/index.html
=> fix(Favicon): on public pages

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/Sell/SelectAccounts/template.success.js
=> fix(copy add new account instead of continue)

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/selectors.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/FaqContent/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/index.js
=> feat(FAQ): filter faq content by partner availability

packages/blockchain-wallet-v4-frontend/src/data/modules/coinify/sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInputTemplate.js
=> fix(coinify: get effective balance properly)

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js
=> Do not redirect to eth transactiona after sending a payment

packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.js
979: adds IE warning to sign up page as well
- Bug Fix
=> fix(SignUp): IE warning on sign up page

packages/blockchain-wallet-v4-frontend/src/modals/SendBch/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBitcoin/FirstStep/index.js
=> set touched when dropdown, forces to validate

packages/blockchain-wallet-v4-frontend/src/components/BuySell/FAQ/index.js, packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Payment/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxEnterMicroDeposits/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxEnterMicroDeposits/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderReview.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderCheckout.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/QuoteInput.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/QuoteInputTemplate.js
1010, 974, 839, 693, 682
- Bug Fix
=> Buy/Sell Random Fixes

packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Link/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Link/template.js
=> Load Plaid

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/orderReviewForm.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(SFOX): shorten ToS copy

packages/blockchain-wallet-v4/src/remote/index.js, packages/blockchain-wallet-v4/src/types/Serializer.js
=> feat(remote serialization and deserialization compliant with redux dev tools

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/template.success.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/index.js
548
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(BuySell): handle unsupported locations

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js
=> bch should accept btc address

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/ethereum/sagas.js
=> pass second password for eth metadata creation

packages/blockchain-wallet-v4-frontend/src/data/modules/coinify/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Create/AcceptTerms/index.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Create/AcceptTerms/template.js
Show a general error if the error is not `email_address_in_use`
- Feature
=> Coinify Signup Error Improvement

packages/blockchain-wallet-v4-frontend/src/services/ChartService/index.js, packages/blockchain-wallet-v4-frontend/src/services/ChartService/index.spec.js
Fix for chart time issue caused by moment's time obj being mutable
1054
- Bug Fix
=> Chart time

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js
=> fix(exchange conversion from fiat)

packages/blockchain-wallet-v4-frontend/src/components/Form/CheckBox/index.js
=> feat(checkbox disabling)

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBox/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/template.success.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/index.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validationMessages.js
=> Buy/Sell selecting country/state errors

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxBitcoinAddresses/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBch/FirstStep/template.success.js
=> feat(no watch only in bch send dropdown)

packages/blockchain-wallet-v4/src/redux/settings/sagas.js
- Bug Fix
1. Navigate to preferences
1. Change notification setup. Sms won't turn on without mobile verification, email won't turn on without email verification. Controls will be disabled w/o verification after [pull request](https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/645) is merged.
2. Change page and come back to preferences. Setup must stay the same unless you turned email/sms on without verification, in which case they must be off
3. Perform same test with logging out/back in
- [+] Code compiles successfully (verified via `yarn start`)
- [+] No lint issues exist (verified via `yarn lint`)
- [+] New and existing unit tests pass (verified via `yarn test`)
- [+] `README.md` and …
=> fix(notifications) fixed notifications checkboxes losing state

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
=> fix(Language): put updateLanguage action on login

packages/blockchain-wallet-v4-frontend/src/data/router/sagas.js
just clearing the redux state would've done the trick but if we're logging the user out we should do the whole logout flow.
1078
- Bug Fix
=> log out when navigating back to login page

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/selectors.js, packages/blockchain-wallet-v4/src/exchange/delegate/index.js
@plondon what do you think is the best way to get this commit onto the production version yet not break staging next time we do a release? (without manually switching it back and forth)
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> chore(BuySell): swap receiveAddress

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bch/Content/Empty/BitcoinCashWelcome/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bitcoin/Content/Empty/BitcoinWelcome/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Ether/Content/Empty/EtherWelcome/template.js
615
- Bug Fix
Test spacing and ui for tx feed empty states
=> style(Tx Empty): ui fixes for empty state in tx feeds

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/WhatsNew/WhatsNewContent/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/WhatsNew/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/WhatsNew/index.js
=> feat(Whats New): empty state

packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/ISignThis/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderCheckout.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/QuoteInputTemplate.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/template.success.js
Some sfox improvements and ramda
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> refactor(sfox content)

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInputTemplate.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Coinify): fixes level check

package.json, packages/blockchain-wallet-v4-frontend/src/components/ServiceAnnouncement/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxEnterMicroDeposits/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInputTemplate.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/TwoStepVerification/index.js
=> v4.0.0-alpha16

packages/blockchain-wallet-v4/src/exchange/delegate/index.js, packages/blockchain-wallet-v4/src/redux/data/coinify/sagas.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js
=> hotfix(exchange delegate: check environment for address generation)

packages/blockchain-wallet-v4-frontend/src/components/Form/CountdownTimer/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderReview.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> refactor(simplify countdown timer)

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BchWatchOnlyBalance/selectors.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BtcWatchOnlyBalance/selectors.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/SendBitcoin/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/SendEther/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/TransferEth/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Shapeshift/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bch/Content/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Bitcoin/Content/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Ether/Content/selectors.js, packages/blockchain-wallet-v4/src/redux/kvStore/bch/sagas.js, packages/blockchain-wallet-v4/src/utils/bch.js, packages/blockchain-wallet-v4/src/utils/bitcoin.js
Use ramda pathOr and propOr just for the love of ramda
- Refactor
=> refactor(introduce pathOr and propOr)

packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.js
Form destruction caused the form state destruction. This cleared guid upon language change.
- Bug Fix
1. Login
2. Logout without deauthorizing
3. Change language
=> fix - persisting guid upon language change/navigation

package-lock.json, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagaRegister.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js, packages/blockchain-wallet-v4-frontend/src/data/components/sagaRegister.js, packages/blockchain-wallet-v4-frontend/src/data/components/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Shapeshift/FirstStep/selectors.js
Added upper limit (max) for shapeshift from wallet-options
- Upgrades
=> fix - upperLimit in shapeshift based on wallet-options for regulation

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/SendEther/FirstStep/template.success.js
1089
- Bug Fix
Attempt to scan https://blockchain.info/payment_request?address=1LTjrNvVw5PSgyRLx9E5CAc8ABqLCAiHq2&message=hello+world&amount=1 qr code, see form fields are filled in.
=> fix(QR Scan): handle btc amt from scan

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BchBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BchWatchOnlyBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BtcBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BtcWatchOnlyBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/EthBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/template.js, packages/blockchain-wallet-v4/src/redux/kvStore/bch/selectors.js
=> fix(Top Balance): styles

packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.js
=> fix(IE): add msie to unsupported list

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BchWatchOnlyBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/BtcWatchOnlyBalance/template.success.js
Small style change to not show unspendable balance separator if balances are 0
=> style(Top Balance): dont show separator if no unspendable balances

packages/blockchain-wallet-v4/src/network/api/kvStore/index.js
=> fix(KVStore): return response.text if kvstore fetch err

packages/blockchain-wallet-v4/src/transactions/ethereum.js
1060
- Bug Fix
All currencies sent txs: should show amount sent + fee
All currencies received txs: should show amount received (NO fee)
**BCH/BTC/ETH transferred txs: should show amount sent (NO fee)**
=> fix(Eth): transferred/sent tx fees

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/services.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Shapeshift/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Shapeshift/FirstStep/validationMessages.js
fix maximum shapeshift to handle the max value when clicking on the link maximum, in addition to the form validation.
- Bug Fix
- Upgrades
=> fix - shapeshift maximum should handle upperLimit

packages/blockchain-wallet-v4/src/redux/data/ethereum/sagas.js
1093. Was causing tx list to skip 0th page
- Bug Fix
=> fix(Eth Tx): when reset pages should be 0

packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/sift-science.js, packages/blockchain-wallet-v4/src/redux/data/sfox/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/buySell/selectors.js
Fix buy sell metadata selector: Do not take data of Remote but expose Remote
- Bug Fix
=> fix(kvstore buysell selectors remote)

packages/blockchain-wallet-v4-frontend/src/data/components/layoutWallet/reducers.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/template.js
- Fixed footer being out of screen
- Fixed sidebar closing when pressed on **settings**
- Made menu scrollable (for small screens, e.g. iPhone SE)
- Bug Fix
Check description
=> fix - left menu responsive fixes

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bch/Wallets/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/AddressRow.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UnusedAddresses/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UsedAddresses/Table/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Menu/index.js
- word break for addresses in tables
- banners under values in tables
- search input menu size
- Bug Fix
1. Test on mobile, real device/emulator preferred to browser
=> fix - added addresses mobile optimizations:

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Shapeshift/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/Empty/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/template.js
Made exchange first step and order history more mobile friendly by reducing paddings
- Bug Fix
=> fix - added mobile optimiations to exchange page;

packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js
=> fix(SFOX): show modal after trade

packages/blockchain-wallet-v4/src/exchange/convertFiatToBitcoin.spec.js, packages/blockchain-wallet-v4/src/exchange/currency/index.js, packages/blockchain-wallet-v4/src/exchange/displayFiatToBitcoin.spec.js
Fix 1104 1115 but break 819
- Bug Fix
=> fix(use bigrational to decimal in conversion system)

package.json, packages/blockchain-wallet-v4-frontend/src/components/BuySell/OrderHistoryTable/TradeItem/index.js, packages/blockchain-wallet-v4-frontend/src/components/BuySell/OrderHistoryTable/index.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxTradeDetails/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Goals/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Ether/Content/Empty/EtherWelcome/template.js, packages/blockchain-wallet-v4/src/exchange/convertFiatToBitcoin.spec.js, packages/blockchain-wallet-v4/src/exchange/currency/index.js, packages/blockchain-wallet-v4/src/exchange/displayFiatToBitcoin.spec.js, packages/blockchain-wallet-v4/src/redux/walletSync/middleware.js
=> Release/v4.0.0 alpha17.4/5

package-lock.json, packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/providers/MatchMediaProvider/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderHistory/RecurringOrderHistoryTable/RecurringOrder/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderHistory/RecurringOrderHistoryTable/RecurringTrade/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/TradeItem/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/SecuritySteps/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Ether/Menu/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/app.js, packages/blockchain-wallet-v4-frontend/src/services/ResponsiveService/index.js
Added MediaContextProvider and MediaContextConsumer:
- Provider uses matchMedia to determine which media config is suitable
- Consumer injects media configs inside jsx structure and rerenders on media config change
- Using new context api
- Better responsiveness ^^
- Upgrades
=> upgrade - added matchmedia to rerender on screen size change

package-lock.json, packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/BuySell/OrderHistoryTable/TradeItem/index.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/template.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyTradeDetails/Recurring.js, packages/blockchain-wallet-v4-frontend/src/providers/MatchMediaProvider/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderHistory/RecurringOrderHistoryTable/RecurringOrder/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderHistory/RecurringOrderHistoryTable/RecurringTrade/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/OrderHistory/RecurringOrderHistoryTable/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/TradeItem/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/SecuritySteps/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Ether/Menu/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/app.js, packages/blockchain-wallet-v4-frontend/src/services/ResponsiveService/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Coinify): mobile friendly recurring order history

packages/blockchain-wallet-v4-frontend/src/components/BalancesChart/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/BchBalance/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/BchBalance/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/BchBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/BtcBalance/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/BtcBalance/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/BtcBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/EthBalance/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/EthBalance/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/BalancesChart/template.success.js
=> feat(display unknown amount below pie chart if endpoint fails)

package-lock.json, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/RecordBackupPhrase/SecondStep/template.js
Added the "previous 4 words" button that was present in v3 backup phrase scene.
- Feature
Go to Security Center > Backup Phrase > Backup Funds
=> added back button to backup phrase sequence in security center

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/AutoLogout/Settings/EditForm/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/AutoLogout/Settings/EditForm/template.js
Added units and helper text to Auto Logout settings.
- Feature
=> auto logout units and helper text

.gitignore, .travis.yml, package.json
Eslint is really slow on big project, cache will speed it up a ton.
- CI/CD
- Upgrades
=> fix - enabled eslint cache, added .eslintcache checksum file to travis cache

package.json
Testing a Concourse build hook.
=> Bump version to beta

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxBitcoinAddresses/selectors.js, packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js
645
- Bug Fix
Try sending to and from imported address.
=> format cash addresses

.travis.yml
Increase the timeouts of test commands for Travis
CI/CD
N/A
=> increase travis timeouts

.travis.yml
=> Undo Travis timeout increases

packages/blockchain-wallet-v4/src/redux/kvStore/bch/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/btc/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/buySell/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/contacts/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/ethereum/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/shapeShift/sagas.js, packages/blockchain-wallet-v4/src/redux/kvStore/whatsNew/sagas.js
Check for a type's empty value in addition to `null` and `undefined`
https://ramdajs.com/docs/#isNil
https://ramdajs.com/docs/#isEmpty
- Bug Fix
=> fix(kvStore): add isEmpty check

package.json
=> chore(Release): v4.0.0-beta1

Dockerfile, README.md, package.json
Require version 10.2 of Node and update readme.
Bug Fix
=> Fix Docker build with Yarn workspaces

.circleci/config.yml
Testing out a basic CircleCI build
CI/CD
PoC
=> Add basic CircleCI build

packages/blockchain-wallet-v4-frontend/src/modals/RequestBch/selectors.js
1130
- Bug Fix
1. Import btc address
2. Try to open request bch and click on imported bch addr
Steps above will break wallet on release/beta1
=> Request BCH - Selector tried to turn cashaddr to cashaddr

config/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js
Changed wallet options and default value in sagas
- Bug Fix
=> fix - changed shapeshift upper limit to 750

packages/blockchain-wallet-v4-frontend/src/components/Terms/index.js
=> fix(Tos): spacing

.gitignore, packages/blockchain-wallet-v4-frontend/webpack.config.js
Add support for WSS
Bug Fix
Local secure web sockets work
=> Fix(local secure web sockets)

config/env/production.js, config/wallet-options-v4.json
Rolled back production changes that got accidentaly merged
- Bug Fix
=> fix - fixed wallet helper apis

packages/blockchain-info-components/src/Form/TextInput.js, packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/RecordBackupPhrase/ThirdStep/template.js
Added the noLastPass attribute to stop lastpass from entering certain fields, such as wallet backup recovery keys.
- Feature
=> feat(TextInput): disable last pass attr

packages/blockchain-wallet-v4-frontend/src/scenes/app.js
=> fix(auth): reset2fa route typo fixed

packages/blockchain-info-components/src/Images/Images.js
Removed references to delete/unused images.
- Bug Fix
=> Images: Removed unnecessary images

packages/blockchain-info-components/src/Footer/index.js
Missing IntlProvider
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Footer: Add Missing IntlProvider

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderReview.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/template.success.js, packages/blockchain-wallet-v4-frontend/src/services/SfoxService/index.js
=> Feat/Jumio - Quotes, Trades

packages/blockchain-wallet-v4-frontend/src/scenes/Register/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.js, yarn.lock
Added more descriptive helper text to the password criteria. #899
- Feature
- Upgrades
=> feat(Register): added password criteria

packages/blockchain-wallet-v4-frontend/src/components/Alerts/template.js, packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js, packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/template.js, packages/blockchain-wallet-v4-frontend/src/data/components/importBtcAddress/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/ImportBtcAddress/ImportExternalBtcAddress/index.js, packages/blockchain-wallet-v4-frontend/src/modals/ImportBtcAddress/index.js, packages/blockchain-wallet-v4-frontend/src/modals/ImportBtcAddress/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/ImportBtcAddress/template.js, packages/blockchain-wallet-v4-frontend/src/services/AlertService/index.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/index.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validationMessages.js
Can now scan either a public or private key to import. They both use the same field. 
#496 and #786
- Bug Fix
- Upgrades
=> upgrade(import address): qr code compatible, one text field.

packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Addresses/Bch/index.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Addresses/Btc/index.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Addresses/Eth/index.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Addresses/index.js, packages/blockchain-wallet-v4/src/utils/bch.js
Refactored address display to avoid messy conditionals. Also fixes the problem of breaking bch tx feed when importing certain addresses that have differently formatted addresses.
#1187
- Refactor
- Bug Fix
=> Fix address display

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/WalletRecoveryPhrase/RecordBackupPhrase/ThirdStep/template.js
=> Added back button to backup phrase sequence

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js, packages/blockchain-wallet-v4/src/network/api/fetch.js, packages/blockchain-wallet-v4/src/network/api/index.js, packages/blockchain-wallet-v4/src/network/api/misc/index.js, packages/blockchain-wallet-v4/src/types/Wrapper.js
Reverts blockchain/blockchain-wallet-v4-frontend#838
=> Revert "upgrade(axios): tested axios for login flow, json errors and 2fa wall…"

packages/blockchain-wallet-v4-frontend/src/scenes/Home/ActivityList/template.success.js
Prevent the header of activity list widget from scrolling inside the widget frame
- Bug Fix
Use mobile width and scroll long activity list
=> fix: activity list scroll

packages/blockchain-wallet-v4-frontend/src/data/components/model.js, packages/blockchain-wallet-v4-frontend/src/data/index.js, packages/blockchain-wallet-v4-frontend/src/data/model.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/Address.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/IdentityVerification.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/Personal/EditEmail.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/Personal/EditSmsNumber.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/Personal/index.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/Personal/template.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/index.js, packages/blockchain-wallet-v4-frontend/src/modals/IdentityVerification/selectors.js
Model now is in the usable state
Import it in the same manner as you would actions or selectors: from 'data'
- Upgrades
=> upgrade(Tech debt): restructured model

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/FaqItem/FaqHeader.js
=> fixes FAQ when inverted theme enabled

packages/blockchain-wallet-v4/src/network/api/misc/index.js
Use a POST for BCH transaction export which fixes issue #875 
Bug Fix
BTC and BCH export works
=> fix(BCH history export)

packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/sfox/sagas.spec.js
1270
- Bug Fix
1. Create sfox account with jumio completed
2. Logout
3. Login, nav to buy/sell
4. Don't see jumio confirm modal
=> fix(Jumio): return payload when jumio status fetch is successful

packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberVerify/index.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberVerify/index.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/MobileNumberVerify/template.js, packages/blockchain-wallet-v4/src/redux/settings/sagas.js
=> Fix sms modal closing on incorrect code

package.json, yarn.lock
Update style-loader to include nonce-support instead of pointing dependency to commit
- Upgrades
=> chore/0.22.1 style-loader

packages/blockchain-wallet-v4-frontend/webpack.config.js, packages/blockchain-wallet-v4/src/exchange/delegate/index.js, packages/blockchain-wallet-v4/src/redux/rootSaga.js, packages/blockchain-wallet-v4/src/redux/wallet/sagaRegister.js, packages/blockchain-wallet-v4/src/redux/wallet/sagas.js
Fixes to buy/sell so it works with btc testnet.
- Feature
=> Make buy/sell work with testnet

packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Create/VerifyEmail.js, packages/blockchain-wallet-v4-frontend/src/modals/SfoxExchangeData/Create/VerifyMobile.js
moves error message below the fields
fixes 1192
- Bug Fix
=> fix(Sfox): errorbottom for mobile and email inputs

packages/blockchain-wallet-v4-frontend/src/index.html
=> Use correct nonce replace string

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.js, packages/blockchain-wallet-v4-frontend/webpack.config.js
- Fixes issue where logout routine would error out due to a `null` task trying to be canceled.
- Removes duplicate `script-src` entry from webpack dev server
Bug Fix
Logout routine should work
=> Fix(Application logout)

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/modules/transferEth/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.js
=> Eth Sweep + Exchange fixes 

packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.js
Fixes described crash
Also performs check if user can trade before going for sfox trades
- Bug Fix
=> fix(sfox): fixed sfox banner crash when there's no sfox data in kvStore

packages/blockchain-wallet-v4-frontend/package.json, yarn.lock
Updated react-tooltip to 3.8.0
- Upgrades
=> fix(CSP): updated react-tooltip to CSP-supporting verion

package.json, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/index.js
=> Release/v4.2.x to Master

.release-it.json, package.json, yarn.lock
Better, faster releases. Moves yarn manage:translations to the release process.
- Upgrades
=> chore(Release): add release-it

packages/blockchain-info-components/src/Form/SelectInput/index.js, packages/blockchain-wallet-v4-frontend/src/modals/CoinifyExchangeData/Create/AcceptTerms/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/ExchangeCheckout/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Goals/index.js
Fixed infinite loops based on suggestions. 
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Fixed a few infinite loops

package.json, packages/blockchain-info-components/package.json, packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4/package.json
Update license in package.json to reflect the license used at root.
Bug Fix
None required
=> fix(License): sync repo license with package.json

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInputTemplate.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/selectors.js, packages/blockchain-wallet-v4/src/redux/data/coinify/selectors.js
Fixes 7 day delay messaging bug
- Bug Fix
=> get canTradeAfter from core selector

packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js
Select bch change index, pass in BCH to util
- Bug Fix
=> fix(BCH): Select bch change index for bch payments

package.json
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> chore: removed engine versions

packages/blockchain-wallet-v4-frontend/src/data/modules/rates/sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): remove xlm forced from available pairs

packages/blockchain-wallet-v4/src/redux/common/xlm/selectors.js, packages/blockchain-wallet-v4/src/transactions/xlm.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): filtering out operations that do not belong to wallet

packages/blockchain-wallet-v4/src/redux/wallet/sagas.js, packages/blockchain-wallet-v4/src/types/Wallet.js
Upgrade non HD wallet was broken because of a missing arg in a curried function.
- Bug Fix
N/A
=> fix(upgradetohd): add missing arg to curried fn

packages/blockchain-wallet-v4-frontend/src/components/Navbar/NavbarNavItem.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/FaqIcon/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/Logout/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/RefreshIcon/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/WhatsNewIcon/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/FaqGroup/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/template.js
Implementing a new design for FAQ/Support. See https://cloudup.com/cIrsDkK_xoV
- Explicit Help button
- Resizing all icons
- Removing tip from Tray
- Adding support link to Tray
- Feature
- Changes are 90% visual. Added a new button as well.
=> Add support

packages/blockchain-wallet-v4-frontend/src/services/LockboxService/utils.js
Fixes XLM install issue that is caused by incorrect `providerName` parsing
Bug Fix
=> fix(XLM app install issue)

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/model.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): changed currencies order

packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js
=> fix: send from nonspendable with second password

packages/blockchain-wallet-v4-frontend/src/services/ChartService/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): whole history for price chart

packages/blockchain-wallet-v4/src/redux/kvStore/buySell/selectors.js, packages/blockchain-wallet-v4/src/redux/kvStore/buySell/selectors.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(ActivityList) fixed buy-sell label crash

packages/blockchain-wallet-v4/src/redux/payment/xlm/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/xlm/sagas.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): removed memo+memoType validation from payment

packages/blockchain-wallet-v4/src/redux/data/xlm/sagas.js, packages/blockchain-wallet-v4/src/redux/data/xlm/sagas.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): fixed empty xlm tx list flickering on scroll

packages/blockchain-wallet-v4-frontend/src/data/components/priceTicker/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/services.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/template.success.js, packages/blockchain-wallet-v4/src/exchange/currency/index.js, packages/blockchain-wallet-v4/src/exchange/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): 4 digits for xlm in charts

config/mocks/wallet-options-v4.json, packages/blockchain-info-components/src/Colors/Default.js, packages/blockchain-wallet-v4-frontend/src/components/ServiceAnnouncement/index.js, packages/blockchain-wallet-v4-frontend/src/components/ServiceAnnouncement/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/RequestBch/index.js
- Adds ability for service alert messages to appear in BCH send and receive modals
- Feature
=> Feat(BCH fork readiness)

packages/blockchain-wallet-v4-frontend/src/assets/locales/defaultMessages.json, packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/scenes/Reset2FA/SecondStep/template.js
=> fix: resest 2fa form copy

packages/blockchain-wallet-v4-frontend/src/assets/locales/defaultMessages.json, packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/AppManager/index.js
=> fix(Lockbox app manage connection copy)

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/components/ServiceAnnouncement/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Balances/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/Empty/CoinWelcome/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/Empty/CoinWelcome/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/Empty/CoinWelcome/template.airdrop.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/Empty/CoinWelcome/template.js
- Ensures welcome page only allows send and exchange buttons if coin is actually enabled
- Ensures service announcements display on small screens
- Aligns height for coin and graph widgets on home page
- Cleans up `PropType` errors on coin welcome and airdrop pages
Bug Fix
=> Fix(BCH fork related fixes)

packages/blockchain-wallet-v4-frontend/src/assets/locales/defaultMessages.json, packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/WhatsNew/WhatsNewContent/ExchangeByBlockchain.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/WhatsNew/WhatsNewContent/__snapshots__/ExchangeByBlockchain.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/SwapGetStarted/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): copy fixes

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/reducers.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.spec.js, packages/blockchain-wallet-v4/src/network/api/profile/index.js
- Adds ability to pull and store new query parameters from referral URLs
- Updates calls to backend with these new paramters
- Feature
=> Feat(Sunriver campaign updates)

packages/blockchain-wallet-v4-frontend/src/data/modules/addressesBch/sagas.spec.js, packages/blockchain-wallet-v4/data/index.js, packages/blockchain-wallet-v4/data/tx.bch.json, packages/blockchain-wallet-v4/data/wallet.v3.json, packages/blockchain-wallet-v4/src/redux/common/bch/selectors.js, packages/blockchain-wallet-v4/src/redux/common/btc/selectors.js, packages/blockchain-wallet-v4/src/redux/common/eth/selectors.js, packages/blockchain-wallet-v4/src/redux/kvStore/bch/selectors.spec.js, packages/blockchain-wallet-v4/src/transactions/bch.js, packages/blockchain-wallet-v4/src/transactions/bch.spec.js, packages/blockchain-wallet-v4/src/transactions/index.js
Separate btc/bch tx processing
Filter dust txs from bch txs
- Upgrades
Main change here: https://github.com/blockchain/blockchain-wallet-v4-frontend/compare/fix/bch-dust-io?expand=1#diff-4996432c9317b11c86ce57d2b00a5f08R274
=> fix(BCH - Split): filter dust tx

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/model.js, packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/SunRiverLinkError/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/index.js, packages/blockchain-wallet-v4-frontend/src/modals/index.js, packages/blockchain-wallet-v4/src/network/api/http.js, packages/blockchain-wallet-v4/src/network/api/profile/index.js
=> Feat(Add invalid sun river link support)

packages/blockchain-wallet-v4-frontend/src/data/components/onfido/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/onfido/sagas.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(KYC): redirecting to exchange after KYC success

README.md
Fix an incorrect link in the README.
- Bug Fix
1.  Click on the link named `React Developer Tools` in the README and verify that it brings you to the React Developer Tools.
=> fix(README.md): Fix incorrect link to React Developer Tools.

packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/AuthenticityStep/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Create/AcceptTerms.js, packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Link/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Sfox/SfoxExchangeData/Verify/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/OrderReview.js, packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/SfoxCheckout/Content/template.success.js
grammar correction for lockbox, 946
- Bug Fix
=> fix: copy changes for lockbox and sfox

packages/blockchain-wallet-v4-frontend/src/components/OrderStatus/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeResults/__snapshots__/ExchangeResults.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeResults/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): removed refund links for trades

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/goals/actions.spec.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/goals/selectors.js, packages/blockchain-wallet-v4-frontend/src/data/goals/selectors.spec.js
- Adds unit tests for everything goals related 
- Tests
N/A
=> Test(Goals/campaigns functionality)

packages/blockchain-info-components/src/Form/SelectInput/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(SelectInput) prevented calling onBlur with event that has no value

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/template.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(KYC): fixed email verfied validation

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeResults/__snapshots__/ExchangeResults.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeResults/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(ExchangeHistory): fixed support link

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Menu/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(exchange menu styling bug)

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> style(Account): change text weight

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Exchange.spec.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeContainer/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/__snapshots__/Exchange.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/index.js
=> fix(Tiers): Profile fetch

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/services.js, packages/blockchain-wallet-v4-frontend/src/data/components/onfido/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/onfido/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/veriff/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/veriff/sagas.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> More tiers related hotfixes

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Veriff/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Veriff): fixed disabled scroll and iframe late removal

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Footer/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/LimitInfo/LimitInfo.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/VerificationInfo/VerificationInfo.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/GetStarted/StatusBar/Statuses/GetStarted.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/GetStarted/StatusBar/Statuses/__snapshots__/GetStarted.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/app.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Profile): renamed account=>profile, updated support link

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> feat(Swap): renewing limits every 30 seconds

packages/blockchain-wallet-v4-frontend/src/components/IdentityVerification/TierCard/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/IdentityVerification/TierCard/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeProfile/IdentityVerification/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> style(Profile): layout fixes

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/template.success.js
=> fix(Theme): swap amount background-color

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/MinMaxButtons/MinMaxButtons.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/SubmitButton/SubmitButton.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> style(Swap): Fix UI when user is rejected

packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/SecondStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/ShowXlmPrivateKey/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): Catch prompt for second password cancel in xlm priv key

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(KYC): sync email prior to saving personal data

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.spec.js
1960
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(OTL): fixed verification starting after entering by otl

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js, packages/blockchain-wallet-v4/src/signer/bch.js
1894
- Upgrades
Send bch from lockbox
=> feat(BCH): Add ability to include unsigned inputs to ledgerjs

packages/blockchain-wallet-v4-frontend/src/scenes/app.js
- If a user is authenticated and hits an unregistered route, redirect to home page instead of login
Feature
=> Feat(Fallback to home for hits on unregistered routes if user is authenticated)

packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/actions.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Bsv/SendBsv/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Wallets/template.js
1979
- Bug Fix
Click send from account at > 0 index
=> fix(BSV): Populate from with selected account

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js
- Adds the note tooltip to BSV send modal
- Bug Fix
- Send BSV and hover tooltip
=> Feat(Add BSV send note tooltip)

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Veriff/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Veriff): allowed microphone on iframe

README.md, setup.sh
- Move dep install logic to shell script
=> Add setup.sh file

packages/blockchain-wallet-v4-frontend/src/components/Lockbox/AppManager/index.js, packages/blockchain-wallet-v4-frontend/src/components/Lockbox/AppManager/template.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/DeviceSelectStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/DeviceSelectStep/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/model.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Transactions/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Onboard/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/index.js, packages/blockchain-wallet-v4-frontend/src/services/LockboxService/utils.js
- Adds missing error messaging during app updates
- Fixes Lockbox transaction list scrolling
- Fixes issue where existing Ledger device setup flow wasn't detecting the BTC app properly
- Adds restore device support link
- Fixes issue where clicking the Lockbox sidenav link and then clicking it again resulted in an empty page/unknown route
- Bug Fix
=> Fix(Small Lockbox bugs)

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
- Adds banner warning users that device connection is required when sending funds from Lockbox
Feature
- Send from Lockbox
=> feat(Lockbox Send): Warn users for device connection

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/index.js
=> Fix(Add overflow scroll to Security Center)

packages/blockchain-wallet-v4-frontend/src/modals/Transactions/TransactionReport/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Transactions/TransactionReport/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Transactions/TransactionReport/template.js
- Makes report names user friendly `{coin}_{startDate}_{endDate}.csv`
- Bug Fix
- Generate a coin tx report
=> Fix(Tx Reports): User friendly file names

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/actions.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/NoAccountTemplate/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeContainer/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Content/Empty/CoinWelcome/template.js
From now one when you leave and return to swap your latest from/to/volume/fix amount is not saved&restored.
Exception is coming through links which specify certain pairs like the ones on the txlist pages.
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> feat(Swap): preserving state for swap

packages/blockchain-wallet-v4-frontend/src/components/Form/PhoneNumberBox/__snapshots__/index.spec.js.snap
Forgot to update this previously :(
=> Fix(Snapshot tests in dev)

packages/blockchain-info-components/src/Modals/Modal.js, packages/blockchain-wallet-v4-frontend/src/modals/Generic/Support/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Generic/Support/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Generic/Support/index.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Generic/index.js, packages/blockchain-wallet-v4-frontend/src/modals/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Menu/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Menu/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/Menu/index.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> feat(Swap): added support modal to swap menu

packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/FiatAtTime/selectors.js
Value is an int - no need to remove commas
- Bug Fix
=> Fix FiatAtTime

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Goals): bsv modal hasSeen flag is now set only when modal gets shown

packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Confirmations/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> Feat(Use new BCH explorer)

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Goals): not freezing bsv goals if metadata call fails

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> KYC(Update tier 2 tooltip CTA)

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxXlmAddresses/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/RequestXlm/template.success.js, packages/blockchain-wallet-v4/src/redux/common/xlm/selectors.js, packages/blockchain-wallet-v4/src/redux/data/xlm/selectors.js, packages/blockchain-wallet-v4/src/redux/data/xlm/selectors.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(XLM): fixed 0 xlm sum balances

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.spec.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Goals): removed auto airdrop for tier 2 goals

package.json, packages/blockchain-info-components/package.json, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/Confirmations/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Public/Footer/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/layouts/Public/Footer/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/FaqContent/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UsedAddresses/Table/template.js, packages/blockchain-wallet-v4/package.json
- Update various linkouts to use .com instead of .info
- Feature
- Bug Fix
=> Feat(Migrate remaining links to .com)

packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/layouts/Public/Footer/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/layouts/Public/Footer/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/RequestBch/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/RequestEth/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Transactions/TransactionReport/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/RequestXlm/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/model.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/Transactions/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bsv/index.js
- Tons of small bug fixes (see commits for more info)
- Bug Fix
=> Fix(Lockbox bugs)

packages/blockchain-wallet-v4-frontend/src/components/Lockbox/AppManager/index.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/actions.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/CustomizeStep/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Menu/DeviceTitle/index.js, packages/blockchain-wallet-v4-frontend/src/services/LockboxService/apps.js
- Ensure all app updates have a 60 second timeout to allow for user interaction and install to complete
- Simplify app manager init saga to just always poll for device type
- Bug Fix
=> Fix(Lockbox app install timeouts)

packages/blockchain-wallet-v4-frontend/src/components/Announcements/Service/template.js
- Testnet app was down for a small time because app errored due to a missing `actions` obj. 
- Bug Fix
=> Fix(Flexible Announcements config)

packages/blockchain-info-components/README.md, packages/blockchain-info-components/package.json, packages/blockchain-info-components/src/Modals/Modal.js, packages/blockchain-wallet-v4-frontend/package.json
- release includes small header and footer link changes (#1421 via @blockfred)
=> chore(Components v0.32 release)

packages/blockchain-info-components/src/Footer/index.js, packages/blockchain-info-components/src/Navigation/index.js
Update Header/Footer links
- Feature
Verify header/footer links
=> feat(header/footer): more link updates

packages/blockchain-wallet-v4-frontend/src/scenes/BuySell/CoinifyCheckout/Content/QuoteInputTemplate.js
- Updates copy for when user attempts to send minimum but doesnt have enough funds
- Bug Fix
=> Fix(Copy update for sending minimum)

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js, packages/blockchain-wallet-v4-frontend/src/providers/AnalyticsTracker/index.js
- Only render analytics in wallet layout and init session inside of component
- Bug Fix
=> Fix(Analytics iframe render)

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.js
Testing to see if this fixes postMessaging in Chrome browser.
=> Fix(Matomo Chrome CORS postMessage issue)

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(KYC): removed email uniqueness check before kyc

packages/blockchain-wallet-v4/src/network/api/misc/index.js
2121
- Bug Fix
Remind yourself what your guid is
=> fix(Captcha): set explicit responseType for kaptcha endpoint

packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/validation.js, packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.js
2091, 2133
- Bug Fix
2091: Fix maximum link
2133: fallback eth fees
=> Fix/eth fallback fees, maximum link fix

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeConfirm/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/SubmitButton/SubmitButton.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/template.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): fixed swap copies

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Page/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/index.js, packages/blockchain-wallet-v4/src/redux/data/xlm/reducers.js, packages/blockchain-wallet-v4/src/redux/data/xlm/selectors.js
2097
- Bug Fix
1. login
2. go to hardware wallet
3. see overflow: initial is not added to parent
=> fix(Scrolling): Fix scrolling issue caused by joyride lib

packages/blockchain-wallet-v4-frontend/src/components/ResizeableFontInputHOC/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): input resized on mount in case initial value is not 0

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): resubscribing and updating fees in swap during init

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js
=> fix(Tiers): Copy for gold level completion

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/SwapGetStarted/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): getstarted modal copy updated

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/SunRiverLinkError/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Sunriver): airdrop error messages for different errors

packages/blockchain-wallet-v4-frontend/src/data/components/swapGetStarted/sagas.js
=> fix(SwapGetStarted): Close modal before opening idv

packages/blockchain-wallet-v4-frontend/src/components/Alerts/template.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/SecondStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/index.js
- Adds custom success/failure setup messages based on device type
- Fix modal unable to close on select device step
- fix BCH send messaging copy
- Feature
- Bug Fix
=> Fix(Lockbox device name messaging)

packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.spec.js
2160
- Bug Fix
Send from imported btc, bch, bsv addr
=> fix(BTC, BCH, BSV): property of undefined failure

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js, packages/blockchain-wallet-v4/src/network/api/trades/index.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): fixed failure-reason endpoint application type

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/selectors.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): selecting previous accounts not from form but from app state

packages/blockchain-info-components/src/Toasts/Toast.js, packages/blockchain-info-components/src/Toasts/__snapshots__/Toast.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/FiatAtTime/template.success.js, packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeResults/__snapshots__/ExchangeResults.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeResults/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/XlmReserveLearn/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeConfirm/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/ComplementaryAmount/ComplementaryAmount.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/ComplementaryAmount/__snapshots__/ComplementaryAmount.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/CurrencySelect/CurrencySelect.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/CurrencySelect/__snapshots__/CurrencySelct.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Error/Error.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Error/MaximumAmountLink/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Error/MinimumAmountLink/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Error/validationMessages.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/MinMaxButtons/MinMaxButtons.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/SubmitButton/SubmitButton.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Summary/Summary.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Summary/__snapshots__/Summary.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/TradeItem/template.js
- Adds e2e tags for swap/exchange
- Adds previously missed e2e related to transactions and messaging
- Fixes a few CSS syntax issues
- Fixes misspelling of `minimum` on exchange order create page
- Feature
=> Tests(Add Swap e2e tags)

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/WalletPassword/Settings/template.js
- Updates non-spendable addresses copy
- show BTC tx confirmation time msg based on selected fee vs reg/priority fees
- fixes spacing around password form errors
- fixes lockbox routing to go to next remaining device dashboard (if applicable) after a device is deleted
- updates tests
- Bug Fix
=> Fix(Various old outstanding issues)

package.json, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBsv/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.spec.js, packages/blockchain-wallet-v4/src/network/api/trades/index.js
- Also bump dev version to 4.10
- Chore
=> Chore(merge 4.9.7 to dev)

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/template.loading.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/template.loading.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): showing loader until data is loaded for all coins

packages/blockchain-wallet-v4/src/redux/data/bch/reducers.js, packages/blockchain-wallet-v4/src/redux/data/bsv/reducers.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(BCH): fixed errors during BCH/BSV error processing

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
- accounts for new action types due to the redux dev tools refactor
- Bug Fix
=> Fix(Login/Nabu auth saga)

packages/blockchain-wallet-v4-frontend/src/components/TransactionListItem/template.js
moving data-e2e tag to the proper element
Fix
=> moving data-e2e tag to the proper element

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js
=> Sunriver copy change

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UnusedAddresses/index.js
moved existing data-e2e tag to the proper element
fix
=> moved existing data-e2e tag to the proper element

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/PasswordStretching/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/SecondPasswordWallet/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/SecondPasswordWallet/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/WalletPassword/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/Menu/index.js
new data-e2e tags for Security Center tab
- Feature
=> new data-e2e tags for Security Center tab

packages/blockchain-wallet-v4-frontend/src/components/Form/NumberBox/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/AirdropReminder/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CoinifyUpgrade/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeForAirdrop/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Settings/SecondPassword/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/PasswordStretching/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/SecondPasswordWallet/Settings/template.js
New data-e2e tags for Security Center - Advanced tab
- Feature
=> new data-e2e tags for Security Center - Advanced tab

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js
2159
- Bug Fix
1. finish a trade and see the order details modal
=> fix(Order Flow): show results modal after confirmation

packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/SecondStep/index.js
=> fix(Eth): send submitting

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.spec.js
=> Feat(Hash user analytics)

packages/blockchain-wallet-v4-frontend/src/components/Form/NumberBox/index.js
data-e2e tag for NumberBox error
- Feature
=> added data-e2e tag for NumberBox error

packages/blockchain-wallet-v4-frontend/src/providers/ErrorBoundaryProvider/template.js
new data-e2e tag for Continue button on Oops error modal. 
- Feature
=> new data-e2e tag for Continue button on Oops error modal

packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.js
Allow XLM send amount update to throw to correctly display error in success template
- Bug Fix
1. enter amount too high error
=> fix(XLM): allow xlm amount update to throw

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js
Same as https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/1513
=> fix(Eth): dont throw in eth payment update

packages/blockchain-wallet-v4/src/network/api/bch/index.js, packages/blockchain-wallet-v4/src/network/api/bsv/index.js, packages/blockchain-wallet-v4/src/network/api/btc/index.js
- Use POST instead of GET to allow for requesting larger amounts of data
- Bug Fix
=> Fix(POST to api instead of GET for unpsents)

packages/blockchain-wallet-v4-frontend/src/components/Form/EmailVerification/EmailVerification.js, packages/blockchain-wallet-v4-frontend/src/components/Form/EmailVerification/__snapshots__/EmailVerification.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js, packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/IdentityVerification.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/index.js
- Adds initial analytics to KYC onboarding
- Feature
=> Feat(Add KYC analytics)

packages/blockchain-info-components/src/Form/RadioButtonInput.js, packages/blockchain-info-components/src/Form/__snapshots__/RadioButtonInput.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Btc/AddBtcWallet/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/ImportBtcAddress/ImportExternalBtcAddress/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/ImportBtcAddress/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/VerifyMessage/index.js, packages/blockchain-wallet-v4-frontend/src/modals/SignMessage/FirstStep/template.js, packages/blockchain-wallet-v4-frontend/src/modals/SignMessage/SecondStep/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/AddressRow.js
new data-e2e tags for input bitcoin addresses functionality
- Feature
=> New data e2e tags

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UnusedAddresses/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UsedAddresses/Table/template.js
New data-e2e tags for used and unused btc addresses links
- Feature
=> new data-e2e tags for used and unused btc addresses

packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js
- Add unique event names so there wont be collisions with funnels
- Feature
=> Feat(Add unique event names for funnels)

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/AddressRow.js
new data-e2e tags for imported btc addresses names
- Feature
=> new data-e2e tags for imported btc addresses names

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/template.js
=> fix(Personal): required flags for certain fields

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/AddressRow.js
new data-e2e tag for Non-Spendable banner
- Feature
=> new data-e2e tag for Non-Spendable banner

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/FaqContent/index.js
Added locbox FAQ, WEB4-2000
Changed size of links to look more like text
- Feature
=> feat: added lockbox faq

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Error/validationMessages.js
removed extra character from "Amount is above maximum message"
- Bug Fix (WEB4-2207)
=> removed extra character from Amount is above maximum message

packages/blockchain-wallet-v4-frontend/src/modals/Btc/ShowBtcPrivateKey/template.js
New data-e2e tags for BTC Private Key modal
- Feature
=> new data-e2e tags for BTC Private Key modal

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/AirdropReminder/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/SwapGetStarted/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeForAirdrop/index.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validators.js
2299
Only displays modals once so they aren't so annoying. Fixes 2299
- Bug Fix
=> Onboarding Modal Fixes

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Swap): prevented swap from requesting undefined pairs

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/RatesBox/RatesBox.js
=> fix: removed $ symbol from coin and changed balance copy

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/CoinPerformance/template.success.js
2297, % symbol on charts
- Bug Fix
=> fix: moved % symbol on charts

packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js
new data-e2e tags for AddressButton
- Feature
=> new data-e2e tags for AddressButton

packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js, packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/template.js
- Feature
- Bug Fix
- CI/CD
- Upgrades
=> fix(Matomo): on personal field blur log event

package.json, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.js
Swap fee error fix.
TODO: remove calclulateProvisionalPayment
=> fix(Swap): dont use calculateEffectiveBalance for fee

packages/blockchain-wallet-v4-frontend/src/components/Form/CreatableInputField/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/validation.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/validationMessages.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validationMessages.js
data-e2e related changes and new tags
- Feature
- Bug Fix
=> data-e2e related changes and new tags

packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/LowBalanceWarning/index.js
data-e2e tags for Running Low messages
- Feature
=> data-e2e tags for Running Low messages

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.js
- refetch user data after eth airdrop modal is shown
- Bug Fix
=> Fix(Refetch user after ETH airdrop)

packages/blockchain-info-components/src/Form/CreatableInput/index.js
=> fix(Send): do not clear to field when user goes back to FirstStep

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/index.js
Templates still there, just removed it from security center index, 2390
- Bug Fix
=> fix: removed activity logging from security center index

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/Faq/FaqContent/index.js, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/__snapshots__/USDPax.spec.js.snap
FAQ: 2280 and Pax -> PAX
what's new test
- Bug Fix
=> fix: changed pax to PAX in faq

packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/USDPax.js, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/USDPax.spec.js, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/__snapshots__/USDPax.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/index.js
Pax to What's New, 2281
- Feature
=> feat: add pax to whats new

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.js
@schnogz does this make sense? Request from data team
=> feat(Matomo): if user id, set for matomo

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js
=> Fix(ETH/ERC20 send max)

packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/SecondStep/index.js
@schnogz do you remember why we were doing this in the first place?
=> fix(XLM): do not clear send form on back

packages/blockchain-wallet-v4/src/exchange/currencies/PAX.js, packages/blockchain-wallet-v4/src/exchange/index.js
=> Feat(Round PAX display to 2 decimals)

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/Balances/Lockbox.js, packages/blockchain-wallet-v4-frontend/src/components/Balances/__snapshots__/Lockbox.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/modals/Bch/RequestBch/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/RequestEth/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/RequestXlm/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Menu/CurrencyList/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Menu/DeviceTitle/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Settings/AddDevice/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Settings/AddDevice/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Settings/UpdateDevice/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Settings/UpdateDevice/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Onboard/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.js, yarn.lock
- Upgrades Bowser to latest version
- Enables Brave, Firefox and Opera browsers for Lockbox
- Feature
- Upgrades
=> Feat(Update supported Lockbox browsers and Bowser)

packages/blockchain-wallet-v4-frontend/webpack.debug.js
- Fixes `yarn debug:prod` command
=> CI(Remove warnings flag from compress)

packages/blockchain-info-components/src/Menus/TabMenu/TabMenuItem.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Menu/index.js
- Small style update for menu
- Bug Fix
=> Fix(Menu display on Address Manage page)

packages/blockchain-wallet-v4-frontend/webpack.config.dev.js, packages/blockchain-wallet-v4-frontend/webpack.debug.js
- Now replaces the correct wallet options path for BTC config
- Bug Fix
=> Fix(Testnet Webpack config)

packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.js, packages/blockchain-wallet-v4/src/signer/eth.js
- Pass in contract address to `signErc20` method instead of hardcoding
- Refactor
=> Fix(Remove hardcoding of ERC20 contract address)

packages/blockchain-info-components/src/Form/PasswordInput.js, packages/blockchain-info-components/src/Form/TextInput.js, packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Recover/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Reset2FA/FirstStep/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/WalletRecoveryPhrase/RecordBackupPhrase/ThirdStep/template.js
- Disables spellcheck on all password, guid and mnemonic entry fields
- Feature
=> Feat(Disable HTML5 spellcheck on sensitive fields)

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Footer/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/selectors.js, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.js
- Adds bitcoin.com url to wallet options
- Feature
=> Feat(Add ads url to wallet options)

packages/blockchain-wallet-v4-frontend/src/data/components/exchangeHistory/model.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/TradeItem/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/TradeItem/template.js
- Fixes issue where we were double parsing and formatting dates which caused issues in certain languages due to recent locale bundling changes
- Bug Fix
=> Fix(Double date parsing/formatting Swap history)

packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.js
https://blockchain.atlassian.net/browse/WEB4-2655
=> fix(v2 Upgrade): if no invited flags exist default invite to true

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js
check if userTiers exists on userData before current tier check
- Bug Fix
=> fix(Upgrade for Airdrop Goal)

packages/blockchain-wallet-v4-frontend/src/providers/TranslationsProvider/index.js
- remove `componentDidMount` from `TranslationsProvider` to fix double render issue
- Bug Fix
=> Fix(Email verification flows)

packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js
https://blockchain.atlassian.net/browse/WEB4-2660
=> fix(Send BTC): if deeplink includes address update payment

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmailToken/index.js
Passes the `context` param from the email verification link to the mobile deep link.
- Feature
=> feat(EmailVerification): Pass verification context to mobile deep link

config/mocks/wallet-options-v4.json
- Ensure local wallet options matches those that are deployed
=> Fix(BSV wallet options) 

packages/blockchain-wallet-v4-frontend/src/components/Balances/Lockbox.js, packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/model.js, packages/blockchain-wallet-v4-frontend/src/data/components/model.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/RequestBch/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/RequestEth/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/RequestXlm/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Menu/CurrencyList/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Menu/DeviceTitle/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Onboard/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.js
- Fix for #1723 
- Creates a Lockbox supported browser model
- Feature
- Sign in works with Vivaldi
=> Feat(Allow Vivaldi browser)

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/AirdropSuccess/index.js
=> feat(Update social share copy)

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmailToken/index.js
Checks the `context` param passed via the verify email link against a list of valid values.
- Feature
Any values assigned to `context` in the verify email link besides the ones in the whitelist should not be applied to the final mobile deep link.
=> feat(LinkContext): check that link context value is in whitelist

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.js, packages/blockchain-wallet-v4/src/redux/common/bch/selectors.js
=> fix(Linking): share addresses when linkFrom, share BCH

packages/blockchain-info-components/src/Colors/DarkMode.js, packages/blockchain-info-components/src/Colors/Default.js, packages/blockchain-wallet-v4-frontend/src/scenes/LinkAccount/index.js
=> fix(pit-linked-login): changed color, font-weight, and added margin

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.js, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.js
=> feat(pit): get invited status and hide/show banners

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkToPitAccount/template.notasked.js, packages/blockchain-wallet-v4-frontend/src/scenes/LinkAccount/index.js
=> fix(Linking): check existence of settings

packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmailToken/index.js
Picks deeplinking commits from development branch.
=> Deeplinking

packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.js
=> fix(Link): check if user is linked before fetching pit accounts

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Submitted/index.js
=> Fix(Update social share link after KYC)

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js
WEB4-2721
Removed airdrop message from profile page.
=> remove(profile-airdrop-message): removed airdrop message in profile

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js
=> fix(Bitpay): prevent send modal if bitpay invoice already expired

packages/blockchain-wallet-v4-frontend/src/data/components/sagaRegister.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagaRegister.js, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.js, packages/blockchain-wallet-v4/src/network/api/bitpay/index.js, packages/blockchain-wallet-v4/src/network/api/index.js, packages/blockchain-wallet-v4/src/signer/btc.js
=> fix(Bitpay): send appropriate headers and add verification check

packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js
Changed recipient to Sender on the 2nd tour description
=> Changed recipient to Sender

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/GetStarted/index.js
Changed USDp to USD PAX in swap intro caoursel (last one)
=> Changed USDp to USD PAX

packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SunRiverWelcome/index.js
Fix position of sunriver modal. Centered the contents.
=> centered content

packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validationMessages.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validators.js, packages/blockchain-wallet-v4/src/network/api/apiAuthorize.js
=> Philip/web 66 pit deposits invalid {coin} address when

packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.js, packages/blockchain-wallet-v4/src/utils/xlm.js
=> feat(Pit link): handle xlm depo addrs from PIT

packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/model.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validators.js
=> refactor(Pit link): move const to model

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.js
=> Fix(Lockbox): send ETH from wallet to Lockbox

packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.js, packages/blockchain-wallet-v4-frontend/src/components/Alerts/template.js, packages/blockchain-wallet-v4-frontend/src/data/alerts/actions.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/services/AlertService/index.js
Added alert for accounts that whitelist IPs.
=> fix(ip-restriction-alert): added alert for accounts that restricts ip

packages/blockchain-wallet-v4-frontend/src/data/components/lockbox/sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/Lockbox/Dashboard/UpdateRequiredNotice/index.js
=> Fix(Dismissible Lockbox software download)

packages/blockchain-info-components/src/Colors/DarkMode.js, packages/blockchain-info-components/src/Colors/Default.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js
=> Tour tooltip now scales in.

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.js
Reverts blockchain/blockchain-wallet-v4-frontend#1827
=> Revert "fix(Nabu): link user walletInfo with nabu on login"

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/GetStarted/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js
=> fix(wallet-tour-swap-carousel-wording)

packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.js
=> Fix(Lockbox): Correctly parse addr when sending xlm between accounts

packages/blockchain-wallet-v4-frontend/src/modals/Eth/RequestEth/selectors.js
default ERC20 token request to wallet address, never lockbox
Closes WEB-76
=> Fix(Lockbox): ERC20 request modal

packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-info-components/src/Colors/DarkMode.js, packages/blockchain-info-components/src/Colors/Default.js, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkToPitAccount/template.notasked.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/ThePitBanner/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ThePit/template.js
=> fix(wallet-connect)

packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js
=> fix(gold-level-tooltip): added 'extended to your region'

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/WalletTour/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js
=> Wallet tour changes

packages/blockchain-wallet-v4/src/redux/kvStore/lockbox/reducers.js
- ensure xlm node exists upon device rename
- Closes WEB-92
=> fix(lockbox): Device rename 

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.js
=> Feat(pit): Split banner and sidenav display logic

packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js
Added autofilled prop to 1st step send btc modal
Test through the following link: https://www.blockchain.com/btc/payment_request?address=1NxaBCFQwejSZbQfWcYNwgqML5wWoE3rK4&amount=0.0002
=> WEB4-2711 Payments | Payment request link broken

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.js
1. centered pulsing for callout_text
2. pulse fades out at 100%
=> Fixed Pulsing

packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Submitted/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/index.js
=> Feat(KYC): Update final success page copy

packages/blockchain-wallet-v4-frontend/src/components/IdentityVerification/TierCard/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js
=> Fix(Profile page: dont show KYC modal if user is already verified)

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.js
=> fix(Matomo): ab test pit fix

packages/blockchain-wallet-v4-frontend/src/middleware/matomoMiddleware.js
=> fix(Matomo): wrap in try catch to prevent random JSON.stringify errors

packages/blockchain-info-components/src/Colors/DarkMode.js, packages/blockchain-info-components/src/Colors/Default.js, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/template.success.js
=> fix(login-approved-styling)

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js
=> Code(make function param more readable)

packages/blockchain-wallet-v4-frontend/src/components/QRCodeWrapper/index.js
=> fix(qr-code-dark-mode)

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js
=> fix(pit-connected-info)

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js
=> fix(pit-connected-info-2)

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/selectors.js
=> feat(PIT): check if user is eligible for sidenav

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ThePit/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/ThePit/template.js
=> feat(The PIT): everyones invited❕

packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js
=> fix(wallet-tour-data-e2e)

packages/blockchain-wallet-v4-frontend/src/data/modules/addressesBch/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/wallet/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/AddBtcWallet/template.js, packages/blockchain-wallet-v4-frontend/src/modals/Generic/PromptInput/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/Wallets/index.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validationMessages.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validators.js, packages/blockchain-wallet-v4-frontend/src/services/SagaService/index.js
=> fix(duplicate-wallet-labels)

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Balance/WalletBalance/Balance/template.success.js
=> fix(balance-dropdown)

packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js
per QA
Added thepit to datae2e
=> fix(wallet-tour-pit-data-e2e)

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/Menu/template.js
=> fix(transaction-dropdown)

packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/selectors.js
=> Hotfix(Add linked wallet linkout analytics)

packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.js, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/WalletTour.js
FUCK YA. 
e2e Tags for wallet intro tour.
=> fix: add e2e to wallet tour elements

packages/blockchain-wallet-v4-frontend/src/modals/Btc/RequestBtc/template.success.js
=> fix(data-e2e-request-modal)

packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Balances/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Balances/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Balances/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Footer/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Footer/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Footer/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/TimeFilters/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/TimeFilters/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/TimeFilters/index.spec.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/TimeFilters/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/TimeFilters/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/selectors.js
=> feat/(price-chart-cta): added price chart button cta

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js
=> Hotfix(sidenav): rename PIT to PIT Exchange

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/ThePitLink/index.js
=> Hotfix(Sidenav): Remove "NEW" tag

packages/blockchain-wallet-v4/src/network/api/wallet/index.js
Closes WEB4-1710 which was requested by Matt.  Updated endpoint is live in prod with proper fallbacks.
=> feat(guid reminder): call new method name to get wallet guid email

packages/blockchain-wallet-v4-frontend/src/scenes/LinkAccount/index.js
=> fix(wallet-connect-log-in)

packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js
=> fix(price-chart-cta)

packages/blockchain-wallet-v4-frontend/src/services/CoinifyService/index.js
Added undefined handling for min/max usd bank/card calculations to avoid NaN limits.
WEB-172
=> fix(coinify usd limit)

packages/blockchain-wallet-v4-frontend/src/services/CoinifyService/index.js
Fixing min calculation that was causing errors in coinify test cases.
See #WEB-172 for testing steps.
=> fix(coinify min calculation)

.circleci/config.yml
=> chore(Circle): update yarn v

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
Quick fix to add guid sub in websocket
1. create new wallet
2. click email verif link
3. look to see if email verification status updates on the fly
=> fix(adding guid subscribe to get email verification updates)

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Footer/template.js
=> fix(price-chart-cta-styling)

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/services.js
=> fix(price-chart-height)

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/xlm/sagas.js
fixes to xlm websocket handler
send or receive transaction while viewing xlm txs page
=> fix(xlm txs update)

packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.js
https://gyazo.com/d1f93f28415592057d5b4915c8160aac
=> fix(PIT): wait for user data before fetching linked pit account

packages/blockchain-wallet-v4-frontend/src/components/SiftScience/index.js
=> fix(Sift): new sift endpoint for wallet-helper

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeForAirdrop/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/BlockstackBanner/index.js
=> fix(airdrop): load correct image in fallback for banner

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/CurrencySelect/selectors.js
=> fix(swap-select-box)

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Bch/Wallets/template.js
=> fix(bch-default-archived)

CODEOWNERS
=> chore(update codeowners)

packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Submitted/index.js
=> fix(Airdrop): submitted copy

packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/model.js, packages/blockchain-wallet-v4-frontend/src/scenes/app.js
https://blockchain.atlassian.net/browse/FWLT-98
=> feat(Airdrop): add tour card

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.spec.js
=> fix(captcha): refresh captcha if entered wrong

packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/AirdropInfo/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.js
=> feat(Airdrops): add links and regulatory text

packages/blockchain-info-components/src/Modals/__snapshots__/ModalHeader.spec.js.snap, packages/blockchain-info-components/src/Text/__snapshots__/Text.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Announcements/Static/template.email.js
Fixes https://blockchain.atlassian.net/browse/FWLT-123
=> fix(email banner): ensure long emails are always hidden

packages/blockchain-wallet-v4-frontend/src/layouts/Public/AirdropCallout/index.js
=> fix(Airdrop): if isLinkFromPitAccount dont show banner

packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/index.js, packages/blockchain-wallet-v4/src/network/api/apiAuthorize.js
https://blockchain.atlassian.net/browse/FWLT-128
=> fix(Airdrops): improve error when user has no email

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/WalletPassword/Settings/template.js
=> fix(security-center-change-password) FWLT-102

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/TrayRight/index.js
=> Fix/right tray overlap (FWLT-106)

CODEOWNERS, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js
=> Fix(airdrops): update under review copy

packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/PastAirdrops/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.js
=> fix(Airdrops): dont break for non nabu users

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.js
Will create a nabu user if none exists on login. May have unintended consequences.
=> fix(User): create nabu user if none exists

packages/blockchain-wallet-v4-frontend/src/components/QRReader/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Verify/index.js, packages/blockchain-wallet-v4-frontend/src/utils/helpers.js
=> Fix/has webcam (FWLT-17)

packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.js
=> feat(Airdrop): handling ended campaigns in stx card

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/TransferEth/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/TransferEth/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/TransferEth/template.js
Legacy balance vs fee logic didnt work since `BigInt` wasnt used therefore the modal never was shown.  Also updated variable names and some modal styling.
=> Fix(ETH): Legacy account sweep

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js, packages/blockchain-wallet-v4/src/utils/eth.js
User can now scan BitPay QRcode for BTC and BCH
=> Feat/read-bitpay-qrcode (FWLT-147)

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/selectors.ts
typesafe selectors file for identityVerification
=> feat(identityVerification): typescript for selectors

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/types.ts
=> feat(Profile): profile reducers and actions

packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/PastAirdrops/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.tsx
=> Feat(Airdrop): Add STX airdrop completion info card

packages/blockchain-wallet-v4-frontend/src/middleware/matomoMiddleware.js
=> fix(Matomo): stop logging err msgs for now

packages/blockchain-wallet-v4-frontend/src/modals/Settings/AutoDisconnection/template.js
FWLT-179, auto-logout modal restyle.
=> feat(Settings): restyled auto-logout modal

packages/blockchain-info-components/.storybook/webpack.config.js, packages/blockchain-info-components/src/Carousels/Carousel/template.js, packages/blockchain-info-components/src/Dropdowns/ComponentDropdown/template.js, packages/blockchain-info-components/src/Dropdowns/SimpleDropdown/template.js, packages/blockchain-info-components/src/Footer/index.js, packages/blockchain-info-components/src/Gauges/SecurityGauge.js, packages/blockchain-info-components/src/Links/Link.js, packages/blockchain-info-components/src/Loaders/FlatLoader.js, packages/blockchain-info-components/src/Loaders/FlatLoader2.js, packages/blockchain-info-components/src/Loaders/HeartbeatLoader.js, packages/blockchain-info-components/src/Navigation/Button/index.js, packages/blockchain-info-components/src/Navigation/index.js, packages/blockchain-info-components/src/Normalize.js, packages/blockchain-info-components/src/Themes/index.js, packages/blockchain-info-components/stories/chapters/colors.js, packages/blockchain-info-components/stories/chapters/icons.js, packages/blockchain-info-components/stories/components/layout.js
=> fix(Storybook): ts fixes for storybook

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/EmailAddress/template.success.js
=> fix(Automation): e2e tag for change your email in security center

packages/blockchain-wallet-v4-frontend/src/scenes/ExchangeHistory/List/template.js
FWLT-185, swap order history table spacing.
=> fix(ExchangeOrderHistory): margin-bottom fix

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/EmailAddress/ChangeEmailSteps/index.js
=> feat(Automation): data e2e change email button

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js
=> Feat(Airdrop) Remove active tag from airdrop menu

package.json, packages/blockchain-wallet-v4-frontend/src/components/IdentityVerification/TierCard/index.tsx, yarn.lock
=> fix(Tier cards): bindActionCreator fix

.eslintrc, package.json, packages/blockchain-wallet-v4-frontend/src/components/Form/FormLabel/__snapshots__/index.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/AirdropInfo/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/PastAirdrops/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/template.success.tsx
Reverts blockchain/blockchain-wallet-v4-frontend#2060
=> Revert "fix(User): create nabu user if none exists"

packages/blockchain-info-components/src/Dropdowns/ComponentDropdown/template.js, packages/blockchain-info-components/src/Menus/TabMenu/TabMenuItem.js, packages/blockchain-wallet-v4-frontend/src/components/Announcements/Static/index.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/WhatsNewIcon/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/ExchangeBanner/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/TransactionFilters/template.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/index.tsx
Styling fixes related to new header, popover balances, exchange ad, coinview dropdown, coinview tab menu item
=> Thianh change

packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/BorrowPax/index.tsx
=> fix(borrow): added zendesk support article to learn more link

packages/blockchain-wallet-v4-frontend/src/data/components/borrow/model.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowDetails/Info/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowDetails/Summary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/BorrowHistory/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/borrow/types.ts
=> fix(money type): use currency and amount

packages/blockchain-wallet-v4-frontend/src/data/components/borrow/model.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowDetails/CollateralWarning/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowDetails/Info/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowDetails/Summary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/BorrowHistory/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/BorrowHistory/template.success.tsx
=> fix(borrow): handle base amounts

packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-wallet-v4-frontend/src/layouts/Public/Header/LoginOrCreate/index.js
=> update nature color, remove responsivelink override for color

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/services.ts
=> fix(linting): add ts-ignore to helper functions

packages/blockchain-wallet-v4/src/redux/kvStore/eth/sagas.js
https://blockchain.atlassian.net/browse/FWLT-279
=> fix(pax): change pax label if incorrect

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/Notifications/Notifications.js
=> feat(usd-rebrand): update paxos copy in swap

packages/blockchain-wallet-v4/src/redux/kvStore/eth/sagas.js
=> feat(usd-d): pax label was USD PAX or USD Pax

packages/blockchain-wallet-v4-frontend/src/data/components/borrow/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/types.ts, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/services.ts, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/validation.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/InitBorrowForm/Amount/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/InitBorrowForm/Amount/selectors.ts, packages/blockchain-wallet-v4/src/network/api/borrow/types.ts
=> fix(borrow): min/max validation from offer

packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/InitBorrowForm/Amount/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/InitBorrowForm/Amount/selectors.ts
https://blockchain.atlassian.net/browse/FWLT-289
=> fix(borrow): you can borrow up to fix

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/TabMenuPaymentMethod/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/template.success.tsx
=> fix(borrow): use principal display name in formatted messages

tsconfig.json
=> build(fix): temp ignore problem ts file

package.json, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/services.ts, packages/blockchain-wallet-v4/src/network/api/borrow/types.ts, yarn.lock
I upgraded TS and removed a few @ts-ignore's. I ran yarn ci:compile multiple times with no issue
=> fix(ts): build issue fix

packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.utils.ts
=> fix(borrow): include priority fee on eth txs

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/AddCollateral/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/ConfirmBorrow/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/selectors.js, packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/types.ts
=> fix(borrow): check eth for fee sufficiency

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/validation.tsx
=> fix(borrow): better min error details

packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/btc/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/xlm/sagas.js
=> fix(borrow): add coin to payment _value_

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/components/refresh/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/PaxWelcome/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/LowEthWarningForErc20/index.js, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/USDDigital.js, packages/blockchain-wallet-v4-frontend/src/services/WhatsNewService/WhatsNewContent/__snapshots__/USDDigital.spec.js.snap
=> fix(usdd): rebrand routing and ETH caps in send modal

packages/blockchain-wallet-v4-frontend/src/components/Navbar/NavbarBrand.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/SendRequest/template.js
=> spacing, divider

packages/blockchain-info-components/package.json, packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-info-components/src/Form/CreatableInput/template.js, packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/create-nonce.js, yarn.lock
=> chore(dependencies): upgrade react-select, remove button prop types

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/index.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/model.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinPrices/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinPrices/selectors.js, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/template.loading.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/model.ts
=> fix(txs): coin price change fixes

packages/blockchain-wallet-v4-frontend/src/components/Form/EmailVerification/EmailVerification.js, packages/blockchain-wallet-v4-frontend/src/components/Form/EmailVerification/__snapshots__/EmailVerification.spec.js.snap, packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js, packages/blockchain-wallet-v4-frontend/src/components/IdentityVerification/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/IdentityVerification.spec.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/IdentityVerification/Personal/template.js
Reverts blockchain/blockchain-wallet-v4-frontend#2131
=> Revert "Style/kyc form"

packages/blockchain-wallet-v4-frontend/src/components/Form/FiatConverter/Converter/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/FiatConverter/Converter/template.js, packages/blockchain-wallet-v4-frontend/src/components/Form/FiatConverter/index.js, packages/blockchain-wallet-v4-frontend/src/components/Form/FiatConverter/selectors.ts
=> fix(pax-rebrand): send modal

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/Summary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Exchange/ExchangeConfirm/ExchangeError/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/BorrowHistory/template.success.tsx
=> fix(e2e): tags for borrowhistory, summary, and swap error message

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.js
=> fix(borrow): remove invitations.borrow check

packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.ts
=> fix(borrow): send checksummed addr

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/WhatsNewIcon/selectors.js
=> fix(build): broken imports

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.tsx
https://blockchain.atlassian.net/browse/NABU-1904/https://blockchain.atlassian.net/browse/FWLT-371
=> fix(usdd-ordersummary): change to USDD

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/template.success.tsx
https://blockchain.atlassian.net/browse/FWLT-382
=> fix(sb-euro): payment details for Euro trades

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Footer/index.js
=> fix(ad): margin top and bottom

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/index.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.tsx
=> feat(nav): if no devices remove hardware from left nav

packages/blockchain-info-components/src/Form/CreatableInput/template.js, packages/blockchain-info-components/src/Form/SelectInput/template.js
=> fix(send): fix paste in send

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowDetails/Summary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/Summary/index.tsx
=> fix(borrow): rounding rate

packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.ts, packages/blockchain-wallet-v4/src/redux/payment/types.ts
=> fix(swap): eth provisional payment, from can be undefined

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Savings/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx
route to /interest, scene header 
=> feat(interest): change route and scene header

packages/blockchain-wallet-v4-frontend/src/middleware/matomoMiddleware.js
Track form inits
cc @ioanna-bc 
=> fix(matomo): track form init

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/assets/locales/types.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Register/template.tsx
-hover text effects and utm codes on linkout
=> Fix(signup): style tweaks

packages/blockchain-wallet-v4-frontend/src/data/components/recoveryPhrase/actionTypes.ts
=> fix(recovery-phrase): fix action step

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/CurrencySelect/SelectBox/index.js
=> fix(swap-select-box): fix border on swap selectbox

packages/blockchain-wallet-v4-frontend/src/middleware/matomoMiddleware.js, packages/blockchain-wallet-v4-frontend/src/modals/RecoveryPhrase/index.tsx
- removes logging artifacts from developing
- ensure matomo iframe is loaded before posting message to avoid console errors
=> Fix(cleanup console)

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Balances/Tabs/index.tsx
=> feat(balances): fix redux connect issue for balances tab

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Footer/index.js
=> fix(footer): clean up ad spacing

packages/blockchain-wallet-v4-frontend/src/middleware/matomoMiddleware.js
=> fix(matomo): add event action blacklist

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CurrencySelection/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/template.success.tsx
=> feat(e2e): add e2e tags

packages/blockchain-wallet-v4-frontend/src/assets/locales/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/template.unsupported.tsx
=> fix(flyout): correct flyout copy according to design

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
=> feat(simple buy): fetch sb balances after sb order poll finishes

packages/blockchain-wallet-v4-frontend/src/components/Navbar/NavbarBrand.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/SendRequest/template.js, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/Header/template.small.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/index.js
- Old ![](https://cloudup.com/czpf5cFWKiT+)
- New ![](https://cloudup.com/cS1GYn0TQLi+)
Also, tweaking padding on Preferences mobile
=> Fix responsive logo, hamburger, balances, send, receive and preferences

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/template.success.tsx
=> fix(simple buy): hardcode eur and gbp for sb eligibility

packages/blockchain-wallet-v4-frontend/src/data/analytics/model.js, packages/blockchain-wallet-v4-frontend/src/data/components/interest/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/TabMenuTimeFrame/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
=> fix(savings): time frame change

packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
=> fix(simple buy): xlm limit to non custody

packages/blockchain-wallet-v4-frontend/src/data/preferences/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/preferences/sagas.ts
Fix for https://blockchain.atlassian.net/browse/FWLT-446 but shouldnt block release
=> fix(simple buy): if sb cur and wallet cur get out of sync, sync

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/TransactionList/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/interest/types.ts
=> fix(interest): search just hash in transactions

packages/blockchain-wallet-v4-frontend/src/data/components/interest/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx
sends satoshis in withdrawal request 
=> fix(withdrawal): send sats instead of fiat

packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/selectors.ts
=> fix(interest): calculate withdrawal amount correctly

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts
=> fix(balance): recovered user sb, interest balance

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/AddCollateral/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/ConfirmBorrow/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/ConfirmBorrow/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/validation.tsx
=> fix(interest): a bit less lag on depo interest form

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/IntroCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/TransactionList/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
=> fix(interest): add e2e tags

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/TransactionList/template.success.tsx
=> fix(interest): use txHash for withdrawals, hide if tx is pending

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
=> fix(interest): move eligible and account calls to top interest comp

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
=> fix(interest): deposit form link to borrow terms

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx
=> fix(interest): disable withdrawal and spacing

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/interest/types.ts
=> fix(interest): remove account balance check from selector

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/TransactionList/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
=> fix(interest): move legal disclaimer to tooltip

packages/blockchain-wallet-v4-frontend/src/components/Navbar/index.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/index.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Features/template.small.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/template.large.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/template.small.tsx
=> css tweaks

packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/template.success.js
=> fix(email-auth): mobile view

packages/blockchain-wallet-v4-frontend/src/components/Navbar/index.tsx
=> color change

packages/blockchain-info-components/src/Toasts/Toast.js, packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.tsx
=> fix(data-e2e): toastMessage tag on right element

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts
Dont merge this until we have validated with QA
=> fix(exchange link): upgrade wallet/exchange link detection

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
=> fix(interest): duplicate legal

packages/blockchain-wallet-v4-frontend/src/components/Balances/wallet/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/interest/types.ts
=> fix(interest): balance responses from number to string

CODEOWNERS
This PR is just to add myself as coowner 
=> Added myself as coowner

CODEOWNERS
First PR 🎉 
Just adding myself to code owners
=> Add Diego Sisto to code owners

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.tsx
=> fix(side-nav): exchange logo size

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/TransactionList/template.success.tsx
=> fix(e2e): tx id to icon

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/template.headerexplainer.tsx
Updated typos
login to wallet make sure that you can see on left side USDT
=> feat: fixed typos after code review

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxEthAddresses/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/TransactionList/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx
=> feat(eth-interest): add interest wallet to eth balance dropdown

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.ts
This PR solve issue for propagating proper coin to selector and then to run transaction call 
login to wallet 
try to send some usdt
make sure that there are no errors in network tab
=> feat: fixed propagation of proper coin name

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/selectors.js
This PR solve problem with swap what we had for usdt
login to wallet
navigate to swap
make sure that USDT is option in swap drop down
=> feat: added usdt swap missing part in selector, more generic selector

packages/blockchain-wallet-v4-frontend/src/components/Balances/wallet/selectors.ts
=> fix(balance-selectors): eth and erc20 selectors

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/goals/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/goals/types.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/TheExchange/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/TheExchange/template.connect.tsx
One last thing for USDT, if the user is connected to the Exchange, resync addresses when they login.
Also some cleanup and reorganizing things alaphabetically.
=> feat(pit): change isRelinkRequired check to check new coins

package.json, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx, yarn.lock
Improved typings and migrated styled components to latest
login to wallet, make sure it works as expected
=> feat: added new step and proper typing

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/template.headerexplainer.tsx
=> fix(algo): add header

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/selectors.ts
Prevent constant loading of API endpoints
=> feat: code improvements

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/template.success.tsx
=> feat: fixed back button

packages/blockchain-wallet-v4-frontend/src/data/analytics/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/analytics/types.ts, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/exchange.sagas.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/selectors.ts
=> fix(swap): remove ab test

README.md, package.json, packages/blockchain-wallet-v4/package.json, packages/blockchain-wallet-v4/src/utils/eth.ts, packages/blockchain-wallet-v4/src/walletCrypto/importExport.js, yarn.lock
Reverts blockchain/blockchain-wallet-v4-frontend#2546
=> Revert "fix(builds): temp rollback node 12"

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/validation.tsx
=> feat(interest): min amount in error

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
=> fix(interest): deposit fee

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/KycRequired/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/KycRequired/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/template.rejected.styles.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/template.rejected.tsx
=> feat: implemented new KYC step

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.utils.ts, packages/blockchain-wallet-v4/src/network/api/coin/model.ts
=> fix(int.): fix deposit payment handling

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
=> fix(sb): fix transfer details payment method

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Payments/PaymentCard/index.tsx
=> fix(sell p2): card logos

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/model.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/index.tsx
=> fix(buy): wrong payment method type

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Payments/index.tsx
=> fix(sell): dont require balance  for sell to method

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/SimpleBuy/index.tsx, packages/blockchain-wallet-v4-frontend/src/data/custodial/actions.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.loading.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/styles.tsx, typings/redux-form.d.ts
implemented list of linked bank accounts
=> feat: implemented linked banks

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/AddCard/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/ActionButton/index.tsx
on Sell/Buy flow label on button is Next rather than Continue
=> feat: changed continue label

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Payments/PaymentCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Payments/index.tsx
=> feat: payment options cleanup

packages/blockchain-wallet-v4-frontend/src/components/Balances/wallet/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/validation.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/validation.js, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/selectors.ts, packages/blockchain-wallet-v4/src/redux/payment/bch/sagas.js, packages/blockchain-wallet-v4/src/redux/payment/btc/sagas.js
=> fix(withdrawal): fix for btc and bbch max withdraw

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Send/index.tsx, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/model.ts, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/selectors.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/services/FormHelper/validators.js
https://www.figma.com/file/zKPhU5yTqpPTqa8awaTvjU/Withdrawal-Locks?node-id=0%3A1
=> feat(withdrawal): lock banner on send

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts, packages/blockchain-wallet-v4/src/network/api/profile/index.js
We call finalise endpoint as BE requested 
=> feat: finalise linking

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/custodial/types.ts
=> WAL-69 - Settings general errors with beneficiaries call

packages/blockchain-info-components/src/Buttons/Button.js, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
Improved rendering of txn details and summary page
=> feat: improved summary page

packages/blockchain-wallet-v4/src/network/api/profile/index.js
We lost some changes in one or previous PRs this PR is all about to revert proper function call
=> Feat/Wallet Linking: fixed proper API call and passing of address/emmail

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/SellBanner/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/index.tsx
This PR implements new sell banner 
=> feat(sell banner): implemented new sell banner

packages/blockchain-info-components/README.md
=> For easier finding of desired option

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4/src/network/api/interest/index.ts
=> fix(interest): send string to withdrawal req

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
=> fix(interest): remove multiple failure messages

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
=> Feat/Simple buy: error message has ben centred

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkFromExchangeAccount/template.conflict.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkFromExchangeAccount/template.failure.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkFromExchangeAccount/template.success.tsx
=> Feat/Wallet linking: fixed action to return to exchange

packages/blockchain-wallet-v4-frontend/babel.config.js, packages/blockchain-wallet-v4-frontend/package.json, yarn.lock
=> feat(styled components): added babel plugin to render nice class name

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
Go to the end of simple buy flow and try to but with card new disclaimer should be visible at the last step
=> feat(sell checkout): implemented new disclaimer in case of buy with CARD

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Tooltips/index.js, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/template.success.tsx
=> feat(withdraw): inform user that founds need some time to be process

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxEthAddresses/selectors.ts
=> fix(send): include exchange wallet for tether and pax

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CancelOrder/template.tsx
=> feat(sell flow): fixed proper label to be shown on order cancel page

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
For this release we are not including send to non custodial 
=> feat(custodial send): temp disable custodial send

packages/blockchain-wallet-v4-frontend/src/providers/TranslationsProvider/index.js
This PR solve problem with react-intl massive errors in console
=> Fix(language locale): fixed problem with empty language

packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/validation.tsx
now we have withdraw minimum it's set to $1000
=> feat(USD wallet): withdraw min has been set

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
This PR is all about fixing a copy text
=> Feat/Wallet Brokerage: fixed copy on last step for buying over credit card

packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts
=> Feat/Fiat ordering: fixed fiat ordering to be USD, EUR, GBP

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/KycRequired/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/KycRequired/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/ThreeDSHandler/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/ThreeDSHandler/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/ThreeDSHandler/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/simpleBuy/index.ts
wal-80 and https://blockchain.atlassian.net/browse/FWLT-744
=> fix(buy): credit card addition  and checkout fixes

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx, packages/blockchain-wallet-v4/src/redux/walletOptions/types.ts
=> feat(usd): add depo and withdraw feature flag

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/SBOrderBanner/index.tsx
=> fix(sb): buy sell order banner

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/index.tsx
=> feat(send non custodial): remove sell banner

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/index.tsx
=> feat(fiat transactions): added automate test data for better automated tests

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/index.tsx
=> feat(buy banner): refetch user orders on order summary page

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/model.tsx
=> feat(fiat transactions): added missing e2e attributes

packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/SecondStep/template.success.js
=> feat(send): added e2e for total on send

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json, packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.tsx
=> feat(login): added missing apostrophe

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
=> feat(simple buy): added missing e2e attributes on enter amount screen

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/index.tsx
=> Feat/Simple buy: added proper e2e data attributes

packages/blockchain-wallet-v4-frontend/src/components/QRCodeCapture/index.js, packages/blockchain-wallet-v4/src/utils/eth.ts
=> feat(qr scan): improved way of scanning coinbase QR from ETH

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/PriceMovement/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/UserPortfolioPositionChange/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/UserPortfolioPositionChange/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/model.tsx, packages/blockchain-wallet-v4/src/redux/data/misc/actions.ts, packages/blockchain-wallet-v4/src/redux/data/misc/model.ts, packages/blockchain-wallet-v4/src/redux/data/misc/sagas.ts, packages/blockchain-wallet-v4/src/redux/data/misc/types.ts
=> feat(price): when amt changes get new portfolio change

packages/blockchain-wallet-v4/src/redux/data/simpleBuy/sagas.ts
=> fix(sb): let be filter payment txs by coin

packages/blockchain-wallet-v4-frontend/src/components/AndroidAppBanner/index.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js, packages/blockchain-wallet-v4-frontend/src/manifest.webmanifest, packages/blockchain-wallet-v4-frontend/utils/webpackBuilder.js
This is not intended for production! Will test in lower environments first and then tweak from there.
=> feat(native apps): add android app install banner with logging

packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/ConfirmWithdraw/index.tsx
We used wrong form data on render checkout page
=> feat(withdraw): use amount from proper redux form

packages/blockchain-wallet-v4-frontend/src/middleware/matomoMiddleware.ts
=> feat(sb): add side to sb step for  some steps

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
=> feat(pending txs): update sb balance on wss tx event

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx
=> feat(buy): show buy cta on coin tx lists

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/custodial/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/BankPicker/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/BankPicker/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/selectors.ts
=> fix(withdrawals): filter for currency

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
Description/notes aligned to 100 characters
=> Feat/Tx description: aligned to be max 100 characters

packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/CurrencySelect/CurrencySelect.js, packages/blockchain-wallet-v4-frontend/src/scenes/Exchange/ExchangeForm/CurrencySelect/SelectBox/index.js
=> feat/Missing e2e - added missing e2e data to select currency dropdown

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/template.success.tsx
This PR fix copy on withdraw flyout 
=> feat(wire transfer): fixed copy for USD wire transfer

packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/validation.tsx
=> Feat/Pending Info: hide tooltip in case that withdrawable amount is same as fiat balance

packages/blockchain-wallet-v4/package.json, yarn.lock
https://www.stellar.org/developers-blog/guide-to-protocol-14-prep?locale=en
=> chore(deps): update xlm sdk to support protocol 14

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx
Fixes FCOM 136, unsupported currency 
=> fix(simplebuy): add logic to fix sb not available bug

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/template.tsx
=> feat(verify email): added check to remote is success removed rem replaced with px

packages/blockchain-wallet-v4-frontend/src/data/analytics/types.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/exchange/types.ts
=> feat(verify email): fixed typo with EMail to Email

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/SecondStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/SecondStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/SecondStep/template.success.js, packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/SecondStep/template.success.js
=> Feat/e2e testing: added missing tags for e2e testing on second step of send flow for total and subtotal amount

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/CryptoLinkHandling/index.js
=> feat(btc handling): for safari we show additional info that feature is not supported

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts
Login to wallet go to simple buy, chose Polish Zloty and try to sell, default should fiat wallet with highest amount
=> feat(sell flow): for sell we select by default fiat wallet with highest balance

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/data/components/withdraw/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/TransferDetails/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/BankPicker/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/index.tsx
=> feat(bank linking): added additional info line in case that user is about to access add a bank

packages/blockchain-info-components/index.d.ts, packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
=> feat(card buy): implemented accept terms and conditions

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
=> fix(terms): wrap accept terms set in useeffect

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
Use AB testing only for fist login and prevent usage on login
=> feat(login): use AB testing only in case of firstLogin

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/index.tsx
=> Feat(Simple Buy): add matomo tracking on buy/sell crypto

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js
=> feat(banners): load user id in case that user is not in kvstore

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/swap/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/validation.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/selectors.ts
Min and Max swap (just min right now)
=> feat(swap-2.x): min clarification and notes

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/components/index.tsx
=> feat(swap): add free tag

packages/blockchain-wallet-v4-frontend/src/data/components/swap/selectors.ts
=> fix(swap): xlm conversion

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js
=> feat(matomo-guid): change guid for non nabu user

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
=> fix(swap): usdt conversion for payment amt

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/actions.ts, packages/blockchain-wallet-v4-frontend/src/scenes/InterestHistory/template.success.tsx, packages/blockchain-wallet-v4/src/network/api/interest/types.ts
show correct origin/destination wallets for interest transactions
=> fix(interest): custodial transaction labels

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
=> Withdraw Lock - bug fixes

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/NewCurrency/index.tsx
fixes issue with close icon being too small and wrong color as well as adds a pointer hover state
=> wdgld banner styles

.github/CODEOWNERS, CODEOWNERS
=> chore(codeowners): update

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Withdraw/EnterAmount/LockTimeTooltip/template.tsx
=> feat(withdraw lock): added singularity for days

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/NewCurrency/index.tsx
Changes formatting of wdgld text from WDGLD to wDGLD
view text in announcement banner.
=> Small UI fix for wdgld

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/TransactionList/template.interest.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts
- Show Interest accounts in coin dropdowns so balances add up to the total
- Update button linkout to the new transaction page for Interest
=> fix(interest): show all interest accounts 

packages/blockchain-wallet-v4-frontend/src/components/Balances/total/selectors.ts, packages/blockchain-wallet-v4-frontend/src/components/Balances/wallet/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js, packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts, packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/index.tsx, packages/blockchain-wallet-v4/src/redux/settings/index.d.ts, packages/blockchain-wallet-v4/src/redux/settings/model.ts
Removes no longer needed checks for feature invites since they have all rolled out to 100% of users.
=> feat(invite list): cleanup no longer needed invite checks

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Payments/index.tsx
Add possibility of undefined for currencies available for deposit. Handles case where we allow CAD users to use cards as an option to buy crypto. 
=> fix(buy): handle case for cad currency to buy cards

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Veriff/template.success.tsx
Prevent to render more times veriff modal
Login with silver+ user and then click on verify gold, once when veriff modal is open close it and try again, should render veriff modal and be able to use it.
=> feat(sdd): prvent duplicate render of veriff modal

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.sdd.success.tsx
go with SDD on step here you have to confirm your CC click on back button; order overview page will show button to finish panding transactions
=> feat(sdd): fixed case when user stop 3DS step

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/ThreeDSHandler/template.loading.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/template.loading.tsx
Try SDD flow, loading message should say `Processing...` before it was `Doing work...`
=> Feat SDD - loader message has been changed

packages/blockchain-wallet-v4-frontend/src/components/Form/CreditCardExpiryBox/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/AddCard/template.success.tsx
=> feat(sdd): fixed styling issues and improved logic with expire date to properly format on paste

packages/blockchain-info-components/src/Badges/Badge.js, packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/components/IdentityVerification/TierCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/components/Navbar/index.tsx, packages/blockchain-wallet-v4-frontend/src/components/Setting/SettingDescription.tsx, packages/blockchain-wallet-v4-frontend/src/components/Setting/SettingHeader.tsx, packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Wallet/PairingCode/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Menu/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/About/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/PairingCode/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/PrivacyPolicy/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/TermsOfService/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/WalletId/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/AutoLogout/Settings/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/AutoLogout/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/MobileNumber/Settings/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/MobileNumber/template.loading.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Notifications/Settings/template.success.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/Notifications/template.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/IdentityVerification/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Profile/index.js
Most of the settings pages havent been updated in years.  This is a quick sweep through to update the styles to closer match the look and feel of the rest of the application. There are no functional changes in this PR except to fix a bug with a modal that was unable to be closed.
=> Feat(Settings): Update page layouts and consistency of styling

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
=> feat(sdd): we have to take care for user with T3 after we stop sdd, they have to be prompted to KYC flow

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Register/SignupForm/index.tsx
Add signup disclaimer
Should see checkbox disclaimer no signup form
make sure you cant create a wallet without selecting checkbox.
=> feat(signup): add secret phase copy

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Veriff/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Veriff/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Verify/index.tsx
This PR prevents rendering more than one iFrame from veriff
Try to verify gold and make sure that each time proper veriff modal is visible and usable.
=> feat(veriff): prevent injecting more than one iframe

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
In case that order need 3DS handling we immediately redirect user to 3DS step
=> feat(simple-buy): force user to go to 3DS handler page

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/selectors.ts
=> feat(sdd): prevent sdd flow and prevent tier 3 sdd user to add new card

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
We have to compare number when we do comparison over numbers which are type of string.
=> feat(simple-buy): when comparing string numbers convert it to numbers and then compare

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/ActionButton/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
=> Feat/FWLT-961 - show sell limit in case that daily limit exceeded

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
We are returning back SDD, beside of this frontend  PR BE guys will turn it on on BE
Create a new wallet; go over SDD flow, make sure SDD flow works as expected
=> feat(sdd): reverted changes back to have SDD again

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/model.tsx, packages/blockchain-wallet-v4/src/network/api/simpleBuy/types.ts
State no longer used by backend.
=> chore(cleanup): remove no longer used DEPOSIT_MATCHED state

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/LinkedPaymentAccounts/Accounts/Card/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx
Simplifies the UI for your saved cards and banks in general settings/selected payment method and saved payment methods in simple buy flow
Check the three places described above to see new, simplified, text/styles.
=> fix(payment methods): changes format for cards/banks saved payments

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx
=> fix(tx list): always have a default case so exotic order types dont blow up app

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/selectors.ts
This PR solves issue with failing end point when user is about to be created
Try to create new wallet go trough SDD flow
=> fix(sdd): prevent expecting success on case for new users it will not be the case

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/Settings/RecoveryPhrase/RecoveryPhraseIntro/index.tsx
=> fix(typo): as to ask

packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Borrow/InitBorrowForm/index.tsx
Borrow is being decommissioned and no new loans are allowed to be created. The feature will be fully removed once all open loans are closed.
=> feat(borrow): disable new loan creation while feature is being sunset

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
Fixes FWLT-753 - refreshes all balances after a sell is submitted so balance changes are immediately reflected. 
=> fix(sell): refresh balances after sell is submitted

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
FWLT-1043: updates copy specifically for ACH buys that have started but are pending deposit. 
=> fix(ach-buy): copy update for ach orders pending deposit

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PreviewSell/index.tsx
Adds back data tag that was removed with changing design for Sell confirm screen. 
=> fix(automation): add tag back in for sell total

packages/blockchain-wallet-v4/src/utils/btc.spec.js
=> fix(bech32): add test case for correct bech32 pubkeyhash decoding

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.tsx, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts
Adds feature flag to mobile auth login via wallet options. I'll open another PR for wallet-options, staging set to true, prod set to false. 
=> feat(qr-code): add feature flag to wallet options

packages/blockchain-wallet-v4-frontend/src/scenes/Register/SignupForm/index.tsx
Leaving the opacity handling with the Form Components
(screenshot of safari)
=> fix(signup): removing opacity 1 for SignupForm

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
This PR improve transitioning between KYC steps and SDD flow
Create a new wallet go trough SDD steps and after adding info and residential data make sure that you are redirected to overview page
=> feat(sdd): improved transition over add user info and residential data and next step on SDD flow

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
This PR solved 
- alignment issue with icons
- fixed header on scroll
- fixed copy text
Login to wallet, click on settings gear and then on Trading Limits scrollable section
=> feat(settings): fixed header to be fixed, alignment of icons and proper copy has been placed

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
This is PR fix alignment with arrow and icons
login to wallet and go to settings and trading limits
=> feat(settings): align arrow with gold/silver icons

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/utils/webpackBuilder.js, packages/blockchain-wallet-v4/src/redux/kvStore/buySell/selectors.js
Removes unused configs from previous integrations
=> chore(cleanup): remove old sfox/coinify configs

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
Fixed logic surrounding indicators for tier statuses
Finish silver verification and then check settings trading limits
=> feat(settings): fixed verified gold tier logic

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
This PR fix proper label for tier 0
Create new wallet and then go to settings and trading limits
=> feat(settings): fixed labels for tier 0

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
This PR fix proper alignment of icons on Trading Limits
Login to wallet go to Trading Limits
=> feat(settings): fixed alignment

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/types.ts, packages/blockchain-wallet-v4-frontend/src/data/components/swap/types.ts, packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Methods/PaymentCard/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Swap/InitSwapForm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/NoHoldings/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx, packages/blockchain-wallet-v4-frontend/src/services/CheckAccountZeroBalance/index.ts
https://user-images.githubusercontent.com/13142568/108761757-ff2c3f00-752d-11eb-8b54-d5171ac15949.mov
=> Adding empty state for Swap

packages/blockchain-info-components/src/Images/Images.ts, packages/blockchain-info-components/src/Images/img/circle-empty.svg, packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/types.ts, packages/blockchain-wallet-v4-frontend/src/data/components/withdraw/reducers.ts, packages/blockchain-wallet-v4-frontend/src/data/components/withdraw/types.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/BankList/Accounts/Bank/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/BankPicker/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/BankPicker/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/BankPicker/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/BankTransfer/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/template.failure.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/template.loading.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx, packages/blockchain-wallet-v4-frontend/src/services/ActiveToggleService/index.tsx
Adding styles and functionality for withdrawal methods
- USD enabled account
- Go to USD wallet
- Click Withdraw button in upper right
- click default bank section on enter amount screen
=> feat(ach withdrawals): added styles and functionality to withdrawal flow

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/router/sagas.js
- Fixes a super old bug that has been around since the start of the application in which the app will bootstrap itself twice.
- Allows for logging for all authentication states of user
=> Fix(app): fix double app bootstrap on enter

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/components/index.tsx
This PR fix styling of withdraw enter amount screen 
=> feat(ach): styled withdraw enter amount modal

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx
This PR solve issue with withdraw and alway preselect brokerage account
Go to some wallet with multiple accounts go to USD open withdraw
=> feat(ach): fixed withdraw selected account

packages/blockchain-wallet-v4-frontend/src/modals/Lockbox/LockboxSetup/index.js, yarn.lock
Fixed warnings for `componentWillUpdate` and `caniuse`
=> fix(codebase): removing warnings

config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/BankPicker/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/selectors.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/selectors.ts, packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts
Wrap the new deposit and withdrawal ACH functionality in a feature flag
=> feat(ach): wrap deposit/withdrawal functionality in a feature flag stored in wallet options

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/selectors.ts, packages/blockchain-wallet-v4/src/redux/settings/index.d.ts, packages/blockchain-wallet-v4/src/redux/settings/model.ts
Removes Simple Sell 2.0 invite since its rolled out to everyone
=> chore(invite list): clean up no longer needed invite flag

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
Fixes an issue where if the user wants to reconnect to secure channel, we were previously unable to re-init the connection.
=> fix(mobile auth): allow to resubscribe to channel

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/index.tsx
Hotfix for non-custodial sell invite list check. We no longer need the check, so it should be removed completely.
=> fix(sell): remove invite list check

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
Improved logic to show banners
- Create a new wallet go over sdd flow jump out banner should be visible
- for silver tier or silver plus, do some BUY/Swap and check is proper banner verify gold shown
=> feat(kyc): implemented new logic when to show which SDD banner

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx
This PR helps to run goals at proper time when wallet is all set
Create an exchange account and then link it with wallet, create new wallet and flyout with wallet linking should be visible
=> feat(sdd): show proper goal if user came from exchange linking

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/Welcome/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/selectors.ts
Fixed issue with loading buy/sell modal
1. create a new a wallet
2. do not verify email
3. go to any coin page
4. click on “buy {coin} button in center of page
5. make sure you see buy/sell modal loads
=> chore(buy): fixed problem with opening modal

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/VerifyEmail/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/VerifyEmail/selectors.ts
Fix proper start of sell/buy flow
- Create new wallet
- go to any crypto page
- click on white button to buy crypto
- buy flow should work without closing of modal and redirecting back to home
=> chore(buy): improved loading to prevent unexpected failing and redirection

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/template.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/CoinCurrentPrice/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/CoinSelector/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinChart/template.tsx
=> feat(home): fixing responsivity for the homepage

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/selectors.ts
=> chore(typo): fixed import typo

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Holdings/CoinBalance/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Home/Holdings/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/index.tsx
Small changes to copy and some styling
=> fix(prices): small style and copy changes

packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/balance.column.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Prices/index.tsx
- Fixes table sorting by balances
- Adds search icon to input
=> Fix(Prices): Table sorting by balance

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
Creates array of xpubs correctly for websocket, accounting for new structure of btcWalletContext. 
=> fix(ws): pass xpub array correctly to ws

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxEthAddresses/selectors.ts
This PR solves issue with proper rendering of account names and balances
Try to send Aave or Yarn Finance, make sure account names are properly rendered
=> fix(send): fixed proper rendering for send of new coins

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/model.tsx
This PR resolve problem with rendering enter amount step of buy/sell flow
Login to wallet try to buy some crypto, make sure that you can proceed to enter amount screen
=> fix(buy): fixed rendering of buy flow when bank do not have all expected details

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/LinkedPaymentAccounts/Accounts/Bank/index.tsx
=> feat(ob): improved rendering and added fallback

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/BankDetails/template.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/model.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/model.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx
Fixed remaining places where we had use bankAccountType 
Login to wallet, test sell/buy flow
=> feat(sell): fixed usage of bankAccountType undefined for open banking

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/index.tsx
This PR solve issue with SDD flow
Create wallet as SDD eligible user and not make sure that you see proper welcome modal
=> fix(sdd): fixed show of welcome modal for SDD eligible users

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
=> fix(legal): fixing legal copies for simplebuy

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.js, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.tsx
https://user-images.githubusercontent.com/13142568/113761032-5b69ad80-96ed-11eb-8bb6-26d7825113b7.mov
=> fix(login): fixing responsivity for login page

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Chart/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinChart/template.tsx, yarn.lock
Added Polyfill for old browsers
=> fix(polyfill): adding polyfill for resize observer

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/template.error.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/template.loading.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/Login/template.tsx
=> fix(device_change): hanging device_change screen sizes

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagaRegister.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/Authorize/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx
Authorization screen was not creating a simple buy order after the user clicked approve. This adds in the order creation code after the user clicks approve.
=> fix(open banking): fixes issues where simple buy authorize screen doesn't create an order after approving it

packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/index.tsx, packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/template.success.tsx
=> fix(login): pushing new designs for login approved scene

packages/blockchain-wallet-v4-frontend/src/scenes/Home/index.tsx
https://user-images.githubusercontent.com/13142568/114239283-4181d200-995c-11eb-9b68-489ee59f4a20.mov
=> fix(home): fixing breakpoint for homepage

packages/blockchain-wallet-v4-frontend/src/data/coins/utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
This PR solve issue with wrong formatting of USDT
Go to interest try to transfer some USDT
=> feat(interest): we have to pass origin coin and do proper formating

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
This PR solve issue with calling endpoint in case that nabu user still do not exists
Create new wallet try to open buy/sell flow
=> feat(open banking): call stuff only in case that user exists

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/selectors.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/template.success.tsx
This PR solve issue with fees on deposit screen
Go over fiat deposit to confirmation screen fee(s) should not be presented at all
=> feat(open banking): in case of deposit we do not need to show fee since we do not charge

config/env/production.js, config/mocks/wallet-options-v4.json, packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/utils/webpackBuilder.js, packages/blockchain-wallet-v4/src/network/api/simpleBuy/index.ts
Add the success callback url to the open banking api calls & Small fix for the earn promo modal broken link
Connect a bank or make a transaction with open banking and once you've verified on modelo you should be redirected to a new success page.
=> feat(open banking): add callback url to api requests and fix broken link in earn popup modal

packages/blockchain-wallet-v4-frontend/package.json, packages/blockchain-wallet-v4-frontend/src/components/Flyout/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Borrow/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYodlee/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/BankDetails/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/RemoveBank/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Interest/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkFromExchangeAccount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/Welcome/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Settings/RecoveryPhrase/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx, yarn.lock
https://user-images.githubusercontent.com/13142568/114914324-898b7380-9df8-11eb-956d-f5b845257a03.mov
=> feat(animations): changing animations for flyout

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts, packages/blockchain-wallet-v4/src/network/api/simpleBuy/index.ts
Api needs callback url to be in an attributes object
=> fix(open banking): callback needs to go in an attributes object on the request

packages/blockchain-wallet-v4-frontend/src/data/coins/utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/borrow/sagas.utils.ts, packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
This PR is improvements and removing of nasty `if (coin)` stuff
make sure that all actions works properly, like sell/buy, swap
=> feat(coins): better formatting of coins removing if (coin) statement

packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx
This PR fix bank logo size on OB flow
Go over OB flow, try to Link a new bank, choose one and then you will see something like this
=> feat(ob): fixed sizing of logo image

packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/validation.js, packages/blockchain-wallet-v4/src/types/Address.js, packages/blockchain-wallet-v4/src/types/Wallet_DEPRECATED_V3.js, packages/blockchain-wallet-v4/src/walletCrypto/importExport.js
=> fix(btc): addr imports, new bitcoinjs to addr usage

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx
=> feat(ob): fix min/max validation

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
This PR update just date frame for lock time period
=> feat(ob): fixed lock time from 14 to 7 days for ACH

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
=> feat(ob): we decide to use dynamic lock days

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts, packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/template.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/index.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
Cleanup of hardcoded values added logic not to show row in case of open banking
Deposit over Open Banking make sure that `Funds Will Arrive` line is not shown
=> feat(ob): added logic not to show row in case of OB added small clean up

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/styles.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.sdd.success.tsx, packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/template.success.tsx
Implemented X button and OK button per designs
Finish OB buy, you should see OK button and X button on top
=> feat(ob): added OK button on final step

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/ConfirmWithdraw/template.success.tsx
Added account name for OB accounts on withdrawals 
Go to withdrawal and make sure on confirm page to see account name if it's present in defaultMethod details
=> feat(ob): added account name property

packages/blockchain-wallet-v4/src/network/api/interest/types.ts
EDD end point response fixed to use most recent response
This is pre dev step of EDD phase 2
=> feat(edd): aligned API response with new changes

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx
For SDD flow we do not need new limits to be considered since SDD have it's own limits
Try to buy some crypto with SDD flow
=> feat(buy): fix SDD case for max amount
