packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts

If a user closes the simple buy modal when they're on the QRCode screen, we should drop them back into the QRcode screen whenever they open the simple buy modal up. 
https://www.loom.com/share/00ced072217f425394c03010eb3025c8
Do a simple buy with an open banking bank, when the QR code screen comes up, close the modal and then click on the various ways to bring the simple buy modal back up.

fix(open banking): reopen qrcode screen and poll order status when user opens simple buy if necessary

---

packages/blockchain-wallet-v4-frontend/src/data/goals/actions.ts
packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware.ts

fix(goals): send origin to analytics

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Addresses/Btc/ManageAddresses/UsedAddresses/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx

- Fixes background colors for coins in transaction lists
- Allows user to hide used addresses list

Fix(bugs): coin icons & used addresses list

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx

This PR solve unchecked exception when start withdraw
Test withdraw for some FIAT currency, make sure there is now unchecked exception occurred

feat(open banking): fix unchecked exception when user start withdraw

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx

This PR fixed issue with comparing min/max dates
Try to buy some DOT coin

feat(buy): convert limit amount to minor string

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/IntroCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/selectors.ts

Fixed Figma stuff and logic about show up proper box on interest page
Use account which need EDD action

feat(edd): improved EDD logic to align with Figma

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.js
packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/index.tsx

This PR solve issue with showing up welcome modal
- Signup with new wallet from non eligible country (common welcome modal should be shown)
- Signup with new wallet from eligible country (sdd flow should be shown)
- Login with existing wallet no modal should be shown

feat(login): fixed issue with goals

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/IntroCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/selectors.ts

Taking EDD phase 1 off this release
Go over to interest page

feat(interest): removed new interest phase 1 from this release

---

packages/blockchain-wallet-v4/src/network/api/kvStore/index.js

fix(metadata): actually catch err and continue execution

---

packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.ts

https://blockc.slack.com/archives/C011JDHCSEB/p1620788510032900

fix(eth): responsive is sufficient eth for erc20

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx

Fix min/max on fresh new account
Create new wallet and the try to buy (SDD or non SDD) should apply on both

feat(buy): fixed override of min/max amount if it's not changed

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware.ts

Removing page and modal events

fix(analytics): removing page and modal events

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx

This PR resolve issue with conversion minor string and double precise amounts and to properly compare them
Go over buy flow try to buy crypto with amount from FIAT account

Max buy amount with limit FIAT account

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/model.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/template.success.tsx

This PR solve smaller UI glitches
This line was overlapping content
after EDD check is applied user will not see above component

feat(edd): fixed css issue with overlay text over bottom line and hide top component in case of EDD

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx

This is cherry picked changes for min/max logic
Go over buy flow try to buy crypto with amount from FIAT account

Min max fix for 4.49

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware.ts
packages/blockchain-wallet-v4-frontend/src/utils/queuevent.ts

feat(segment): adding events for onboarding and simple buy (v1)

---

packages/blockchain-wallet-v4/src/network/api/kvStore/index.js
packages/blockchain-wallet-v4/src/types/KVStoreEntry.js
packages/blockchain-wallet-v4/src/types/KVStoreEntry.spec.ts

fix(metadata): naming and refactor of parse, use padded as default

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PreviewSell/index.tsx

This PR implements new changes on checkout sell for custodial and non custodial
Go over Sell flow

feat(brokerage ux): implemented checkout sell for non custodial and custodial

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware.ts

Waiting for the BE to fix it before we merge

feat(analytics): adding identity for publish calls

---

packages/blockchain-wallet-v4-frontend/src/modals/Eth/TransferEth/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx

Fixes this typo from tx feed. 

fix(tx feed): typo

---

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Wallet/InterestPromo/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Wallet/InterestPromo/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Wallet/InterestPromo/template.tsx
packages/blockchain-wallet-v4-frontend/src/modals/index.tsx
packages/blockchain-wallet-v4-frontend/src/providers/TranslationsProvider/index.js
packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/EmailAddress/template.success.js

Fix rendering of HTML tags inside app translations
Go to any page where we use HTML inside translations

feat(react intl): fixed rendering of html translations

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/ActionButton/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/Payment/model.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/template.failure.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/template.unsupported.tsx

This PR solves problem we had with changing payment method and aligning it with mobile app
Detailed steps are explained in a ticket

feat(buy): allow users to change payment method always

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware.ts

fix(analytics): adding id to segment identify

---

packages/blockchain-wallet-v4-frontend/src/modals/Borrow/BorrowForm/template.loading.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Borrow/RepayLoanForm/template.loading.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.loading.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.loading.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.loading.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/InterestHistory/template.loading.tsx
packages/blockchain-wallet-v4/src/network/api/interest/index.ts

This PR loads EDD status after user send withdraw/deposit of interest
Details are attached to ticket

feat(edd): load EDD status after we do submit it

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Authorize/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Authorize/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkFromExchangeAccount/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/Authorize/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/Preferences/CryptoLinkHandling/index.js

Fixes issue from react-intl update where links from FormattedHtmlMessages weren't being updated correctly. 

fix(intl): fix a tags for fomatted messages

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/ActionButton/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx

feat(buy): changed naming to be bounds not bounce

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/selectors.ts

This PR solve issue with fresh new wallet and loading API data since user do not exists at that point of time
Create new wallet, go to trading limits settings

feat(trading limits): fixed expected value to be empty in case of brand new wallet

---

packages/blockchain-wallet-v4/src/coinSelection/coin.js
packages/blockchain-wallet-v4/src/coinSelection/coinSelection.spec.js
packages/blockchain-wallet-v4/src/coinSelection/index.js

fix(segwit): different change output types for burn

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/validation.tsx

This PR fix credit card limits
Go over buy flow

feat(buy): min/max credit card fix

---

packages/blockchain-wallet-v4-frontend/src/data/components/exchange/services.ts

feat(intellisense): adds intellisense friendly comments for convertBaseToStandard and convertStandardToBase methods describing how they work

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts

Fixes FWLT-1417. 
I believe `payment.build()` won't work if 'from' account is custodial, because payment will try to build using unspents, but they will be missing from a custodial send. `Payment.build()` was added recently to make sure we were calculating network fees in real time for BTC send, accounting for any additional inputs being added to the transaction as the amount was changing dynamically.
I added a check to only update the payment with `payment.build()` if it's not a custodial wallet. 

fix(interest): remove payment.build for custodial payments

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx

This PR resolve copy issue
You need a wallet with interest, try to do big amount transfer(EDD need flag from API) then go over settings

feat(edd): fixed copy of gold level

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.ts
packages/blockchain-wallet-v4/src/network/api/simpleBuy/index.ts
packages/blockchain-wallet-v4/src/utils/bch.js

fix(send receive): bch address

---

packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/coins/btc.tsx

fix(imported addrs): request screen balance

---

packages/blockchain-wallet-v4-frontend/src/components/Form/CoinBalanceDropdown/selectors.ts

Hotfix for releasing AAVE and YFI for interest

fix(interest): enable interest deposits for aave and yfi

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CryptoSelection/CryptoSelector/SellEmptyState/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/NoHoldings/index.tsx

feat(buy): confirmation screen copy has been fixed

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx

Style fixes for swap preview "exchange rate" question mark icon.

fix(swap): fix icon color and alignment

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkFromExchangeAccount/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PreviewSell/index.tsx

This PR fix disclaimer rendering

feat(sell): fixed disclaimer error

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/components/FeeBreakdownBox.tsx

fix(swap): style tweaks for fees box

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PreviewSell/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/index.tsx

This PR resolve issues on sell checkout page
Go over sell flow and check checkout page

feat(sell): fixed checkout network currency and disclaimer text

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/AutoDisconnection/index.js
packages/blockchain-wallet-v4-frontend/src/modals/Settings/AutoDisconnection/template.js
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OpenBankingConnect/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OpenBankingConnect/template.success.tsx

Cancel order PIS flow

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx

Small design changes to the swap confirm fees box

fix(swap): small design changes

---

packages/blockchain-wallet-v4/src/types/HDAccount.spec.ts
packages/blockchain-wallet-v4/src/types/HDAccount.ts

fix(btc): derivation type vs type fix

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx

Updates the "Learn More" and "Refund Policy" links 

fix(swap): update learn more links

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4/src/redux/wallet/sagas.ts

Separated update mnemonic code into its own saga
Wrapped saga in a try/catch so login continues even if update mnemonic fails

fix(update-mnemonic-call): wrap call in try catch to handle error better

---

packages/blockchain-wallet-v4-frontend/src/components/QRCodeWrapper/index.tsx

Fixes level of correction for QR code, login QR code for mobile wallet authorization. 

fix(qr-code): level m correction

---

packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PreviewSell/index.tsx

This PR solve issue with wrong article in use
Go over sell flow and check checkout page article should point to proper one (listed in ticket)

feat(sell): fixed article id for more crypto info

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/onboarding/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/refresh/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/index.tsx

This PR solve issue by calling API for tier 0 wallets
Create new wallet open settings trading limits, after that close flyout and try to open buy flow - should be able to open it

feat(buy): fixed opening of modals for tier 0 wallets

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

fix(kyc-reset): remove unneeded comments

---

packages/blockchain-wallet-v4-frontend/src/components/Send/ExchangePromo/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Send/LockTime/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Send/LockTime/selectors.ts
packages/blockchain-wallet-v4-frontend/src/components/Send/LockTime/template.tsx
packages/blockchain-wallet-v4-frontend/src/components/Send/RecoveryPhrase/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Send/index.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/send/actions.ts
packages/blockchain-wallet-v4-frontend/src/data/components/send/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/withdraw/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/LockTimeTooltip/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/EnterAmount/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/index.js
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/selectors.js
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.loading.js
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/index.js
packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/selectors.js
packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/index.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/selectors.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/validationMessages.js
packages/blockchain-wallet-v4/src/network/api/custodial/index.ts

This PR haev mainly eslint fixes

feat(send): eslint fixes and make sure that we show proper lock message

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx

In case that user is tier zero we have to make sure that current tier is set to proper one
Create a new wallet and go to trading limits

feat(trading limits): fixed issue when user is tier 0

---

packages/blockchain-wallet-v4-frontend/src/components/Announcements/Static/index.js
packages/blockchain-wallet-v4-frontend/src/components/Announcements/Static/template.email.tsx

This PR fix error when user login to wallet 

feat(announcments): fixed error after login

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

fix(kyc-reset): if user has just been created dont reset kyc

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

Adds login via mobile app option to password screen

fix(login): add login via mobile app to password page

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/CheckEmail/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

Refreshes captcha token required for login emails more frequently (when clicking back arrows in flow and when requesting email to be reset). Hoping this prevents the issue of following recaptcha errors:
EXPIRED - The user verification token had expired.
DUPE - The user verification had already been seen.

fix(captcha): new captcha more freq to prevent dupes or exp error

---

.well-known/apple-app-site-association
packages/blockchain-wallet-v4-frontend/src/components/Form/PasswordBox/index.js
packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterEmailOrGuid/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterPassword/index.tsx

1. Add autofocus to email/guid field + password field when loading login page (had to add autofocus to PasswordBox component props)
2. Updates app association file for iOS team

fix(sso): app assoication file and autofocus to email password fields

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

For SSO login verification email:
Changes where a new recaptcha token is initialized to avoid any duplicate errors.

fix(sso-captcha): change when new captcha is generated

---

packages/blockchain-wallet-v4-frontend/src/scenes/ResetWallet2fa/index.tsx

Fixes #watchkeeper issue of 2FA form requests not being sent. Wrong var being used to generate captcha key

fix(reset-2fa): fix captcha key var

---

packages/blockchain-wallet-v4/src/network/api/wallet/index.ts

fix(reset-2fa): add sitekey to request

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts

fix(brokerage): fixes payload for adding bank saga and removes unused code

---

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/SecondStep/index.js

Hotfix that went into master, allows user to continue with recovery process with a valid phrase, even if it doesn't match any blockchain guids. 

fix(recovery): allow user to restore wallet without metadata

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/template.failure.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/template.upgrade.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/InitSwapForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/InitSwapForm/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/OrderDetails/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/SuccessfulSwap/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/UpgradePrompt/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/selectors.ts

feat(swap): lint styling changed

---

packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts

Erc20 related fixes

---

packages/blockchain-wallet-v4-frontend/src/data/prices/sagas.ts
packages/blockchain-wallet-v4/src/network/api/coin/index.ts

fix(prices): remove hardcoded prices list

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/data/components/settings/types.ts
packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/template.unsupported.tsx
packages/blockchain-wallet-v4/src/network/api/custodial/index.ts
packages/blockchain-wallet-v4/src/network/api/swap/index.ts
packages/blockchain-wallet-v4/src/network/api/swap/types.ts
packages/blockchain-wallet-v4/src/remote/types.ts

In a case of non eligible region we show proper message instead of swap flow

feat(swap): implemented case when user is not eligible to show proper error page

---

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/selectors.ts

feat(home, nav): sort coin by balance

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/model.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/types.ts
packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/actions.ts
packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/OpenBankingConnect/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/LinkedPaymentAccounts/Accounts/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OpenBankingConnect/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OpenBankingConnect/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Methods/LinkBank/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/PaymentMethods/Methods/index.tsx

This PR update labels in case of PIS flow

feat(simple buy): added different labels fro PIS flow when linking bank

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx

This PR fix issue with coin picker on swap

feat(swap): we do not need to call this one since we call it on init swap page

---

packages/blockchain-wallet-v4-frontend/src/modals/index.tsx

fix(nabu-conflict-modal): and modal back to index file

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/store/index.js
packages/blockchain-wallet-v4/src/redux/kvStore/eth/sagas.js

feat(erc20): release prep

---

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/template.header.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/template.menu.tsx

Bringing changes to release
T0 wallet go to earn interest page, should see proper info box to verify gold

feat(edd of interest): fixed fall back compatibility in case that user is T0

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

Hotfix branch, has kyc reset re-verification flow fixes already in development branch. 

hotfix(kyc-reset): cherry picked changes for kyc reset reverification flow

---

packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/SecondStep/selectors.ts

Hotfix/erc20 send fee UI bug

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/selectors.ts

Get all coin prices on prices page

fix(prices): show prices for all coins on window

---

packages/blockchain-wallet-v4/src/redux/data/eth/selectors.js

fix(erc20): at bounds is a boolean, should default to false

---

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts
packages/blockchain-wallet-v4/src/redux/common/eth/selectors.js

fix(erc20): interest balances display on home and total

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/middleware/autoDisconnection.js

this code was no longer needed (guessing it's removal was missed in previous refactor). all the magic is already wired in the autoDisconnection middleware

fix(logout): remove unneeded logout listener code in auth saga

---

packages/blockchain-wallet-v4-frontend/src/utils/helpers.ts

fix(collapse): dont collapse text if undefined

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx

fix(swap): fixes issue where swap max button was filling in incorrect values causing api errors

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts

Removes incorrect kyc state check.

fix(kyc-reset): catching kycstate none too early

---

packages/blockchain-wallet-v4/src/redux/wallet/sagas.ts

fix(restore): check bech32 correctly

---

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts

fix(erc20): include custodial only erc20s in top balance

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/model.tsx

fix(interest): withdraw custodial only coins

---

packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Transactions/DownloadTransactions/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/NonCustodialTx/Confirmations/index.tsx
packages/blockchain-wallet-v4/src/redux/walletOptions/types.ts

fix(assets): parent chain is optional

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.ts
packages/blockchain-wallet-v4/src/network/api/wallet/index.ts
packages/blockchain-wallet-v4/src/redux/wallet/actionTypes.ts
packages/blockchain-wallet-v4/src/redux/wallet/actions.ts
packages/blockchain-wallet-v4/src/redux/wallet/sagaRegister.ts
packages/blockchain-wallet-v4/src/redux/wallet/sagas.ts

WS-104: We want to trigger an email notification for every non-custodial tx being sent by the wallet. 
Also some linting fixes, had to re-order some function in xlm saga.

feat(send): add email notification for nc txs

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Notifications/index.tsx

Grammer/styles on these flyout screens

fix(recurring buy): fixes grammer and design issues with explainer text

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/FrequencyScreen.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/recurringBuy/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/index.tsx

fix(recurring buy): add one time option to frequency screen and fix back button

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SBOrderTx/model.tsx

fix(recurring buy): adds sb updatedAt info to transaction list for non-finished orders for better context for users

---

.storybook/main.js
.storybook/preview.js
packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuyDetails.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuyDetails.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuyRemoveConfirm.tsx
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Details/index.tsx

Fix close button
Fix keep button

fix(recurring buy): fix close and keep buttons on recurring buy details modal

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuy/GettingStarted.tsx

fix(recurring buy): update learn more link

---

packages/blockchain-wallet-v4-frontend/src/data/auth/actions.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/session/selectors.js
packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

Hotfix for issue when we regenerate a new session token for 2fa authorization if we don't yet have one for their guid. 

hotfix(login-2fa): setting new session token with 2fa login

---

packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/selectors.ts

fix(coin list): filter out unknown coinfigs

---

packages/blockchain-wallet-v4/src/redux/data/coins/actions.ts
packages/blockchain-wallet-v4/src/redux/data/coins/reducers.ts
packages/blockchain-wallet-v4/src/redux/data/coins/sagas.ts
packages/blockchain-wallet-v4/src/redux/data/coins/types.ts

fix(tx): scroll

---

packages/blockchain-wallet-v4-frontend/src/data/session/selectors.js

Flips defaultTo case, will always choose emailSession if there is one. 

fix(2fa-login): prioritize email session token

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

Added feature flag on top of country signup
Try to signup wallet country dropdown should be hidden

feat(signup): put country logic on signup under feature flag

---

packages/blockchain-wallet-v4-frontend/src/data/components/recurringBuy/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Scheduler/index.tsx

fix(simple buy): fixes issue with calling type of undefined error

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/index.tsx

fixes keys encoded in base64 JSON object in magic email link. legacy email link flag still on in production, so doesn't change anything live yet.

fix(magic-link): correct key for magic link json data

---

packages/blockchain-wallet-v4/src/redux/wallet/sagas.ts

Fixes issue where wallet was stuck in loading state after nc sends. This had to do with how i was calling the api to trigger private key wallet send notifications.

fix(nc-email): fixes api call for alert endpoint

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/actions.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

fix(prices): add logic to open buy flyout directly to the coins enter amount screen when appropriate

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx

This PR solve issue with trading limits gold level badge
Use acount which have gold level make sure that trading limits do not have badge to need more info

feat(edd): fixed issue with proper rendering of states under trading limits

---

packages/blockchain-wallet-v4/src/network/api/eth/index.ts
packages/blockchain-wallet-v4/src/network/api/misc/index.ts
packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.ts
packages/blockchain-wallet-v4/src/signer/eth.js

https://blockchain.atlassian.net/browse/FWN-743

fix(erc20): check contract before sending

---

package.json
packages/blockchain-wallet-v4-frontend/src/data/session/selectors.js
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/selectors.ts

Release to master

---

packages/blockchain-wallet-v4-frontend/src/data/components/recurringBuy/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/recurringBuy/types.ts
packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Details/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/RecurringBuys/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx

segment even when the user clicks the view details button

feat(recurring buy): adds rb view details event

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuy/FrequencyScreen.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuy/FrequencyScreen.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/OptionRightAction.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/OptionRightAction.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/index.ts
packages/blockchain-wallet-v4-frontend/src/data/components/recurringBuy/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Scheduler/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Scheduler/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/OrderSummary/index.tsx

Changing the designs for recurring buy options in order to be more user friendly

feat(recurring buy): ui changes for clarifying which methods are available for recurring buy

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

feat(ping manifest): after catch

---

packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Scheduler/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/index.tsx

fix(recurring buy): move payment info request out of scheduler to fix issue with resetting period back to one time

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/CloudRecovery/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryOptions/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryPhrase/FirstStep/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/StepOne/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/StepTwo/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/model.tsx

Add param to loginRoutineSaga when it is called from restore. This is already in development and 4.55 release branch. 

fix(recovery): add recovery param to login routine saga

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.tsx
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

Potential hot fix for device mismatch error.

fix(session-mismatch): use same email session token if it exists

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.tsx

Updated copy and clearer instructions for device mismatch issue

fix(copy): device mismatch toast

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

Adds recovery checks back to login routine saga. 

fix(login-saga): add recovery checks back

---

packages/blockchain-wallet-v4/src/redux/data/eth/reducers.ts

This was throwing an error when clicking the gen report button. 

fix(eth txs): fixes issue where app throws when trying to download your eth transactions

---

packages/blockchain-info-components/src/Modals/ModalHeader.js
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkToExchangeAccount/template.error.js
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkToExchangeAccount/template.loading.js
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkToExchangeAccount/template.notasked.js
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/LinkToExchangeAccount/template.success.js

This PR fix close button
Go over try to link exchange

feat(exchange): allow users to close modal

---

packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/APIAccess/index.js

Added missing space between text and link
Go to security-center/advanced page

feat(security): added missing space

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/template.success.tsx

This PR fix some UI and UX issues on signup page
Go over signup flow

feat(sigup): fixed issue with pre-fill country on info and additional details KYC step

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/components/SiftScience/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Verify/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Verify/selectors.ts
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

- Removes unused feature flag selectors
- Syncs feature flags states with targeted app state

Chore(Feature Flags): Cleanup

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

For the mobile team to test message passing
- Hopefully it works

feat(debug): mobile sso debug

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx

fix(interest): slice issue

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SwapOrderTx/model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx

fix(activity feed): change some text, add a useCallback and change date format

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/NonCustodialTx/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx

feat(activity feed): for btc/bch sends show the address next to the to account name

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts

fix(interest): amount to fixed

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

iOS and Android testing message passing
Button click works

feat(sso-debug): finish ios and android implementation that should work

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/NonCustodialTx/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx

feat(activity feed): for btc/bch show the address next to the to account name

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

Set default currency based on country
Create a new wallet from some EU country default currency should be EUR

feat(signup): fetch settings after we update wallet currency

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx
packages/blockchain-wallet-v4/src/network/api/swap/types.ts

fix(deposits): adds min max to payment method limits type and checks that instead of daily.available for bank deposits

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
packages/blockchain-wallet-v4/src/network/api/swap/types.ts

Additional fixes for the broken deposit/limits issue.

feat(payment methods): remove checks for daily available limits on bank transfers as its being deprecated in the api

---

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx

fix(bank linking): fixes issue with bank linking modal in general settings

---

package.json
packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx
packages/blockchain-wallet-v4/src/network/api/swap/types.ts

Hotifx v4.55.8

---

packages/blockchain-wallet-v4-frontend/src/data/components/settings/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modules/settings/sagas.js

fix(rates): fetch rates when user changes currency

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx

* update interest terms link from `/borrow-terms` to `/reward-terms`

fix(legal-link): update interest legal link

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/types.ts

Implemented proper calling of events

feat(signup by country): added proper events calling on signup

---

packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/types.ts

Fixed issue with proper select country
Go over signup and change country to be US state should be visible

feat(country on signup): fixed issue with select country to show state in case of US

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4/src/exchange/index.ts

fix(conversion): round coin to fiat down

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

Fixes how we get mnemonic from the payload. Should fix FWN-830

fix(recovery): gets mnemonic correctly from action payload

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/EmailVerification/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/EmailVerification/selectors.ts

feat(trading limits): load sdd eligible on rendering verify emails step since it's dependent on it

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

Based on country we do set user's currency
Try over signup process change country and later currency should be based on country

feat(signup): set currency based on country after signup with country

---

packages/blockchain-wallet-v4/src/utils/btc.js

fix(private key): fix left padding and compress keypair

---

package.json
packages/blockchain-wallet-v4/src/utils/btc.js

release to dev

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/conversions.tsx

Fixed issue with exponentiation operator and calculation
Go over interest try to transfer some money and see calculation works

feat(interest): fixed issue with calculations of interest values

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/UploadAndVerify.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/interestUploadDocument/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx

improved flow to show last step, prevent showing of edd in case that files are already processed and send properly file to API

chore(edd of interest): several improvements

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

Delete the SSO dummy feature flag used to test message passing between mobile and web.
yarn start:staging works

chore(sso): delete sso dummy feature flag

---

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryOptions/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/index.tsx

Disables cloud recovery option is 'has_cloud_backup' is false from email magic link. 
FWN-782/

fix(recovery-option): disable cloud recovery is hascloudbackup is false

---

packages/blockchain-wallet-v4-frontend/src/data/components/interestUploadDocument/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/InterestUploadDocuments/AdditionalInformation/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/InterestUploadDocuments/selectors.ts

Fixed proper usage of user residence country from nabu
Create an wallet with US based, go over interest deposit and new EDD for interest will prompt SSN required input

feat(edd for interest): fixed detect country and submit of US based account data

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/AdditionalInformation.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/RecurringBuy/FrequencyScreen.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/services/forms/utils.js
packages/blockchain-wallet-v4-frontend/src/services/forms/utils.spec.js
packages/blockchain-wallet-v4-frontend/src/services/forms/validators.js

I fixed storybooks rendering and also added small improvements
Try deposit/withdraw of interest

feat(edd of interest): limit additional info to min 4 characters

---

packages/blockchain-wallet-v4-frontend/src/components/Rows/index.ts

This PR resolve export issue and fix rendering of storybooks

chore(storybook): fixed rendering of storybook

---

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryOptions/index.tsx

Only change recovery step if hasCloudBackup === true. Fix for FWN-804

fix(cloud-recovery): return if has cloud backup is false

---

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

fix(erc20): tx history fix

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/AdditionalInformation.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/AdditionalInformation.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/interestUploadDocument/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/InterestUploadDocuments/AdditionalInformation/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/InterestUploadDocuments/index.tsx
packages/blockchain-wallet-v4-frontend/src/services/forms/utils.js
packages/blockchain-wallet-v4-frontend/src/services/forms/validators.js

This PR updates logic for validation of SSN number, beside of that logic for sending additional info is now on additional info page, smaller changes on storybook to easer visual testing of additional info step
Try interest withdrawal/deposit of big amounts

feat(eed for interest): implemented SSN validation to be aligned with BE, added submit of data on additional info page

---

packages/blockchain-wallet-v4-frontend/src/components/Form/TextWithQRScanner/index.tsx

fix(ts): err

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/AdditionalInformation.stories.tsx

feat(edd for interest): fixed imports to use aliases

---

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxCountry/index.tsx

fix(missing country): added Russia

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/validation.tsx

update interest to use `displaySymbol`

fix(interest): update to use displayName for tickers

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinChart/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinChart/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CoinPerformance/CoinPrices/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/CustodialTx/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/components/index.tsx

https://blockchain.atlassian.net/browse/FWN-845

fix(tx list): display symbol fixes

---

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxBchAddresses/selectors.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxBtcAddresses/selectors.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxCoinAddresses/selectors.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxEthAddresses/selectors.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxXlmAddresses/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/coins/utils.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts

fix(interest): add to wallet balance dropdown for custodial only coins

---

packages/blockchain-wallet-v4-frontend/src/data/cache/slice.ts

fix(announcements): fix rtk issue

---

packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/template.success.js

fix(xlm): memo field for trading acct

---

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts

Noticed fiats had stopped showing up on home/holdings

fix(fiat): show in holdings section

---

packages/blockchain-wallet-v4-frontend/src/data/components/recurringBuy/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/RecurringBuys/Frequency/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SimpleBuy/Frequency/index.tsx

fix(recurring buy): fixes issue to support recurring buys for credit cards

---

packages/blockchain-wallet-v4-frontend/src/data/auth/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/NewVersionAvailable/index.tsx

fix(new version): when new version is available just hard reload

---

packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/simpleBuy/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/index.tsx

This PR fix issue we had with calling  non existing function
Go to some fiat currency and try deposit flow

fix(deposit): fixed issue with call of non existing function

---

packages/blockchain-wallet-v4-frontend/src/data/auth/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/NewVersionAvailable/index.tsx

fix(new version): just hard reload on new app versions

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

/prices doesnt lag
Scrolled and it doesn't lag
https://www.loom.com/share/61ead5e90b1747a6883e4beb47fa968e

Fix/fwn 973/price lag 2

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

fix(prices): align columns

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
packages/blockchain-wallet-v4/src/network/api/interest/index.ts

This PR solves the problem with not calling proper API endpoint for deposit
- Create new T2 account
- with some huge amount of crypto
- Open Earn rewards
- Click on earn rewards of desired coin
- Click on transfer button
- Select account with huge amount
- Enter big number, you should see prompt like

feat(edd): deposit flow now use proper API endpoint and logic around it

---

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

fix(eth err): if no eth addr wrap error

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/components/Send/LockTime/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Send/LockTime/selectors.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/selectors.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/template.success.tsx
packages/blockchain-wallet-v4/src/redux/settings/model.ts
packages/blockchain-wallet-v4/src/redux/settings/types.ts
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

chore(feature flag): wrap on hold funds feature in feature flag

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/schemas.ts

To be honest, I'm not sure if this is the correct default value, but it seems to be working again: https://etherscan.io/tx/0x97f2bb7e15be74bcb0d8606664411a05bda6d76ac7639943cd07559560c90da0

fix(nfts): fix encoding call

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/index.ts
packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(nfts-gas-estimations): dynamic gas limits via ethersjs

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx

Fixes:
https://blockchain.atlassian.net/browse/FWN-994
https://www.loom.com/share/5325f47e85164f66abc093784f4081f7

fix(prices): fixes weird zoom on staging url (sorry named the branch wrong)

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/OnHold.tsx

fix(on hold): add the year to on hold date

---

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/validation.js
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/validation.js
packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/validation.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/validation.js

feat(seamless limits): adopted structure to new API changes

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/actions.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/selectors.ts

1. if there is balance && containers custodialwalletbalance show buy sell and swap
2. if no balance && containers custodialwalletbalance show buy and swap - NO sell 
3. Price change column shows 0 rather than NaN

fix(prices-table): fix actions and price change columns

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/index.ts
packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(nft-sell-orders): makerRelayerFees fixed

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/VerificationMobile/index.tsx

Fixes mobile app QR code scanning UI and adds a refresh link to show code again after scanned. 

fix(mobile-login): add refresh code link to show qr code after scan

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

feat(ceeur): remove gb from list

---

packages/blockchain-wallet-v4/src/network/api/misc/index.ts

Changes Product parameter to uppercase for /auth/email-reminder endpoint. 

fix(email-login): wallet param to uppercase

---

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxCoinAddresses/selectors.ts

fix(tx balance dropdown): show correct coin balance

---

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/FirstStep/validation.js
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/FirstStep/validation.js
packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/FirstStep/validation.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/FirstStep/validation.js

This PR prevent send for to error in case that there are no limits
Try to send some crypto from Trading to PK account

feat(seamless limits): prevent error to ocure in case of non existing limits

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/index.ts
packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

feat(nft-erc20-payments): ERC20 Payments working

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(nft-replacement-patterns): Removed hardcoded replacement patterns

---

packages/blockchain-wallet-v4-frontend/src/components/Form/TabMenuNftSaleType/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/TabMenuNftSaleType/template.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/ShowAsset/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/index.tsx

feat(nfts): start on mark for sale form

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Header/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Marketplace/index.tsx

feat(nfts): refetch orders

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/abis.ts
packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

Added ERC721 support to encodeSell

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/template.success.tsx

fix(dev): misc type errors

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(nft-seller-points): removed excess point addition

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/ShowAsset/CancelListing/cta.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Marketplace/MarketForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/YourCollection/index.tsx
packages/blockchain-wallet-v4/src/network/api/nfts/index.ts

fix(nfts): user can sell

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterEmailOrGuid/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx

Responsiveness in login screens so it looks acceptable on mobile devices

fix(login): style for mobile devices

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/Veriff/template.failure.tsx

This PR removes server response message
Try to verify gold and fail, it will ended up with this screen

feat(veriff): remove server error message to not be shown to users

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(erc721 approval): isApprovedForAll returns bool

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(estimate-gas-limits): gas limits increased by 20%

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

This PR fix proper message to be shown in case of sell not enough coins
Use T3 account and test sell, try to enter more than you have, proper error message should popus up

feat(seamles limits): added case for showing proper sell error message

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx

feat(seamless limits): fixed typos on swap flow

---

packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx

feat(seamless limits): removed space between value and currency

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/UpgradeToGold.tsx

feat(seamless limits): improve button styling

---

packages/blockchain-wallet-v4/src/redux/data/btc/sagas.ts

This PR solve issue when we have imported BTC address
Try to download transaction history of imported BTC address

feat(download transactions): fixed issue with imported BTC address

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(nfts): use diff prxy registry addr for testnet

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/template.success.tsx

Remove trading limits currency selection for now

feat(trading limits currency): reverting back trading limits currency for this release

---

package.json
packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/CircularProgressBar/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/index.tsx
yarn.lock

This PR brings usage of theme colors and also move dependency to proper location

feat(complete profile): added usage of colors from theme, also moved dependency to proper location

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/UpgradeToGold.tsx
packages/blockchain-wallet-v4-frontend/src/services/custodial/index.ts
packages/blockchain-wallet-v4/src/network/api/custodial/types.ts

This PR add proper message data for suggested amount

feat(seamless limits): show proper suggested value and period for send flow

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.utils.ts
packages/blockchain-wallet-v4-frontend/src/data/components/send/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts
packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.ts
packages/blockchain-wallet-v4/src/signer/eth.js
packages/blockchain-wallet-v4/src/signer/eth.spec.js

feat(Eth-Savings): refactored, need to include test cases

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/PriceMovement/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/PriceMovement/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/selectors.ts

Fix/fwn 1037/api layout calls

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

feat(seamless limits): fixed error message to be correct one

---

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx
packages/blockchain-wallet-v4/src/network/api/index.ts
packages/blockchain-wallet-v4/src/network/api/nfts/index.ts
packages/blockchain-wallet-v4/src/network/api/nfts/types.ts

feat(nfts): move endpoints to internal service

---

packages/blockchain-wallet-v4/src/redux/kvStore/eth/sagas.js

Users have reported a missing account in the ethereum accounts list.

fix(eth): fix empty eth accounts list

---

packages/blockchain-wallet-v4-frontend/src/scenes/InterestHistory/DownloadTransactions/index.tsx

Defence interest download transactions 

feat(interest): add fallback for rendering of report

---

packages/blockchain-wallet-v4-frontend/src/scenes/InterestHistory/DownloadTransactions/index.tsx

feat(interest): removed test code and added proper comment

---

package.json
packages/blockchain-wallet-v4-frontend/src/index.html
packages/blockchain-wallet-v4-frontend/webpackBuilder.js

feat(gtm): add google tag manager support

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

Make sure that available button is always shown and remove "not enough funds"

Fix/fwn 998/tb correct designs

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/UpgradeNow/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/UpgradeNow/template.success.tsx

feat(trading limits): close modals and open KYC modal

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx

This PR solve issue with passing a proper value to next step

feat(buy sell): pass proper orderType value

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/model.tsx

feat(swap): fixed issue with comparison and fixed typo

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

Explicitly checks if product auth option is wallet in case where there's a stored guid in the cache. 

fix(initialize-login): add product check to store guid case

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/index.tsx
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

Added feature flag for trading limits

feat(trading currency): added feature flag to prevent rendering of trading limits

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/Trade.tsx
packages/blockchain-wallet-v4-frontend/src/modals/index.tsx
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

feat(trading currency): moved KYC modals to be always rendered on top

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/components/FeeBreakdownBox.tsx
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

hot fix ts issue and clean up code

Feat/pricing - hotfixes

---

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxCountry/index.tsx

feat(signup by country): japan users can't signup

---

packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

feat(trading currency): use proper feature flag name

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/Navbar.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/Navbar.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/index.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/template.tsx

fix(navbar): fix dapps and nfts nav items and tweek styles

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx

feat: add Purchase to checkout screen

---

packages/blockchain-wallet-v4-frontend/src/modals/Trade/index.tsx

Fix trading currency modal to be shown

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx

fix(log-in): sign in create your account

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx

feat(trading currency): use trading currency if it's set

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/index.tsx

fix(flyouts): fixes issue with multiple modals

---

packages/blockchain-wallet-v4-frontend/src/modals/Trade/index.tsx

fix(trade modal): speed optimization

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Marketplace/MarketForm/index.tsx
packages/blockchain-wallet-v4/src/network/api/nfts/index.ts

fix(nfts): change 7 day to 1 day vol

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Footer.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileNav.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/Navbar.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/layoutWallet/slice.js
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/template.tsx

fix(navbar): fix mobile navbar styles

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/index.tsx

feat(complete profile): close modal every time we start with something new

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx

All payment methods will show the blockchain fees
Tried different payment methods, had fees

feat: blockchain fee on all payment methods

---

packages/blockchain-wallet-v4-frontend/src/data/components/layoutWallet/slice.js

fix(layout): default left menubar to closed when in mobile view mode

---

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxCountry/index.tsx

fix(country selector): fixed issue with file formatting and lost of country icons

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/validation.tsx

fix: fix quote amounts

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

fixes no quote found error
both buy and sell

fix(CON-2584): fix no quote found on selling trades

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/selectors.ts
packages/blockchain-wallet-v4/src/network/api/buySell/index.ts
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

This PR brings new api endpoint to be used to see did user ever bought any crypto

feat(buyer hand hold): use proper API for accumulated spent all the time

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx

Default toggled on and can toggle

fix(FWN-1096): default on and fee toggle

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/selectors.ts
packages/blockchain-wallet-v4-frontend/src/services/search/index.ts

sort the currencies list with the levenshtein algorithm. sort by exact currency first, and similar currencies are sorted by balance

Fix/fwn 1093/tb asset search

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

feat(buy sell): prevent switch currency

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx

User have to be able to select trading currency, when use buy button from currency

feat(trading currencies): force user to select trading currency

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

Sell orders use old quote rather than new buy quote.

fix(quote): use old quote for sell orders

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

Reverts blockchain/blockchain-wallet-v4-frontend#4062

Revert "hotfix(buy/sell): 4.61-2 to 4.62"

---

package.json
packages/blockchain-wallet-v4-frontend/package.json
yarn.lock

fix(package): add module to original developers repo

---

package.json
packages/blockchain-wallet-v4-frontend/package.json
yarn.lock

fix(package): add qr.js to resolutions in package json

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/template.tsx

feat(trading currency): allow users to select trading currency

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx

fix(swap: enter amount error styles

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CeloEURRewards/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

refactor(announcement): change ceur announcement

---

packages/blockchain-wallet-v4-frontend/src/scenes/Airdrops/StxAirdrop/model.tsx

fix(stx airdrop): use coin display function

---

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

fix(eth): check the correct erc20 contract addr

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/BuyMoreLine.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/BuyMoreLine.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/template.tsx

Implemented missing banner to let user to buy more crypto

feat(seamless limits): fixed issue with send crypto, added missing banner

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

fix(product-param): convert to uppercase so param is ready correctly

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/BankDeposit/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/BankWire/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/LinkBank/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/index.tsx
packages/blockchain-wallet-v4/src/exchange/currencies/EUR.ts
packages/blockchain-wallet-v4/src/exchange/currencies/GBP.ts
packages/blockchain-wallet-v4/src/exchange/currencies/USD.ts

feat(payment-name-change): Change payment names

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

feat(seamless limits): improved logic for buy flow to cover case over balance

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterPasswordExchange/index.tsx

fix(error-message): wrong password error for exchange

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/LinkItem/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/selectors.ts

feat(buyer hand hold): show processing state

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(offers and orders): fix recipient addr and change fees

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts

Adding in correct address for rinkeby WETH for cancel offer

fix(nfts): add in weth address for cancel order

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts

- Adds `site_redirect` param to analytics events to distinguish between wallet and exchange login
- Adds exchange login events

fix(analytics): add product information to events

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

Improved UX of complete profile banner, updated labels

feat(buyer hand hold): improved banner logic and UX

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx

feat(limits): trading limits are in minor we have to properly format values

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/validation.tsx

fix(buysell): add flexible pricing style buyQuote to max amount validation

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/LinkItem/model.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/selectors.ts

feat(buyer hand hold): updated copy and logic for banner to show proper progress

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

fix(quotes): refresh quote before old one expires

---

packages/blockchain-wallet-v4-frontend/src/data/misc/sagas.ts

- Changes app refresh check interval to 15 seconds
- Only ping manifest if window is active

feat(manifest): only ping if current window is active

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

feat(buyer hands hold): prevent calling accumulated data before user is ready

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

feat(buyer hand hold): prevent calling endpoint before user data are ready

---

packages/blockchain-wallet-v4/src/network/api/misc/index.ts

Fix email-reminder api call to return error. 

fix(email-reminder): fix api call to return error

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/SignupLanding/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx
packages/blockchain-wallet-v4/src/network/api/profile/index.ts

Go over signup and make sure that country is not prefilled

feat(signup): prevent auto-select country based on geo location

---

packages/blockchain-wallet-v4/src/network/api/nfts/index.ts

fix(nfts): change route to match our api route

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/AccountUnification/MergeAccountConfirm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/AccountUnification/UpgradePassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterEmail/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterPasswordExchange/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/Institutional/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/TwoFA/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/CheckEmail/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterEmailOrGuid/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPasswordWallet/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/TwoFA/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/BackArrowHeader/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/LoginSceneFooter/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/NeedHelpLink/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/ProductTabMenu/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/SignupLink/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/UnsupportedBrowser/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx

refactor(sso): break up model file into components

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/ThreeDSHandlerCheckoutDotCom/index.tsx

feat(add card): show error in case of rejected card

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/ThreeDSHandlerCheckoutDotCom/index.tsx

feat(add card): display error message in case of error adding a card

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardEverypay/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BillingAddress/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/template.success.tsx

feat(address): added optional beside address line 2

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/index.tsx

Fixed CTA button to redirect to buy crypto

feat(interest): allow users to buy more coins

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/LoginSceneFooter/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx

Phishing warning wasn't being rendered, change from component to function. 

fix(phising-warning): change from component to function

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

feat(buyer hand hold): prevent showing up a banner

---

lang/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/defaultMessages.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Alerts/messages.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/Institutional/index.tsx
packages/blockchain-wallet-v4/src/network/api/misc/index.ts

fix(captcha-error): copy for email error and back arrow spacing

---

packages/blockchain-wallet-v4/src/network/api/misc/index.ts

fix(email): remove comment

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/template.success.tsx

Prevent users to change country on KYC flow

feat(kyc): do not allow users to change country

---

packages/blockchain-wallet-v4-frontend/src/data/cache/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/session/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/AccountUnification/MergeAccountConfirm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/Institutional/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/TwoFA/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/CheckEmail/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/TwoFA/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

fix(cache): back arrow cache clearing logic

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/Institutional/index.tsx

fix(institutional): fix exchange email field name

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/utils.ts

fix(analytics): fixes swap clicked and swap viewed tracking events

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/onboardingAndVerification.ts
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CompleteProfile/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/CompleteYourProfile/index.tsx

Segment expect to receive string not number

feat(tracking): fixed validation issue

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/EntitiesMigration/index.tsx

feat(entity migration): copy has been updated

---

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts

feat(entity migration): prevent calling fetch user too fast

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/EntitiesMigration/index.tsx

feat(entities migration): added missing paragraph

---

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts

New info modal to show abut entities migration

feat(entity migration): show info modal for UK region

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

feat(institutional): temp change for portal redirect

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPassword/index.tsx

Changing some copies from the login page

feat: add new copy to ensure notifications on wallet login

---

packages/blockchain-wallet-v4-frontend/src/scenes/Signup/SignupLanding/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx

Makes exchange sign up link dynamic by env, so wallet in dev will link to exchange in dev. 

fix(exchange-signup): make link dynamic by env

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/ConfirmWithdraw/template.success.tsx

Remove cancel button from withdrawal/deposit screens

feat(withdraw deposit): remove cancel button

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/UrlNoticeBar/index.tsx

Addressing previous PR comments.

fix: removing unneeded component and using theme colors for styling

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Footer.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/template.success.tsx

Attempt to make a deposit, confirm that the warning text is not covered

Feat/fwn 1241/tb spacing issue

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/CheckEmail/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/index.tsx

* fix(signup-captcha): refresh if error on signup
* fix(email-auth): reuse session id and sending state
* fix(signup-captcha): remove signup captcha fixes for next release
* fix(on-click): fix resend email button event handler

release 4.63 into development

---

packages/blockchain-wallet-v4-frontend/src/layouts/Explore/Header/index.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Explore/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/index.tsx

fix(nfts): add in mobile styling and from explorer

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

fix(login): comment out code thats redirecting institutional logins to the wrong endpoint

---

packages/blockchain-wallet-v4-frontend/src/generated/graphql.ts
packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAsset.graphql
packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAssets.graphql
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx

fix(nfts): footer styling links

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/index.tsx

fix(nfts): links

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/selectors.ts

fix(swap): fix swap lag

---

packages/blockchain-wallet-v4-frontend/src/components/Form/CoinBalanceDropdown/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts
packages/blockchain-wallet-v4/src/redux/data/coins/selectors.ts
packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts
packages/blockchain-wallet-v4/src/redux/data/eth/selectors.js

https://blockchain.atlassian.net/browse/CRI-142

fix(cel): dont support cel eur pk acct

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/Trade.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/TextInputWithClipboard/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileDropdown/Switch/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileDropdown/Switch/types.ts
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileDropdown/template.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileNav.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/Navbar.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/OptionRightAction.tsx
yarn.lock

This upgrades constellation version and fix all the
incompatibilities
* This also changes the swap icon in the trade view because the icon it was used before dont exist anymore
* Sets the default font family to Inter so the nav bar icons do use the font
* Adds the old implementation of the Switch but with correct colors
* Implements the Copy button in the mobile view

chore(constellation): upgrade from 0.0.27 to 0.0.28

---

package.json
packages/blockchain-wallet-v4-frontend/src/components/Form/CoinBalanceDropdown/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts
packages/blockchain-wallet-v4/src/redux/data/coins/selectors.ts
packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts
packages/blockchain-wallet-v4/src/redux/data/eth/selectors.js

Release/v4.64 into Release/v4.65

---

.well-known/assetlinks.json

Added exchange asset links for SSO purposes.

EXAND-731 Add exchange asset links for login*.blockchain.com host

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/AdditionalInformation.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/InterestUploadDocuments/UploadAndVerify.tsx

feat(edd uploader): fixed flyout design and page to be figma aligned

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/Card/Card.tsx
packages/blockchain-wallet-v4-frontend/src/components/Card/styles.ts
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tab/Tab.spec.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tab/Tab.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tab/Tab.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tab/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tab/styles.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tab/types.ts
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tabs.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tabs/Tabs.spec.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tabs/Tabs.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tabs/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Tabs/Tabs/types.ts
packages/blockchain-wallet-v4-frontend/src/components/Tabs/index.ts
yarn.lock

feat(Tabs): add tabs

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/CoinPerformance/CoinPriceChange/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/model.tsx

In the event that the price or price difference is NaN, do not show anything.

feat(NaN): in the event of a NaN dont display the diff change

---

lang/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/ConfirmWithdraw/template.success.tsx

Change withdrawal copy and make it closer to deposit

Fix/fwn 1242/tb withdrawal now

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/Flyout/TermsAndConditions/index.tsx
yarn.lock

feat(terms and conditions): fixed rendering

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PreviewSell/index.tsx

fix(buy sell): show sale amount for erc20s as the coin not eth

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinChart/CoinChart.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinChart/CoinChart.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinChart/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinChart/mocks.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinChart/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinHeader/CoinHeader.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/CoinPage.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/CoinPage.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/types.ts
yarn.lock

This adds a chart for the coin page

feat(CoinPage): add chart to coin page

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/selectors.ts

feat(request): order by balance

---

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/template.success.tsx

feat(interest): we would like to allow users to withdraw money even they are from blocked region

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

feat(buy sell): turn off auto complete for amount input field

---

packages/blockchain-wallet-v4-frontend/src/data/components/send/types.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.ts

feat(domains): resolve emojis

---

packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/utils/createChartDateFormatterFromSelectedTimeRange.ts

Fix the types used in the chart

fix(CoinView): chart type and curve

---

packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/slice.ts
packages/blockchain-wallet-v4/src/network/api/debitCard/index.ts

Add logic for preventing request from debit card module if it is disabled
Fix card creation response type

fix: avoid product request if feature flag is not enabled

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/types.ts

- send jwt expiration time to mobile exchange

feat(sso): pass jwt expiration time to mobile

---

package.json
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/index.tsx
packages/blockchain-wallet-v4/src/network/api/buySell/index.ts

Release/v4.65 into release/v4.66

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/ShowAddress/index.tsx
packages/blockchain-wallet-v4/src/utils/bch.js

Reverts blockchain/blockchain-wallet-v4-frontend#4343

Revert "Fix/fwn 1120/tb recive copy bch"

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/ShowAddress/index.tsx
packages/blockchain-wallet-v4/src/utils/bch.js

refactor(receive): remove bch copy logic

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/template.success.tsx

Added IBAN code format (4 characters per block)

feat: add iban code format

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/OrderSummary.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/model.tsx

IGNORE the color differences
#NEW

feat(FWN-1192): remove message if holding period is 0 days

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/template.success.tsx

Added a minor improvement to formatIbanAddress function.
Notes:
We found another reference for sbIbanAddress inside BuySell flow. We need to update it also?

feat: moving formatIbanAddress inside components

---

packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/InitSwapForm/index.tsx

feat(code cleanup): removed unused import and added proper typing to state object

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/InitSwapForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx

feat(silver revamp): fixed opening of a wrong modal

---

packages/blockchain-wallet-v4-frontend/webpackBuilder.js

Reverts blockchain/blockchain-wallet-v4-frontend#4386

Revert "refactor(builds): remove non-english bip39 files from bundle"

---

packages/blockchain-wallet-v4-frontend/src/index.html

- attempting to speed up initial page load

fix(app): defer loading of non-essential google scripts

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/VerifyNotice/index.tsx

feat(silver revamp): changed copy description on modal

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts

feat(silver revamp): show kyc extra fields only for Lithuanian entity users

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/components/IconCircularBackground/IconCircularBackground.tsx
packages/blockchain-wallet-v4-frontend/src/components/IconCircularBackground/index.ts
packages/blockchain-wallet-v4-frontend/src/components/IconCircularBackground/types.ts
packages/blockchain-wallet-v4-frontend/src/components/Rows/Checkout.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/StandardRow.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/StandardRow.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinHeader/CoinHeader.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/useWalletsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/HoldingsCard/HoldingsCard.spec.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/HoldingsCard/HoldingsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/WalletsCard/WalletsCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/WalletsCard/WalletsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/WalletsCard/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/WalletsCard/types.ts

feat(coin page): adding wallets and accounts section

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts

fix(login): continue login in original tab

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

fix(payments): adding correct error screens for pending and blocked

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/ExtraFields.stories.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/template.success.tsx

feat(silver revamp): fixed issue with KYC form submit

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/selectors.ts

We are filtering out trading wallets in case that user do not have ability to use custodial 

feat(silver revamp): filter out trading wallets in case of user inability to use it

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts

feat(silver revamp): show upgrade modal if user is run out of buy ability

---

packages/blockchain-wallet-v4-frontend/src/modals/Bch/SendBch/SecondStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Btc/SendBtc/SecondStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Eth/SendEth/SecondStep/template.success.js
packages/blockchain-wallet-v4-frontend/src/modals/Xlm/SendXlm/SecondStep/template.success.js

fix(FWN-1328): match modal spacing

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/NoHoldings/index.tsx

fix(swap): don't show all payment methods when user is not gold tier

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

feat(silver revamp): show transactions left banner unless there are transactions left from BE

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Banners/GetMoreAccess.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/CoinSelection/index.tsx

fix(upgrade): fixes padding issues with box

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts

Reverts blockchain/blockchain-wallet-v4-frontend#4408

Revert "fix(login): continue login in original tab"

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts

get correct key from error message 

fix(analytics): get right key from error message

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

Fixed issue with redirect if there are pending orders

feat(buy flow): fixed issue with redirect if there are pending orders

---

packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

Reverts blockchain/blockchain-wallet-v4-frontend#4424

Revert "fix(nfts): disable route entirely if not invited"

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

feat(silver revamp): skip checking products ability for gold users

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx

Show new design modal in case of T0 user

feat(silver revamp): show new modal in case of tier 0

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinIconColor/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinIconColor/types.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinIconColor/useCoinIconColor.test.tsx
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinIconColor/useCoinIconColor.ts
yarn.lock

This hooks is here to provide the background color for coin icons
in the CoinPage header

feat(useCoinIconColor): adds a hooks to provide the coin color

---

packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/List/List.tsx

fix(taxcenter): month report was fixed

---

packages/blockchain-wallet-v4-frontend/src/store/index.js

fix(coin defs): remove coin symbols that have .

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx

feat(BuySell): make footer sticky

---

packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxCountry/index.tsx

Added missing countries on signup

feat(singup): added missing countries: Tunisia, Venezuela, Zimbabwe and Cote d'ivoire

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Header/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/workInProgressBanner.tsx

feat(nfts): add in beta banner

---

packages/blockchain-wallet-v4-frontend/src/index.html
packages/blockchain-wallet-v4-frontend/src/layouts/Public/components/Header/index.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Public/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

Changing page titles, we still need @amadeo-bc confirmation.

Fwn 1389 when in any of the sso login screens change the title of the page to blockchain com instead of blockchain com wallet

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sagas.ts

If user want to deposit and is not eligible prevent it

feat(silver revamp): if user can't deposit prompt them to verify modal

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/index.tsx

feat(silver revamp): prevent using filter for trading accounts, and make it used only for silver revamp logic

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/onboardingAndVerification.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/AdditionalInfo/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/AdditionalInfo/template.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/VerifyNotice/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.gold.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.silver.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/InitSwapForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx

feat(silver revamp): added instrumentation events

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx

feat(silver revamp): fixed error message styling

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx

Re-fetch payment methods before rendering cards flow, we need most resent state from server

feat(silver revamp): we have to refetch payment methods to have most recent data for card

---

packages/blockchain-wallet-v4-frontend/src/data/components/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/withdraw/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/withdraw/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts

Show upgrade to gold modal in case of un ability to withdraw 

feat(silver revamp): check is user eligible for withdrawal

---

.well-known/assetlinks.json

Update the asset links for SSO to work properly on exchange

EXAND-731 update asset links to use android app namespace

---

packages/blockchain-wallet-v4-frontend/src/components/ClickableArea/ClickableArea.test.tsx
packages/blockchain-wallet-v4-frontend/src/components/Divider/Divider.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Divider/Divider.tsx
packages/blockchain-wallet-v4-frontend/src/components/Divider/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Divider/types.ts
packages/blockchain-wallet-v4-frontend/src/components/Rows/StandardRow.tsx
packages/blockchain-wallet-v4-frontend/src/components/SeparatedList/SeparatedList.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/SeparatedList/SeparatedList.test.tsx
packages/blockchain-wallet-v4-frontend/src/components/SeparatedList/SeparatedList.tsx
packages/blockchain-wallet-v4-frontend/src/components/SeparatedList/index.ts
packages/blockchain-wallet-v4-frontend/src/components/SeparatedList/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/CoinPage.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/WalletsCard/WalletsCard.tsx

This uses the ClickableArea component in the StandardRow to add the click handler and style effects

feat(Rows): add click event to StandardRow

---

packages/blockchain-wallet-v4-frontend/src/scenes/HelpExchange/index.tsx

Hotfix exchange support links. 

fix(support-links): update support links

---

packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/sagas.ts

Implement filter when obtaining cards for not retrieving TERMINATED ones

feat: add filter for cards terminated in debit card module

---

packages/blockchain-wallet-v4/src/redux/payment/eth/sagas.ts
packages/blockchain-wallet-v4/src/utils/eth.ts

fix(eth): gas memo bug fix

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/openSeaStatus.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/workInProgressBanner.tsx

fix: match banner for opensea api down and nft beta

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx

feat(silver revamp): improve close swap and open upgrade modal

---

.well-known/apple-app-site-association

Enable deeplink handling for exchange iOS apps for login.blockchain.com/exchange*

EXIOS-924 Update association file for login.blockchain.com/exchange path

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/EnterAmount.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/AmountFieldInput/AmountFieldInput.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/AmountFieldInput/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/ResizeableFontInput/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx

feat(amount field input): apply to deposit / withdraw

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinRates/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinRates/types.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinRates/useCoinRates.test.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinRates/useCoinRates.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/types.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/useRemote.test.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/useRemote.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/utils/createRemoteFailureState.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/utils/createRemoteLoadingState.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/utils/createRemoteNotAskedState.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/utils/createRemoteSuccessState.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/utils/index.ts
yarn.lock

feat(useRemote): add hook to access remote data from redux

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/selectors.ts

fix(buy sell): checks for cancellable orders when a user opens the buy sell modal

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

Prevent rendering of banner in case that user is T2 also do not render banner before we load userDetails 

feat(complete profile): prevent banner rendering in case of T2 user

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/onboardingAndVerification.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx

feat(segment conflicts): fixed issue with segment issues

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx

feat(silver revamp): updated designs removed title to align it with most recent figma

---

packages/blockchain-wallet-v4-frontend/src/components/Rows/StandardRow.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/StandardRow.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useRecurringBuyPanel/useRecurringBuyPanel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RecurringBuyListItem/RecurringBuyListItem.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RecurringBuyListItem/RecurringBuyListItem.tsx
yarn.lock

fix(coin view): convert recurring buy line items to standard row and enable standard row to have a right action and loading state

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/Trade.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/CreditCardExpiryBox/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/CreditCardExpiryBox/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/CreditCardExpiryBox/utils/normalizeCreditCardExpiry/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/CreditCardExpiryBox/utils/normalizeCreditCardExpiry/normalizeCreditCardExpiry.test.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/CreditCardExpiryBox/utils/normalizeCreditCardExpiry/normalizeCreditCardExpiry.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/TextInputWithClipboard/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileDropdown/Switch/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileDropdown/Switch/types.ts
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileDropdown/template.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/MobileNav.tsx
packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/Navbar.tsx
packages/blockchain-wallet-v4-frontend/src/components/Rows/OptionRightAction.tsx
packages/blockchain-wallet-v4-frontend/src/index.html
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/utils/normalizeCreditCard/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/utils/normalizeCreditCard/normalizeCreditCard.test.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/utils/normalizeCreditCard/normalizeCreditCard.ts
packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/List/List.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/template.tsx
yarn.lock

Update constellation to version 0.0.34 and add the @blockchain-com/icons package
* Updates the app card to use the new useCopy hook
* Updates the icons in the Trade NavBar
I also need to add the swap and minus icons to the constellation icons, so I can use them here, but  I will do that in another PR

chore(wallet): upgrade constellation to v0.0.34

---

packages/blockchain-wallet-v4-frontend/src/components/Rows/StandardRow.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/Button/Button.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/BuyButton/BuyButton.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useChart/useChart.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/LearnAboutRecurringBuyPanel/LearnAboutRecurringBuyPanel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/ReceiveButton/ReceiveButton.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RecurringBuyListItem/RecurringBuyListItem.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/SellButton/SellButton.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/SendButton/SendButton.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/mocks/defaultAboutSectionActions.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/mocks/defaultHoldingsCardActions.tsx

It seems that when coin page was merged, it did not contain the new icons package.
Then the build only failed in development because development had the new version of Constellation and its icon
So to fix that I updated all the old icons on the coin page and I added another fix to the StandardRow to pick up the correct colour

fix(CoinPage): update the coin page code to use the new icons package

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts

Fixed issue with sending crypto with fix of fiat where we do not convert amount to proper currency

feat(send crypto): fixed issue with sending fiat as crypto

---

package.json
packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts

Release/v4.66 into relese 4.67

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts

This PR should prevent sending fiat amount as crypto

feat(send crypto): prevent sending fiat value as crypto value

---

packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

fix(coin view): convert new coinview route to a single paramaterized route

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/refresh/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendBch/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendBtc/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendXlm/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/xlm/sagas.js
packages/blockchain-wallet-v4-frontend/src/data/modules/transferEth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Balances/model.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/CoinList/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/Status/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Holdings/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

feat(coins): use single coin layout switch

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/EnterAmount.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/index.tsx

fix(deposits): use proper payment method limits when users payment account is selected

---

.storybook/main.js
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useChart/useChart.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useChartBalancePanel/useChartBalancePanel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useHoldingsCard/useHoldingsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useRecurringBuyPanel/useRecurringBuyPanel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RecurringBuyListItem/RecurringBuyListItem.tsx
packages/blockchain-wallet-v4-frontend/webpackBuilder.js
tsconfig.json

this adds a new alias to the hooks folder and update the current files that use the hooks to use the new alias

Add alias to hook

---

packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Flex/Flex.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Flex/Flex.tsx
packages/blockchain-wallet-v4-frontend/src/components/Padding/Padding.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Padding/Padding.tsx
packages/blockchain-wallet-v4-frontend/src/components/Padding/types.ts

feat(components cleanup): removed unused stuff

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/utils.ts

fix(segment): add another case for recurring buy cancel button clicked

---

packages/blockchain-wallet-v4-frontend/src/components/Form/AmountFieldInput/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/EnterAmount/Checkout/index.tsx

feat(amount input): turn off autocomplete for enter amount form fields for deposit withdrawal and swap

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useCoinBalance/useCoinBalance.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useWalletsCard/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/StxAirdropFundsAvailable/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SelfCustodyTx/SelfCustodyTxModel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SelfCustodyTx/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/TransactionList/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/types.ts
packages/blockchain-wallet-v4/src/network/api/coin/types.ts
packages/blockchain-wallet-v4/src/redux/data/coins/sagas.ts

fix(stx): change movement shape

---

.storybook/main.js
packages/blockchain-wallet-v4-frontend/src/components/FabButton/index.stories.tsx

chore(storybook): change bc info components and constellation names in storybook

---

packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/template.tsx

fix(taxcenter): export limit copy was removed

---

packages/blockchain-wallet-v4-frontend/src/components/Card/Card.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Divider/Divider.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Flex/Flex.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Intro.stories.mdx
packages/blockchain-wallet-v4-frontend/src/components/Padding/Intro.stories.mdx
packages/blockchain-wallet-v4-frontend/src/components/Padding/Padding.stories.tsx

Add a new introduction page to the storybook https://blockchain.github.io/blockchain-wallet-v4-frontend/?path=/story/introduction--page

chore(storybook): add introduction mdx document and fix the broken padding story

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts
packages/blockchain-wallet-v4/src/network/api/coin/types.ts

feat(stx): change buildtx intent source to sources

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

feat: nfts buy and sell flyouts

---

packages/blockchain-info-components/index.d.ts
packages/blockchain-info-components/src/Modals/Modal.js
packages/blockchain-info-components/src/Modals/__snapshots__/Modal.spec.js.snap
packages/blockchain-wallet-v4-frontend/src/components/Flyout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/index.tsx

New ability to keep modal open
https://www.loom.com/share/d55254b969a7479eb1881223456adb46 

feat(silver revamp): improved logic to render and transition modals

---

packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/types.ts
packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/CardDashboard/ManageCardBox/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/CardDashboard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/CardDashboard/model.ts
packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/template.tsx
packages/blockchain-wallet-v4/src/network/api/debitCard/index.ts
packages/blockchain-wallet-v4/src/network/api/index.ts

Add Lock Card feature in debit card module

Feat/ci 111/add lock card feature

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Address/AddressItems/AddressItems.results.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Address/AddressItems/AddressItems.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Address/AddressItems/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Address/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/CollectionItems/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Events/Events.results.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Events/Events.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Events/index.ts

feat(nfts): events on owner addr

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.utils.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/auth/types.ts

fix(exchange-mobile): session passed from webview launch

---

packages/blockchain-wallet-v4-frontend/graphql.schema.json
packages/blockchain-wallet-v4-frontend/src/generated/graphql.ts
packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAsset.graphql
packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAssets.graphql
packages/blockchain-wallet-v4-frontend/src/layouts/Explore/Header/index.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Explore/NftSearch/NftSearch.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Explore/NftSearch/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/CollectionItems/CollectionItems.results.tsx

fix(nfts): graphql

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx

This PR improve new silver revamp upgrade your account flyout

feat(silver revamp): removed white space and added position of icon to top left corner

---

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx

fix(bank transfer): default to user wallet currency if userData limit currency doesnt exist

---

packages/blockchain-wallet-v4-frontend/src/data/coins/sagas/coins/bch.ts
packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/ShowAddress/index.tsx
packages/blockchain-wallet-v4/src/utils/bch.js

Feat/fwn 1120/tb move bch

---

packages/blockchain-wallet-v4-frontend/src/index.html

feat(sso): change captcha site key for testing

---

package.json

chore(Release): v4.67.2 into development

---

packages/blockchain-wallet-v4-frontend/src/layouts/Explore/NftSearch/index.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/Nfts.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/index.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsSearch/NftsSearch.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsSearch/index.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsTemplate.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/NftFilter/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/NftPageLazyLoadWrapper.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

feat(nfts): rename explore to nfts

---

packages/blockchain-wallet-v4-frontend/graphql.schema.json
packages/blockchain-wallet-v4-frontend/src/generated/graphql.ts

fix(graphql): circ deps

---

packages/blockchain-wallet-v4-frontend/src/components/Badge/Badge/Badge.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/Badge/Badge.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/Badge/Badge.types.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/Badge/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/BadgePlacement/BadgePlacement.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/BadgePlacement/BadgePlacement.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/BadgePlacement/BadgePlacement.types.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/BadgePlacement/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/BaseBadge/BaseBadge.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/BaseBadge/BaseBadge.types.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/BaseBadge/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/IconBadge/IconBadge.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/IconBadge/IconBadge.tsx
packages/blockchain-wallet-v4-frontend/src/components/Badge/IconBadge/IconBadge.types.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/IconBadge/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Badge/Intro.stories.mdx
packages/blockchain-wallet-v4-frontend/src/components/Badge/index.ts

This adds a badge component and badge placement component to position ate badges

feat(Badge): add badge component

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts

Creates separate login function if user is signing up from exchange mobile app webview. 

fix(exchange-mobile): add own login function

---

packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js

fix(websocket): reorder subscription to start with wallet entity

---

packages/blockchain-wallet-v4-frontend/src/store/index.js

fix(coins): revert store index changes

---

packages/blockchain-wallet-v4-frontend/src/store/index.js

feat(coins): use for each instead of reduce

---

package.json
packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/CoinSelect/selectors.ts

Release/v4.67 into v4.68

---

packages/blockchain-wallet-v4-frontend/src/data/components/debitCard/selectors.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuLeft/Navigation/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

A quick fix to have a working deployment of debit card module. 
NOTE: Will continue working on this fix

fix: quick fix for displaying correctly debit card module

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/AcceptOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelListing/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/NotVerified/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Transfer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/NftFlyoutLoader.tsx

Centers the loading icon in the flyouts

fix(nfts): improve load state

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Approval/fees.tsx
packages/blockchain-wallet-v4-frontend/src/store/index.js
packages/blockchain-wallet-v4/src/network/api/eth/index.ts

fix(nfts): fix eth testnet config

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/Offers.table.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/Offers.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/OffersTableColumns/OffersTableColumns.amount.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/OffersTableColumns/OffersTableColumns.expiration.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/OffersTableColumns/OffersTableColumns.from.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/OffersTableColumns/OffersTableColumns.price.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/OffersTableColumns/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Offers/index.tsx

feat(nfts): offers table

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/nfts.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts

feat: nft success fail events

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/index.d.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/template.unsupported.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/template.unsupported.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/template.unsupported.tsx

feat(sell): fixed copy on sell flow

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/Collection.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/Stats/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/index.tsx

feat(nfts): add in floor price filter on click

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/nfts.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts

feat(nts): more events accept offer, cancel offer, cancel listing 

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/middleware/webSocket/coins/sagas.js
packages/blockchain-wallet-v4-frontend/src/data/session/sagas.ts

feat(analytics): login analytics changes

---

packages/blockchain-wallet-v4-frontend/src/components/Clipboard/CopyClipboardButton/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/ShowAddress/index.tsx

Improved logic to copy address

feat(copy address): fixed issue with copy address

---

packages/blockchain-wallet-v4-frontend/src/components/Balances/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/errors.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/index.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/index.tsx
packages/blockchain-wallet-v4/src/utils/index.ts

chore(segment): adding oops error analytics to crypto selection screen

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/index.tsx

fix: nft banner image

---

packages/blockchain-wallet-v4-frontend/src/data/components/refresh/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/SelfCustodyTx/index.tsx
packages/blockchain-wallet-v4/src/redux/data/coins/sagas.ts

fixes pending txs not showing, fixes transactions_at_bound issue, refresh coin transactions after sending

fix(stx): tx history fixes, include pending

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Firehose/Firehose.tsx

feat(nfts): add collections to firehose filters

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/nfts.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts

fix: add in usd calc for nft events

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Firehose/Firehose.results.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Firehose/Firehose.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/NftFilter/index.tsx

fix(nfts): better collection filtering

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx

fix(nfts): add unauth state for make offer

---

packages/blockchain-wallet-v4-frontend/src/index.html
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/Nfts.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsTemplate.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/NftFilter/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/NftError.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/NftPageLazyLoadWrapper.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/TraitGridFilters.tsx

fix(nfts): scroll on nfts

---

packages/blockchain-wallet-v4-frontend/src/scenes/InterestHistory/template.success.tsx

fix(interest): date format for txs

---

packages/blockchain-wallet-v4-frontend/src/components/Terms/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/index.tsx
packages/blockchain-wallet-v4-frontend/src/services/forms/validationMessages.js
packages/blockchain-wallet-v4-frontend/src/services/forms/validators.js

- Fixes strength regex to properly detect all special characters allowed
- Adds live password requirement checker

fix(signup): fix password requirements regex

---

packages/blockchain-wallet-v4-frontend/src/components/Form/DateInputBox/index.js

Fixed issue with tabs and non US countries format
Create new wallet go over to info and residential settings and enter details

feat(date input): implemented logic to support proper tabbing around date component and formats

---

packages/blockchain-wallet-v4-frontend/src/generated/graphql.types.ts
packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAsset.graphql
packages/blockchain-wallet-v4-frontend/src/graphql/queries/NftAssets.graphql
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/NftAssetItem.tsx

fix(nfts): remove listings now for faster querying

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/StxAirdropFundsAvailable/index.tsx

fix(stx): update copy

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/index.tsx

feat(deposit): fixed issue with payment methods in case of brand new verified wallet

---

packages/blockchain-wallet-v4-frontend/src/store/index.js
packages/blockchain-wallet-v4/src/redux/data/coins/sagas.ts

- fix typo from testing
- actually ensure browser is supported on app load

fix(error): remove testing code and update assets failure routing

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/index.tsx
packages/blockchain-wallet-v4-frontend/src/providers/ModalEnhancer/index.tsx

fix(nfts): fix nft scroll flyout

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Events/Events.tsx

fix(nfts): activity page scroll issue

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/AcceptOffer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/AcceptOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelOffer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Transfer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Transfer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/NftFlyoutFailure.tsx

fix(nfts): failure page for flyout and fees description fix

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Errors/Oops.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/index.tsx

We are extending logic to show more errors

feat(ukraine sanctions): extended logic to show exact error message

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.ts

This PR fix sending email rather than just is email verified flag

feat(analytics): beckend expects to receive email not is email verified value

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.ts

feat(analytics): send email instead of is verified

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx

fix(txs): wallet balance dropdown weird balance fix

---

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/IntroCard/index.tsx

Fixing a link that has been updated.

fix: fixing rewards "Learn More" link

---

packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsSearch/NftsSearch.tsx

fix(nfts): account search

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

fix: nft asset copy link

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

fix: show new trait instead of na

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Status/index.tsx

fix: nft copy changes

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Address/AddressItems/AddressItems.results.tsx
packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(nfts): english auction delegate call fix

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/MarkForSale.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/MarkForSale.utils.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx

fix(nfts): english auction listing fix

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

fix(nfts): place a bid button

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/NotVerified/index.tsx

feat(nft): disclosures

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx
yarn.lock

Add react-query as an alternative to handle asynchronous states

chore(react-query): add react-query and add the in memory cache for queries

---

packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx
packages/blockchain-wallet-v4/src/network/api/coin/types.ts

fix(stx): change priority fee to high

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Status/index.tsx

fix: nfts route to portfolio

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/Brokerage/EnterAmount.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/components/index.tsx

fix(deposit): move max button to footer so it doesnt get cut off on smaller browser windows

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

fix: nfts hide more assets footer if less than 2

---

packages/blockchain-wallet-v4-frontend/src/components/NavbarV2/Navbar.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx

feat(nfts): account dropdown

---

packages/blockchain-wallet-v4-frontend/src/hooks/useRemote/useRemote.ts

Refactor the useRemote hook to use the Remote helpers when getting the remote current state.
This don't change the useRemote interface

refactor(useRemote): this refactor the useRemote hook to use remote helpers

---

packages/blockchain-wallet-v4-frontend/src/layouts/Auth/components/Footer/Help/index.tsx

Fixes footer link to support. 

fix(support-link): link in footer

---

packages/blockchain-wallet-v4-frontend/src/services/forms/constants.js
packages/blockchain-wallet-v4-frontend/src/services/forms/utils.js

Do not allow to enter a year 0000

feat(dob): fixed dob validation

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts

it also ensures we always track the login event properly

fix(login): null checks to hide institutional login error msg

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/sendCrypto.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts

feat(send): track failures

---

packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Flex/Flex.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Flex/types.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Settings/NftSettings.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Settings/NftSettingsMenu.tsx

feat(notifications): set up notifications layout

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

Fixes issue where scrolling down on chart would cause table to expand in width. 

fix(price-chart): add max width to chart

---

packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsSearch/NftsSearch.tsx

feat(nfts): add verified to search

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

feat(peek sheet): show peek sheet banner first

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

fix(table): max width

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sagas.ts
packages/blockchain-wallet-v4/src/network/api/nfts/index.ts

feat(nfts): pass jwt to post order

---

packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/components/AssetMoreItems.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/components/NftAssetLoading.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/components/index.tsx

fix(nfts): asset loading state

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/CreateOffer.fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/fees.tsx
packages/blockchain-wallet-v4/src/redux/payment/nfts/index.ts
packages/blockchain-wallet-v4/src/redux/payment/nfts/utils.ts

fix(bids): pass optional sell order to create buy order

---

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts

fix(cache): add unified acct details if deeplinked from exn settings

---

packages/blockchain-wallet-v4-frontend/src/data/prices/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/prices/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/prices/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/PriceMovement/selectors.ts

- adds typings to prices api response

chore(prices): add types to multi-index api

---

packages/blockchain-wallet-v4/src/redux/data/custodial/sagas.ts

We send wrong format to BE and it has to be in ISO UTC with Z at the end.

feat(custodial orders): fixed date format to be in ISO with Z at the end which is expected from BE side

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/es-LA.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/es.json

Signup latam header text changed, no % profits shown

fix: signup latam header text

---

packages/blockchain-wallet-v4-frontend/src/layouts/Auth/components/Footer/index.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Auth/index.tsx

fix(footer): only show intstituional login on login path

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/MarkForSale.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/Stats/index.tsx

fix(nfts): add 30 mins 1 hour selections for listings

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

fix(nfts): speed up listing and hide accept offer if listed

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/slice.ts

feat(kyc flow): fixed issue with passing wrong property type to store

---

packages/blockchain-wallet-v4-frontend/webpackBuilder.js

feat(webpack): removed deprecated onBeforeSetupMiddleware function and replaced with new one setupMiddlewares

---

packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/PairingCode/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/WalletId/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/model.tsx

fixes small bugs for copy on settings page and price change displaying as NaN on homepage

fix(bugs): copy spacing on settings, NaN prices displaying

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts

feat(login): prevent failing due to missing state data use default data

---

packages/blockchain-wallet-v4-frontend/src/modals/Eth/EthWalletBalances/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/index.tsx
packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

fix(erc20): use weth abi for balances, center nft banner img

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx

fix(nfts): fix weth hardcoding in make offer and reset after submission

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts

feat(login event): we have to make sure that state auth exists otherwise just need to pass default value

---

packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx

fix(nfts): remove confusing dropdown from nft header

---

packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/index.tsx

Fixes width in signup form and styling for product picker page in mobile. 

fix(sign-up): style for mobile width signup form and product picker

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx

feat(silver revamp): updated designs to show proper label for tier zero

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx

feat(silver revamp): updated designs to show proper label for tier zero users

---

packages/blockchain-wallet-v4-frontend/src/components/EmptyResults/EmptyResults.stories.tsx
packages/blockchain-wallet-v4-frontend/src/hooks/useWalletsForCoin/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AccountSelectBox/AccountSelectBox.styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AccountSelectBox/AccountSelectBox.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AccountSelectBox/AccountSelectBox.types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AccountSelectBox/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/ActivityFeedCard/ActivityFeedCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/useActivityFeed.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/useActivityFeed.types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/utils/filterTransactionsByWalletType/filterTransactionsByWalletType.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/utils/filterTransactionsByWalletType/filterTransactionsByWalletType.types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/utils/filterTransactionsByWalletType/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RewardsTransactionsCard/RewardsTransactionsCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RewardsTransactionsCard/RewardsTransactionsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RewardsTransactionsCard/RewardsTransactionsCard.types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RewardsTransactionsCard/index.ts

Adds a wallet filter to the transactions list in the Coin view v2 page

feat(CoinView): add wallet filter to transactions list

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx

Adding needed logic for the rewards flow to load under coinview

feat: adding needed logic to load rewards flow

---

packages/blockchain-wallet-v4/src/redux/data/xlm/selectors.spec.js
packages/blockchain-wallet-v4/src/redux/kvStore/xlm/selectors.js
packages/blockchain-wallet-v4/src/redux/kvStore/xlm/selectors.spec.js

fix(xlm): first account only

---

packages/blockchain-wallet-v4-frontend/src/modals/Wallet/InterestPromo/template.tsx

Removing hardcoded currency per dynamic one.

fix: removing hardcoded currency per dynamic one

---

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts

Adds event for failure when calling mercury/auth and getting an error (trying to get token to log into the exchange) 

fix(analytics): add login failure for mercury auth

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

Back ported changes to release

feat(buy): fixed issue with getting order since order is now Remote type

---

packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/coins/self-custody.ts
packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/index.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/Confirm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterTo/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/types.ts
packages/blockchain-wallet-v4-frontend/src/store/worker.assets.js
packages/blockchain-wallet-v4/src/network/api/coin/types.ts

fix(stx): add memo

---

packages/blockchain-wallet-v4-frontend/src/scenes/UploadDocuments/template.js

feat(upload documents): added changes on upload page

---

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts
packages/blockchain-wallet-v4/src/transactions/eth.ts

- more issues from date-fns migration

fix(transactions): eth/erc20 transaction history export to csv

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Home/Home.tsx

fix(nft hero): filtering hero

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Collection/Collection.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Firehose/Firehose.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/components/TraitGridFilters.tsx

fix(nfts): add sort by label, set num of results back to undefined

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/index.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/swap.ts
packages/blockchain-wallet-v4-frontend/src/modals/Swap/SuccessfulSwap/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Swap/selectors.ts
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

Adding "Earn Rewards" into Swap flow.

Srw 42 web add rewards on swap flow modal

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/validation.ts

https://www.loom.com/share/143bca37ff734b54a0ee994f912663ea

fix(nfts): improving max amount experience

---

packages/blockchain-wallet-v4-frontend/src/components/SupportChat/index.tsx
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/misc.ts

feat(analytics): add segment event for chat button click and convert class component to FC and hooks style

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts

fix(kyc): call correct modal

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/data/misc/sagas.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Auth/components/Footer/DropdownLanguage/index.js
yarn.lock

* add cookie implementation to persist language setting

feat(automatic-languages): detect/set language cookie

---

packages/blockchain-wallet-v4-frontend/package.json

fix(wallet): remove core from fe pkg json

---

packages/blockchain-wallet-v4-frontend/src/data/custodial/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/custodial/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/custodial/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

feat(sanctions): persist sanctions banner during the new api calls

---

packages/blockchain-wallet-v4-frontend/src/data/misc/sagas.ts

fix(automatic-language): fix if statement check

---

packages/blockchain-info-components/package.json
packages/blockchain-info-components/src/Form/PasswordInput.js
packages/blockchain-info-components/src/Form/TextInput.js
packages/blockchain-info-components/src/Form/__snapshots__/PasswordInput.spec.js.snap
packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/Form/PasswordBox/index.js
packages/blockchain-wallet-v4-frontend/src/components/Form/TextBox/index.js
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryPhrase/SecondStep/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/StepTwo/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/WalletPassword/Settings/template.js
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/services/forms/validators.js
yarn.lock

- Adds a password visibility toggle to all password inputs as per design
- Updates min password length to be 8 characters instead of 12
- Didnt spend the time to convert to functional component due to risk and in favor of future migration to Constellation

feat(passwords): add password input visibility toggle

---

packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/Sanctions/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts

feat(sanctions): remove ability to have sanctions modal non-dismissible

---

packages/blockchain-wallet-v4-frontend/src/modals/Transactions/DownloadTransactions/index.tsx
packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

- Adds support to show ERC20 gas fees in ETH transaction report
- Fixes issue with date ranges not being properly applied

fix(transactions): add support for eth gas fees in tx reports

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/viewAndClick.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/RewardsBanner/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

Adding a new banner for in product announcement for rewards

SRW-89 - in product announcement for rewards

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/AcceptOffer/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/AcceptOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelListing/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelListing/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelListing/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelOffer/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/CancelOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Transfer/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Transfer/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/GreyMessage.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/NftDropdown.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/NftNotInvited.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/PendingEthTxMessage.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/components/PendingTxMessage.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

Squad 150 nf ts if user has pending eth tx block order flow call to actions

---

packages/blockchain-wallet-v4-frontend/src/components/CryptoAddress/CryptoAddress.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Address/Address.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

fix(nfts): copy crypto addr to clipboard

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositStatus/index.tsx

feat(manual review): show order success in case of manual review

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositStatus/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositStatus/template.success.tsx
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

feat(deposit): show success message in case of manual review of deposit action

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/cta.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MarkForSale/index.tsx

fix(nft): fix disabled button when selling item

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/index.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/walletRewardsClientEvents.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/SummaryCard/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Interest/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/InterestHistory/DownloadTransactions/index.tsx

SRW-96 - Implement missing events on WEB

---

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas.ts

Since users are not tier 2 we are about to allow them to do swap if maxOrdersLeft is null/not set

fix(silver revamp): allow users to do swap

---

packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/components/AssetMoreItems.tsx

fix(nfts): more items offset

---

packages/blockchain-wallet-v4-frontend/src/components/CoinWithBalance/CoinWithBalance.test.tsx
packages/blockchain-wallet-v4-frontend/src/components/CoinWithBalance/CoinWithBalance.tsx
packages/blockchain-wallet-v4-frontend/src/components/CoinWithBalance/__snapshots__/CoinWithBalance.test.tsx.snap

fix displayed value in user funds box for fiat and crypto
added test

fix: in Debit Card -> displayed value in user funds box for fiat and crypto

---

packages/blockchain-wallet-v4-frontend/src/components/CircularProgress/CircularProgress.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/CircularProgress/CircularProgress.styles.ts
packages/blockchain-wallet-v4-frontend/src/components/CircularProgress/CircularProgress.tsx
packages/blockchain-wallet-v4-frontend/src/components/CircularProgress/CircularProgress.types.ts
packages/blockchain-wallet-v4-frontend/src/components/CircularProgress/index.ts

Adds circular progress component to be used in the Feynman integration
https://user-images.githubusercontent.com/99212903/174607997-c1ff2ef2-c822-41af-81da-47010f91592b.mov

feat(CircularProgress): add circular progress

---

packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorFulfilledInterceptor/createNabuErrorFulfilledInterceptor.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorRejectedInterceptor/createNabuErrorRejectedInterceptor.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorRejectedInterceptor/createNabuErrorRejectedInterceptor.ts

Expect error not to have response in the nabu error axios reject interceptor

fix(NabuError): expect no response in axios reject interceptor

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts

Includes custodial wallet when loading coin data in transactions page dropdown

fix(Transactions): include custodial in coin dropdown

---

packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts

* only show create wallet error if it's not related to referral error

fix(referral-error): only show referral error

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/WrapEth.fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/fees.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/MakeOffer/index.tsx

If wrapped fees are needed for make offer, show the row.  Otherwise hide it and don't include in total.

fix: nft wrapped fees / no wrap fees

---

packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/modals/Interest/AccountSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Interest/WithdrawalForm/template.success.tsx

SRW-106 - rename "[Coin] Balance" to "Rewards Balance" in Interest Flyout

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/InfoAndResidential/template.success.tsx

Give some time state to be updated, since sometimes country updated do it in parallel and reset state 

feat(info and residential): fixed timing issue with reset state on in fo and residential data page

---

packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts

fix(referral-syntax): fix syntax

---

packages/blockchain-wallet-v4-frontend/src/data/modules/profile/sagas.ts

Undid these changes resolving merge conflicts when merging release branch into dev. 

fix(exchange-mobile): fix merge conflict mistake

---

packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/CardDashboard/TransactionsBox/TransactionsBox.template.tsx

Add logic for displaying different descriptions and icons depending on transaction type
Note: still needs more design definition to complete this task

feat: manage view for different type of transactions

---

packages/blockchain-info-components/src/Form/SelectInput/__snapshots__/SelectInput.spec.js.snap
packages/blockchain-info-components/src/Form/SelectInput/template.js

fix: select input "ValueContainer" clickable area

---

packages/blockchain-wallet-v4-frontend/src/components/Form/FormError/index.js
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Exchange/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPassword/index.tsx

fix(login): adding props to FormError so the design is not broken

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

This adds a way to poll the order if it's settled but not complete. Gives time for the backend to return it as "FINISHED"

fix(payments): adding order polling when settled but not complete

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts

feat(kyc): fixed issue in case that state is not exists for countries without state

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/TwoFA/index.tsx

Add wallet deactivation message handling

---

packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPassword/index.tsx

Show 'account locked' error for account deactivation

fix(login): account locked error for deactivation

---

packages/blockchain-info-components/src/Form/SelectInput/__snapshots__/SelectInput.spec.js.snap
packages/blockchain-info-components/src/Form/SelectInput/template.js

Rolling back changes on SelectInput

fix: rollback changes to SelectInput

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/slice.ts

Improve kyc questions flow for fiat deposit context.
Prevent deposit flyout from opening before kyc flow is settled.

feat(kyc questions): improve flow on FIAT_DEPOSIT context

---

packages/blockchain-wallet-v4/src/redux/payment/nfts/__mocks__/index.ts

fix(nfts): test - part 1

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/index.tsx

modal on close button click and prevent non tier 2 user to see deposit screen rendered

feat(deposit): do proper close of KYC 

---

packages/blockchain-wallet-v4-frontend/src/components/Card/Card.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Card/Card.tsx
packages/blockchain-wallet-v4-frontend/src/components/Card/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AboutSection/AboutSection.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AlertCard/AlertCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/AlertCard/styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/CoinPage/hooks/useActivityFeed/useActivityFeed.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/HoldingsCard/HoldingsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/LearnAboutRecurringBuyPanel/LearnAboutRecurringBuyPanel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RecurringBuyPanel/RecurringBuyPanel.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/RewardsTransactionsCard/RewardsTransactionsCard.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/CoinPage/components/WalletsCard/WalletsCard.tsx

Adds a card at the bottom of the "Add Card" flyout to inform about debit and credit card differences 
https://user-images.githubusercontent.com/99212903/176534534-6fcb2076-62e5-4226-babd-9133b5afce22.mov

feat(AddCard): adds card to incentivize use of debit card

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/ExtraFields/template.success.tsx

updateItem function for MULTIPLE_SELECTION fields fixed.

feat(Extra KYC): fields updateItem function fixed

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx

feat: remove `INTEREST_CLIENT_SUBMIT_INFORMATION_CLICKED` event

---

packages/blockchain-wallet-v4-frontend/src/scenes/AuthorizeLogin/AuthorizeLogin.template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/VerifyMagicLink/template.success.tsx

fix(authorize): fixing font weight for authorize approve screen

---

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/RecoveryOptions/index.tsx

fix(recovery): adding small margin on buttons

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/actions.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

feat: adding "earn" button for eligible currencies under prices page

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx

Handle the quote error with the generic nabu error flyout when that is available

fix(BuySell): handle nabu error when fetching for quotes

---

packages/blockchain-wallet-v4-frontend/src/services/locales/index.ts

feat(pt-br): add pt-br to language list

---

packages/blockchain-wallet-v4-frontend/src/components/Navbar/MobileNav.tsx
packages/blockchain-wallet-v4-frontend/src/components/Navbar/Navbar.tsx
packages/blockchain-wallet-v4-frontend/src/components/Navbar/UserNavDropdown.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/Nfts.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsHeader.tsx

fix(nav): user dropdown

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

Fixes rare race condition, where order is still on polling, and we try to cancel and recreate another one on the background

fix(order): fixing race condition for enter amount card polling

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/ArriveInThreeDaysEasyBankTransferCard/ArriveInThreeDaysEasyBankTransferCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/ArriveInThreeDaysEasyBankTransferCard/ArriveInThreeDaysEasyBankTransferCard.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/ArriveInThreeDaysEasyBankTransferCard/ArriveInThreeDaysEasyBankTransferCard.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/ArriveInThreeDaysEasyBankTransferCard/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/InstantlyEasyBankTransferCard/InstantlyEasyBankTransferCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/InstantlyEasyBankTransferCard/InstantlyEasyBankTransferCard.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/InstantlyEasyBankTransferCard/InstantlyEasyBankTransferCard.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/InstantlyEasyBankTransferCard/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/OneDayBankTransferCard/OneDayBankTransferCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/OneDayBankTransferCard/OneDayBankTransferCard.styles.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/OneDayBankTransferCard/OneDayBankTransferCard.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/OneDayBankTransferCard/OneDayBankTransferCard.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/OneDayBankTransferCard/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/SameDayBankTransferCard/SameDayBankTransferCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/SameDayBankTransferCard/SameDayBankTransferCard.styles.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/SameDayBankTransferCard/SameDayBankTransferCard.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/SameDayBankTransferCard/SameDayBankTransferCard.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/SameDayBankTransferCard/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/WireTransferCard/WireTransferCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/WireTransferCard/WireTransferCard.styles.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/WireTransferCard/WireTransferCard.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/WireTransferCard/WireTransferCard.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/WireTransferCard/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/index.tsx

Update bank transaction items to indicate the different bank transfer scenarios

feat(Methods): change methods text for USD

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/WalletBalanceDropdown/selectors.ts

- pass fiat coin to its balance selector
- remove hardcoding of coin codes on crypto selector

fix(balances): pass coin to fiat currency selector

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/data/modals/types.ts
packages/blockchain-wallet-v4-frontend/src/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/useApplePay.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/useApplePay.types.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/utils/isApplePayAvailable/index.ts
packages/blockchain-wallet-v4-frontend/src/hooks/useApplePay/utils/isApplePayAvailable/isApplePayAvailable.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/AppleAndGooglePayBanner.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/components/AppleAndGooglePayBannerView/AppleAndGooglePayBannerView.stories.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/components/AppleAndGooglePayBannerView/AppleAndGooglePayBannerView.styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/components/AppleAndGooglePayBannerView/AppleAndGooglePayBannerView.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/components/AppleAndGooglePayBannerView/AppleAndGooglePayBannerView.types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/components/AppleAndGooglePayBannerView/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/components/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/AppleAndGooglePayBanner/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/Banners/selectors.ts
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts
typings/window.d.ts
yarn.lock

Add promo banner for Apple and Google Pay
https://user-images.githubusercontent.com/99212903/177807476-dda41cc9-6857-430a-b880-6f5d46a2ffee.mov
[FWN-1693](https://blockchain.atlassian.net/browse/FWN-1693)

feat(Home): add Apple and Google Pay anouncement banner

---

package.json
packages/blockchain-info-components/src/Form/SelectInput/template.js
packages/blockchain-wallet-v4-frontend/src/layouts/Nfts/NftsHeader/NftsSearch/NftsSearch.tsx
yarn.lock

Text should persist despite clicking out of search bar

fix: nft search bar

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/NftOrder.Buy.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/Buy/cta.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/Asset/Asset.tsx

feat(nfts): hide reserved listings, fix fulfiller error msg

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4/src/network/api/nfts/index.ts
packages/blockchain-wallet-v4/src/network/api/nfts/types.ts

feat(nfts): send purchase email notification to nft-market-api

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx

feat(trading currencies): fixed filtering for buy flow

---

packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts

fix(email): send email on nft purchase

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/AdditionalInfo/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/AdditionalInfo/model.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/AdditionalInfo/template.tsx

For Argentine User only, allowed one document for veriff

feat(LTMONB-27): pre veriff screen for AR users

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/KycVerification/index.tsx

Created new action, specific for the dissmisal of kyc flow. This way we can wait for that specific action, avoiding to loop through all closing modal actions.

fix(LTMONB-28): improved code removing loop

---

packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Expanded/Expanded.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flex/components/Expanded/types.ts
packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/Bank/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/Card/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedCards/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedWireBanks/template.success.tsx

Update designs on the card, bank and wire transfer items in the payment methods and in settings page

feat(BuySell): add credit card limit to payment item

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/utils/getCurrencyName.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/Confirm/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/ConfirmWithdraw/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PaymentMethods/Methods/PaymentCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/PreviewSell/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/SellOrderSummary/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/model.tsx

Update payment method format and the wallet coin name is some confirmation pages

fix(BuySell): text copy change

---

packages/blockchain-wallet-v4/src/network/api/settings/index.js

Update method name for secure update

fix(secure-update): change method name

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4/src/network/api/settings/index.js
packages/blockchain-wallet-v4/src/redux/settings/sagas.ts
packages/blockchain-wallet-v4/src/redux/walletOptions/selectors.ts

Wraps secure update endpoints in feature flag, uses old update endpoint if set to false. 

fix(secure-update): add feature flag

---

packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts
packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

fix(balances): even if eth balance call fails show holdings

---

packages/blockchain-wallet-v4/src/redux/settings/sagas.ts

Prevent updating wallet currency on trading currency change

feat(trading currency): do not update wallet currency on trading currency change

---

packages/blockchain-wallet-v4-frontend/src/components/GenericNabuError/GenericNabuError.tsx
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuErrorFlyout/GenericNabuErrorFlyout.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/NabuErrorDeepLinkHandler/NabuErrorDeepLinkHandler.tsx
packages/blockchain-wallet-v4-frontend/src/services/deepLinkListener/components/DeepLinkListener/DeepLinkListener.test.tsx
packages/blockchain-wallet-v4-frontend/src/services/deepLinkListener/components/DeepLinkListener/DeepLinkListener.tsx
packages/blockchain-wallet-v4-frontend/src/services/deepLinkListener/components/DeepLinkListener/DeepLinkListener.types.ts
packages/blockchain-wallet-v4-frontend/src/services/deepLinkListener/contexts/DeelLinkListenerContext/DeelLinkListenerContext.context.ts
packages/blockchain-wallet-v4-frontend/src/services/deepLinkListener/contexts/DeelLinkListenerContext/DeelLinkListenerContext.types.ts
packages/blockchain-wallet-v4-frontend/src/services/deepLinkListener/contexts/DeelLinkListenerContext/index.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.types.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/constants/NabuErrorDeepLinkActions.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/isNabuErrorCloseAction/index.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/isNabuErrorCloseAction/isNabuErrorCloseAction.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/isNabuErrorLaunchAction/index.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/isNabuErrorLaunchAction/isNabuErrorLaunchAction.ts

Update the generic nabu error to handle the new deep links
https://user-images.githubusercontent.com/99212903/179819942-7285ad3d-683e-48d6-a1b2-10539980733a.mov

fix(NabuError): update the nabu error actions to handle new API

---

packages/blockchain-wallet-v4-frontend/src/components/GenericError/ErrorIconWithSeverity/ErrorIconWithSeverity.tsx
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuError/GenericNabuError.tsx
packages/blockchain-wallet-v4-frontend/src/components/NabuErrorDeepLinkHandler/NabuErrorDeepLinkHandler.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/index.tsx
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/constants/NabuErrorDeepLinkActions.ts

- Update go to card deep link action to go to add card
- Update try different payment method to go to linked payment methods
- Add go to dashboard deep link action
- fix default nabu error icons
- handle nabu error in the add card page
https://user-images.githubusercontent.com/99212903/180467581-a3d8f773-9741-41b1-8749-ae8e653cb0f8.mov
https://user-images.githubusercontent.com/99212903/180467878-0e547606-dabc-4a46-ab05-b214638fa3e5.mov
https://user-images.githubusercontent.com/99212903/180468105-ed1b4e82-a423-443f-b1bc-1ee5c75fad79.mov
https://user-images.githubusercontent.com/99212903/180468178-ce97c4b5-6bc0-400f-b722-dd7f6020ab9f.mov

fix(NabuError): update deep link actions and visual fixes

---

packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/Account/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/Connected/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Currency/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Currency/list.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Currency/selection.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Currency/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Language/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Language/list.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Language/selection.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/Overal/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/General/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/Info/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/Networks/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/Overal/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/Settings/index.tsx

feat(plugin): settings page

---

packages/blockchain-wallet-v4-frontend/src/layouts/plugin/PluginLayout.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/ConnectDapp/Confirmation.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/ConnectDapp/Connected.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/ConnectDapp/Connecting.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/ConnectDapp/index.tsx

feat(plugin): connect dapp page

---

packages/blockchain-wallet-v4-frontend/src/components/Public/index.js
packages/blockchain-wallet-v4-frontend/src/hooks/useSelfCustodyCoinsBalances/useSelfCustodyCoinsBalances.tsx
packages/blockchain-wallet-v4-frontend/src/plugin/internal/index.ts
packages/blockchain-wallet-v4-frontend/src/plugin/tab.css
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterEmailOrGuid/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/EnterPassword/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/Wallet/TwoFA/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/SignupLink/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/plugin/CoinsList/Header.tsx

Added isPlugin checks for sign-up/sign-in pages according to the design
**Example:**

feat(plugin): added isPlugin checks for sign-up and sign-in components

---

packages/blockchain-wallet-v4-frontend/src/modals/Mobile/MobileNumberVerify/index.js

Fixes bug where 'change number' link would just re-render the verification modal. 

fix(mobile): show correct change mobile number modal

---

packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/actions.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx

This reverts commit 4effa238c4a002351bcbbc6d16b4baff3539b5d9.

fix(prices): hotfix to revert unfinished earn & pricing alignment changes

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/errors.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.types.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.types.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/index.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/index.ts
packages/blockchain-wallet-v4-frontend/src/store/index.js

Include nabu error tracking
Towards FWN-1742

Add nabu error id to tracking to release 4 70

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/errors.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/NabuError.types.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.test.ts
packages/blockchain-wallet-v4-frontend/src/services/errors/NabuError/utils/createNabuErrorAnalyticsInterceptor/createNabuErrorAnalyticsInterceptor.ts

feat(NabuError): include id in nabu error analytics

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

This is already fixed on development, but not here.

fix(order): fixing skip error display list

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/index.tsx

Handle the nabu error when the order is polling for confirmation

fix(BuySell): handle generic nabu error in order polling

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.silver.tsx

feat(trading limits): show different description message for US based T1 wallets and for LT entity

---

packages/blockchain-wallet-v4-frontend/webpack.config.dev.js

https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/main/README.md#options

fix(webpack): doubling the size of the memory limit for webpack

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/AddCardCheckoutDotCom/template.success.tsx

Handle back button in add card flyout

fix(AddCardFlyout): check the origin and correct dismiss flyout

---

packages/blockchain-wallet-v4-frontend/src/scenes/Interest/IntroCard/index.tsx

fix(spelling): fix rewards flow spelling

---

packages/blockchain-wallet-v4-frontend/src/data/components/utils/selectors.ts

fix(erc20s): dont uppercase erc20s so coin can be found on window

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/nfts.ts
packages/blockchain-wallet-v4-frontend/src/data/components/nfts/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/AssetViewOnly/AssetViewOnly.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/View/View.results.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Nfts/View/View.tsx

feat: add in nft web view analytics

---

packages/blockchain-wallet-v4-frontend/src/modals/Settings/SecondPassword/template.js
packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/AdvancedSecurity/SecondPasswordWallet/Settings/template.js

feat: update second password modal

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuErrorCard/GenericNabuErrorCard.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuErrorCard/GenericNabuErrorCard.styles.ts
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuErrorCard/GenericNabuErrorCard.tsx
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuErrorCard/GenericNabuErrorCard.types.ts
packages/blockchain-wallet-v4-frontend/src/components/GenericNabuErrorCard/index.ts
packages/blockchain-wallet-v4-frontend/src/components/Tag/Tag.stories.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tag/Tag.tsx
packages/blockchain-wallet-v4-frontend/src/components/Tag/Tag.types.ts
packages/blockchain-wallet-v4-frontend/src/components/Tag/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/Payment/Payment.styles.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/Payment/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/hooks/useBlockedPayments/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/hooks/useBlockedPayments/useBlockedPayments.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/hooks/useBlockedPayments/useBlockedPayments.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/Card/Card.styles.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/Card/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/hooks/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/hooks/useCardState/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/hooks/useCardState/useCardState.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/hooks/useCardState/useCardState.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

Add card optimization in the select payment and enter amount page
https://user-images.githubusercontent.com/99212903/184183636-27e5e773-c992-43b7-b33f-e904084664de.mov

feat: add card optimization to select payment and enter amount

---

packages/blockchain-wallet-v4/src/redux/data/eth/sagas.ts

fix: pagination for tx history

---

packages/blockchain-wallet-v4-frontend/src/data/goals/sagas.ts

fix(goals): remove multiple unnecessary fetch user calls from goals

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/NonCustodialTx/Confirmations/index.tsx
packages/blockchain-wallet-v4/src/redux/data/eth/selectors.js

https://blockchain.atlassian.net/browse/RI-699

fix: eth confirmations for transactions

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

Uses the payment card method when fetching for buy quotes

fix(BuySell): use correct payment type when fetching for quotes

---

packages/blockchain-wallet-v4/src/network/api/buySell/index.ts

fix(buysell): make pairs endpoint an authorized get request

---

packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/ShowAddress/index.tsx

feat: show network for asset

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx

feat(PaymentSelect): update padding and add divider to card optimization container

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/request/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/request/selectors.ts
packages/blockchain-wallet-v4/src/redux/data/coins/sagaRegister.ts
packages/blockchain-wallet-v4/src/redux/data/coins/sagas.ts
packages/blockchain-wallet-v4/src/redux/data/coins/slice.ts
packages/blockchain-wallet-v4/src/redux/data/coins/types.ts

feat: sub to currency on receive

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

feat(sb order): send proper object not a single variable

---

packages/blockchain-wallet-v4-frontend/src/data/misc/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/misc/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/misc/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/misc/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js

fix(ping manifest): use runtime file instead of manifest

---

packages/blockchain-info-components/src/Form/PasswordInput.js
packages/blockchain-info-components/src/Form/__snapshots__/PasswordInput.spec.js.snap
packages/blockchain-wallet-v4-frontend/src/data/rootSaga.js
packages/blockchain-wallet-v4-frontend/src/modals/ReferralLandingFlyout/ReferralLandingFlyout.tsx

feat(constellation): fixed issues with failing constellation import

---

packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/index.tsx

feat(tax center): load tax center reports if there are some pending

---

packages/blockchain-wallet-v4-frontend/src/components/Card/CowboysCard/CowboysCard.tsx
packages/blockchain-wallet-v4-frontend/src/components/Flyout/Header.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/modules/profile/selectors.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Header.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/OrderSummary/template.sdd.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CowboysPromo/RaffleEntered/RaffleEntered.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CowboysPromo/Signup/Signup.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CowboysPromo/VerifyId/VerifyId.tsx

fix(cowboys): styles, copy, and flow fixes

---

package.json

feat(gtag): use fixed version

---

packages/blockchain-wallet-v4-frontend/src/components/Card/CowboysCard/CowboysCard.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CowboysPromo/RaffleEntered/RaffleEntered.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CowboysPromo/Signup/Signup.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/CowboysPromo/VerifyId/VerifyId.tsx
packages/blockchain-wallet-v4-frontend/src/modals/index.tsx

feat(cowboys): added missing events

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankPlaid/Handler/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx

fix(plaid): add refresh flow for yodlee -> plaid upgrade path

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankPlaid/Handler/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankPlaid/index.tsx

fix(plaid): fixes error when adding a bank

---

package.json
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankPlaid/Handler/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/SelectBank/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/SelectBank/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/CryptoItem/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/CryptoItem/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx

Release/v4.72 into release/v4.73

---

packages/blockchain-wallet-v4-frontend/src/data/session/selectors.ts

Fixes issue with case sensitivity and login - makes search and matching session token for login email case insensitive

fix(session-token): make session token lookup case insensitive

---

package.json
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankYapily/Connect/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/selectors.ts
packages/blockchain-wallet-v4/src/network/api/buySell/index.ts

Release/v4.72 into release 4.73

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/slice.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/AddBankPlaid/Handler/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/BankList/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/DepositMethods/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/EnterAmount/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Withdraw/WithdrawalMethods/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Settings/General/LinkedBanks/index.tsx

fix(deposits): fixes various issues with deposits and withdrawals

---

packages/blockchain-wallet-v4-frontend/src/scenes/DebitCard/CardDashboard/CardDashboard.model.ts

feat(debit): adding new designs to debit card

---

packages/blockchain-wallet-v4-frontend/src/data/components/brokerage/sagas.ts

fix(plaid): check settlementType reason for deposits

---

packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Interest/DepositForm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Staking/DepositForm/DepositForm.selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Staking/DepositForm/DepositForm.template.success.tsx

Fix/stak 108/analytics

---

packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/ImportNFTs/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/Earn.model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/Earn.template.header.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/index.tsx

Fix/stak 110/learn more

---

packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Nfts/NftOrder/ImportNFTs/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/Earn.selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/EarnTable/SortableTable/SortableTable.model.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/EarnTable/SortableTable/SortableTable.types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/EarnTable/SortableTable/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/EarnTable/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/EarnTable/selectors.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Earn/index.tsx

Fix/stak 93/balance sorting

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/UpgradeNowSilver/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/styles.ts
packages/blockchain-wallet-v4-frontend/src/modals/Settings/TradingLimits/template.success.silver.tsx

Updated modal for upgrade to gold and trading limits in case of silver user

feat(trading limits): updated full verification modals to use new design

---

.github/CODEOWNERS

chore(codeowners): update codeowners

---

packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/VerifyEmail/index.tsx

Skips 'Select Product' screen if user's signup country is RU. Users can’t sign up to the Exchange due to 8th round of Sanctions 

fix(country-signup): add country check at email verification step

---

packages/blockchain-wallet-v4-frontend/src/modals/Staking/DepositForm/DepositForm.template.success.tsx

fix(staking-analytics): add missing analytic

---

packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/selectors.ts

* earn button should link to earn page

fix(earn-coinview): earn should link to earn page

---

packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/identityVerification/types.ts
packages/blockchain-wallet-v4-frontend/src/data/components/onboarding/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/sagaRegister.ts

This is just a improvement to convert JS based code to TS

feat(identity verification): moved js code to be TS

---

packages/blockchain-info-components/package.json
packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/components/Navbar/Navbar.tsx
yarn.lock

feat(constellation): updated constellation to most recent version

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Onboarding/components/StepCard/StepCard.tsx

Container fixed since Padding from constellation ruins the layout

fix(dex-onboarding): layout fixed

---

packages/blockchain-wallet-v4-frontend/package.json
packages/blockchain-wallet-v4-frontend/src/layouts/Dex/DexHeader/DexHeader.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Dex/DexHeader/index.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Dex/DexTemplate.tsx
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Header.tsx
yarn.lock

First version of constellation navigation to test inside DEX. Only layout and basic navigation is there. Still a lot to handle in the next PRs e.g. app QR code, user dropdown, 
Go to DEX and check it

feat(dex-nav): layout and base navigation

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/model.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SwapSettings/SwapSettings.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SwapSettings/constants.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SwapSettings/utils.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Dex.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/QuoteDetails/QuoteDetails.tsx

Slippage for fixed in terms of types (optionals removed) and logic

feat(dex-slippage): slippage form conn to swap

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SwapSettings/utils.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/ConfirmSwap/ConfirmSwap.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx
packages/blockchain-wallet-v4/src/network/api/dex/types.ts

fix(dex-slippage): slippage type fixed to number

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/model.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/SelectToken.selectors.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/SelectToken.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/components/ViewEtherscan/ViewEtherscan.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/components/ViewEtherscan/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/components/index.ts

feat(dex-etherscan): view coin on etherscan

---

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/EmailAuthLanding/index.tsx

fix(email-approval): move actions locally

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/scenes/SecurityCenter/BasicSecurity/TwoStepVerification/GoogleAuth/template.success.js
packages/blockchain-wallet-v4-frontend/src/scenes/TwoStepVerification/Authenticator/template.qrcode.tsx
packages/blockchain-wallet-v4-frontend/src/utils/helpers.ts

1. move regex to get mobile auth app qr code to helper file
2. add function to new 2fa setup

fix(auth-app): fix mobile code

---

packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/coins/eth.tsx
packages/blockchain-wallet-v4-frontend/src/data/coins/selectors/index.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Dex.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/hooks/useSceneResolver.ts

Reverts blockchain/blockchain-wallet-v4-frontend#5611

Revert "fix(dex): console logs added to debug"

---

packages/blockchain-wallet-v4-frontend/src/components/Card/ExchangePromo/ExchangePromo.tsx
packages/blockchain-wallet-v4-frontend/src/components/Card/ExchangePromo/index.tsx
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/exchangePromo.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/index.ts

feat(exchange-promo): add analytics

---

package.json
packages/blockchain-wallet-v4-frontend/src/assets/locales/en.json
packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts

Release/v4.79 into release/v4.80

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/buy.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/index.ts
packages/blockchain-wallet-v4-frontend/src/layouts/Wallet/MenuTop/Header.tsx
packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/index.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CryptoSelection/CryptoSelector/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/Payment/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/Accounts/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/LinkedPaymentAccounts/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Trade/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Home/PriceChart/Actions/template.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/actions.column.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/Table/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Prices/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Transactions/index.tsx

Add new analytics events for Buy functionality.

feat(Buy): update buy analytics

---

config/mocks/wallet-options-v4.json
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

fix(vgs): check for needing cvv and direct user to cvv screen

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

fix(quote): always include the payment method id when fetching a quote

---

packages/blockchain-wallet-v4-frontend/src/scenes/ActiveRewardsLearn/Header/index.tsx
packages/blockchain-wallet-v4/src/network/api/earn/types.ts

fix(active-rewards-learn-eligible): fix eligible check

---

packages/blockchain-wallet-v4-frontend/src/middleware/analyticsMiddleware/analytics.ts

fix(analytics): change middleware queuevent name

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendCrypto/sagas.ts

feat(send): since coins now have dynamic custody flag we still do not fully support it on FE side, so we have to open old modals in such case

---

packages/blockchain-wallet-v4-frontend/src/scenes/Earn/Table/MobileRow/index.tsx

* fix disable logic between desktop view and tablet view

fix(earn-table): fix responsive disable logic

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/AllowanceCheck/AllowanceCheck.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/AllowanceCheck/index.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/ConfirmSwap/ConfirmSwap.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx

It's just a layout with visibility logic of an allowance button. I'm preparing a mocked version of the whole flow before adding on chain interactions.

fix(dex-allowance): Layout (preparation before on chain interactions)

---

packages/blockchain-wallet-v4-frontend/src/modals/BuySell/CheckoutConfirm/template.success.tsx
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

fix(buy sell): check for optional depositTerms from quote endpoint

---

packages/blockchain-wallet-v4-frontend/src/data/components/swap/sagas/trackAccountsSelected.ts

Fixes old way of importing `notReachable` util.

fix(Swap): change how notReachable util is imported

---

packages/blockchain-wallet-v4-frontend/src/modals/Swap/PreviewSwap/index.tsx

fix(link): fix refund policy help article link

---

packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/Earn/Earn.models.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/Earn/Earn.types.ts
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/Earn/Slide/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Onboarding/Earn/index.tsx

* update copies
* remove learn more buttons
* set localstorage value on render instead of close

feat(earn-onboarding): update copies and remove learn more buttons

---

packages/blockchain-wallet-v4-frontend/src/modals/ActiveRewards/index.tsx

* fix active rewards flyout close logic

fix(active-rewards-flyout): fix active rewards close flyout logic

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/accountRecovery.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/login.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Wallet/SkipTwoFAVerificationRecovery/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Login/components/NeedHelpLink/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/TwoFAConfirmation/index.tsx

Merge recovery analytics into 4.82 in case there's a delay with 4.83. 

feat(account-recovery): add events for 2fa confirmation

---

packages/blockchain-wallet-v4-frontend/src/scenes/RecoverWallet/ResetAccount/ResetWarning/index.tsx

fix(copy): change button copy for account recovery v2

---

packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/constants.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/index.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/sagas/initialize.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/sagas/sagaRegister.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/selectors/index.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/testUtils/setupStore.ts
packages/blockchain-wallet-v4-frontend/src/data/remoteConfig/types.ts
packages/blockchain-wallet-v4-frontend/src/data/rootReducer.ts
packages/blockchain-wallet-v4-frontend/src/data/rootSaga.ts
packages/blockchain-wallet-v4-frontend/src/providers/RemoteConfigProvider/hooks/useRemoteConfigPresenter.test.tsx
packages/blockchain-wallet-v4-frontend/src/providers/RemoteConfigProvider/hooks/useRemoteConfigPresenter.ts
packages/blockchain-wallet-v4-frontend/src/providers/RemoteConfigProvider/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx
packages/blockchain-wallet-v4-frontend/webpackBuilder.js
packages/blockchain-wallet-v4/package.json
packages/blockchain-wallet-v4/src/network/api/firebase/index.ts
packages/blockchain-wallet-v4/src/network/api/index.ts
packages/blockchain-wallet-v4/src/network/api/remoteConfig/index.ts
yarn.lock

Adds Firebase Remote Config implementation using [Load new values for next startup](https://firebase.google.com/docs/remote-config/loading#strategy_3_load_new_values_for_next_startup) loading strategy. Should be a superior replacement for all existing feature flag management solutions.
This initial version supports only Boolean values.
Set `web_ff_super_app` to true in Firebase console then check Redux store for the value in `remoteConfig`. Be aware of [the SDK throttling](https://firebase.google.com/docs/remote-config/get-started?platform=web#throttling). In case if SDK request fails, you will still see default config in the Redux; however, instead of dispatching `remoteConfig/setConfig` - `remoteConfig/initializeFailed` will be dispatched.

feat(remoteConfig): add Firebase SDK

---

packages/blockchain-wallet-v4-frontend/src/data/components/sendEth/sagas.ts

fix(erc-20-custodial-fee): replace ETH with dynamic coin variable

---

package.json
packages/blockchain-wallet-v4-frontend/src/components/Form/CoinBalanceDropdown/index.tsx
packages/blockchain-wallet-v4-frontend/src/components/Form/CoinBalanceDropdown/selectors.ts
packages/blockchain-wallet-v4-frontend/src/components/Form/SelectBoxBtcAddresses/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/interest/sagas.utils.ts
packages/blockchain-wallet-v4-frontend/src/modals/Earn/ActiveRewards/DepositForm/DepositForm.template.success.tsx

Fix coindropdown component for active rewards.
add `showCustodialFirst` to display custodial as first item on dropdown
add address to custodial account, so it also defaults to custodial

Fix/earn 315/coindropdown

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/InstructionDetails.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/template.success.tsx
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

feat(wire): added intermmediatery bank details for wire transfers

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/InstructionDetails.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/types.ts
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

feat(wire): display wire details from BE

---

packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/InstructionDetails.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Brokerage/Banks/Deposit/WireInstructions/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/BankWireDetails/types.ts
packages/blockchain-wallet-v4/src/network/api/buySell/types.ts

Reverting changes from https://github.com/blockchain/blockchain-wallet-v4-frontend/pull/5799

fix(wire): revert display wire details from BE

---

packages/blockchain-wallet-v4-frontend/src/scenes/TaxCenter/template.tsx

feat(turbo-tax): copy

---

packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/CoinSelect/selectors.ts

* enable stx noncustodial send

chore(stx-nc-send): enable stx noncustodial send

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/SelectToken.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/hooks/useTokensListSearch.ts

* reset search value when user closes token list selection modal

fix(token-list): change search value to '' on close of token selection

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/SelectToken.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SelectToken/hooks/useTokensListSearch.ts
packages/blockchain-wallet-v4-frontend/src/modals/Dex/SwapSettings/SwapSettings.tsx

* remove infinite rerendering when entering custom slippage

Fix/dex 51/slippage

---

packages/blockchain-wallet-v4-frontend/src/modals/Earn/Staking/AccountSummary/AccountSummary.BalanceDropdown.template.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Earn/Staking/AccountSummary/AccountSummary.template.success.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Earn/Staking/WithdrawalForm/WithdrawalForm.model.tsx
packages/blockchain-wallet-v4-frontend/src/modals/Earn/Staking/WithdrawalForm/WithdrawalForm.template.success.tsx
packages/blockchain-wallet-v4/src/network/api/earn/types.ts

Add 'Unbonding' balance row to balance dropdown in Account Summary of staking. 

fix(staking): add balance row in dropdown for unbonding

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/QuoteDetails/QuoteDetails.tsx

fix(dex-swap-quote): fix min amount for fiat value

---

legacy-pages/js/import/wallet-import.js

fix(import): include actionName instead of making it a var

---

packages/blockchain-wallet-v4/src/network/api/dex/constants.ts
packages/blockchain-wallet-v4/src/network/api/dex/requests/getDexChainTokens.ts
packages/blockchain-wallet-v4/src/network/api/dex/requests/getDexChains.ts
packages/blockchain-wallet-v4/src/network/api/dex/requests/searchDexTokens.ts

chore(dex-gateway-api): update dex gateway apis

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/types.ts
packages/blockchain-wallet-v4-frontend/src/modals/RequestCrypto/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/AllowanceCheck/AllowanceCheck.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/AllowanceCheck/styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/ErrorMessage/ErrorMessage.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/FlipPairButton/styles.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/FormWrapper/FormWrapper.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPairWrapper/SwapPairWrapper.tsx

* add error mapping to DEX
* Add functionality where RequestCrypto modal can go directly to showAddress step

Feat/dex 54/errors

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/analytics.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/analytics/types/index.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/signup/types.ts

Request from data science to add country to user traits.

fix(country-trait): add country to user trait

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/NonEligible/NonEligible.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/ConfirmSwap/ConfirmSwap.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/SwapPair.tsx

* fixed input entered analytics
* fixed properties in confirmation analytics
* move ineligibility analytic to saga

Fix/dex 135/analytics

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts

fix(dex-quote): fix amount in quote param

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts

* stop polling when input is 0 or insufficient balance

fix(dex-fee): stop polling when input is 0 or insufficient balance

---

packages/blockchain-wallet-v4-frontend/src/components/Form/AmountFieldInput/index.tsx
packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/index.tsx
packages/blockchain-wallet-v4-frontend/src/modals/BuySell/EnterAmount/Checkout/template.success.tsx

- Amount now carries after selecting payment method
- Destructured props usage 
- Other minor fixes

fix(buy): show amount after selecting payment method

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/model.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/CompleteSwap/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/Swap.tsx

* preselect input token based on balance and native token

feat(dex-auto-input-select): 

---

packages/blockchain-wallet-v4-frontend/src/data/analytics/types/dexEvents.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/selectors.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/slice.ts
packages/blockchain-wallet-v4-frontend/src/data/components/dex/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/ConfirmSwap/ConfirmSwap.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/QuoteDetails/QuoteDetails.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/SwapPair.tsx
packages/blockchain-wallet-v4/src/network/api/dex/requests/getDexSwapQuote.ts
packages/blockchain-wallet-v4/src/network/api/dex/schemas.ts
packages/blockchain-wallet-v4/src/network/api/dex/types.ts

* update analytics
* enable counter input in dex swap module

Feat/growux 867/dex

---

packages/blockchain-wallet-v4-frontend/src/components/Flyout/model.tsx

* pass isDisabled to component, to render correctly

Fix/growux 1248/open banking

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/SwapPair.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/styles.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/utils/getZeroFiatAmountPreview.ts
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/utils/index.ts

* make input container larger
* subtext should match selected token subtext

Growux 1348

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/EnterSwapDetails/EnterSwapDetails.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/SwapPair/SwapPair.tsx

* fix analytics when user inputs into swap module

Growux 1330

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/BaseRateAndFees/BaseRateAndFees.tsx

fix(dex): fix base rates in swap module

---

packages/blockchain-wallet-v4-frontend/src/scenes/Dex/Swap/components/BaseRateAndFees/BaseRateAndFees.tsx

fix(dex): fix base rate symbols

---

package.json

chore(Release): v4.89.1

---

.release-it.json

fix(release): remove push: false

---

package.json

chore(Release): v4.89.2

---

package.json

chore(Release): v4.89.3

---

packages/blockchain-wallet-v4-frontend/src/modals/SendCrypto/EnterAmount/index.tsx

* add loading state when processing fee is calculating

Growux 1555

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts
packages/blockchain-wallet-v4/src/network/api/dex/index.ts
packages/blockchain-wallet-v4/src/network/api/dex/requests/getDexSwapQuote.ts

* skip validation when fetching quote when user is still ENTER_DETAILS step

feat(dex-quote)

---

packages/blockchain-wallet-v4-frontend/src/data/components/dex/sagas.ts

fetch quote when clicking max in dex

fix(dex-max): clicking max fetches quote

---

packages/blockchain-info-components/src/Modals/ModalBody.js
packages/blockchain-info-components/src/Modals/__snapshots__/ModalBody.spec.js.snap
packages/blockchain-wallet-v4-frontend/src/components/Navbar/MobileDropdown/template.tsx
packages/blockchain-wallet-v4-frontend/src/components/QRCode/Wrapper/index.js
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/template.error.exchange.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/ProductPicker/template.error.exchangeMobile.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/ContinueOnPhone.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/ModalBackground.svg
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/QRsModal.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/index.tsx

Adding an alert for TX users so they are redirected to download the mobile apps, where they can operate according to their regulations

feat(redirect): derivate TX users to mobile app

---

packages/blockchain-wallet-v4-frontend/src/data/components/buySell/sagas.ts

fix: fixed confirm order check to return order instead of attribute

---

package.json

chore(Release): v4.91.0

---

package.json

chore(Release): v4.90.2

---

packages/blockchain-wallet-v4-frontend/src/data/auth/sagas.ts
packages/blockchain-wallet-v4-frontend/src/data/custodial/types.ts
packages/blockchain-wallet-v4-frontend/src/scenes/ContinueOnPhone/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupCard/index.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/Signup/components/SignupForm/QRsModal.tsx
packages/blockchain-wallet-v4-frontend/src/scenes/app.tsx

Redirect user to phone when useExternalTradingAccount is enabled
